/* This file was automatically generated. Do not edit by hand. */

const {
  ldp,
  dcterms,
  xsd,
  ns4,
  vann,
  rdf,
  owl,
  rdfs,
  ns9,
  ns10,
  ns11,
  ns12,
  ns13,
  foaf,
  vs,
  ns16,
  ns17,
  ns18
} = {
  'ldp': 'http://www.w3.org/ns/ldp#',
  'dcterms': 'http://purl.org/dc/terms/',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'ns4': 'http://www.w3.org/data#',
  'vann': 'http://purl.org/vocab/vann/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'ns9': 'http://www.w3.org/2011/09/LinkedData/',
  'ns10': 'http://www.w3.org/2012/',
  'ns11': 'http://www.w3.org/TR/ldp-paging/',
  'ns12': 'http://www.w3.org/TR/ldp-ucr/',
  'ns13': 'http://www.w3.org/TR/ldp/',
  'foaf': 'http://xmlns.com/foaf/0.1/',
  'vs': 'http://www.w3.org/2003/06/sw-vocab-status/ns#',
  'ns16': 'http://csarven.ca/#',
  'ns17': 'https://rhiaro.co.uk/#',
  'ns18': 'https://www.w3.org/TR/ldn/'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 4; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(ldp),
      namedNode(`${dcterms}created`),
      literal(`2015-02-26`, namedNode(`${xsd}date`)),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${dcterms}creator`),
      blankNodes[0],
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${dcterms}creator`),
      blankNodes[1],
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${dcterms}creator`),
      blankNodes[2],
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${dcterms}description`),
      literal(`Vocabulary URIs defined in the Linked Data Platform (LDP) namespace.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${dcterms}publisher`),
      namedNode(`${ns4}W3C`),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${dcterms}title`),
      literal(`The W3C Linked Data Platform (LDP) Vocabulary`),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${vann}preferredNamespacePrefix`),
      literal(`ldp`),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${vann}preferredNamespaceUri`),
      literal(`http://www.w3.org/ns/ldp#`),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${rdfs}comment`),
      literal(`This ontology provides an informal representation of the concepts and terms as defined in the LDP specification.  Consult the LDP specification for normative reference.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${rdfs}label`),
      literal(`W3C Linked Data Platform (LDP)`),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${rdfs}seeAlso`),
      namedNode(ns9),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns10}ldp`),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${rdfs}seeAlso`),
      namedNode(ns11),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${rdfs}seeAlso`),
      namedNode(ns12),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${rdfs}seeAlso`),
      namedNode(ns13),
      namedNode(ldp)
    ),
    quad(
      namedNode(ldp),
      namedNode(`${foaf}maker`),
      blankNodes[3],
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Ascending`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Individual`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Ascending`),
      namedNode(`${rdfs}comment`),
      literal(`Ascending order.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Ascending`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Ascending`),
      namedNode(`${rdfs}label`),
      literal(`Ascending`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Ascending`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}BasicContainer`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}BasicContainer`),
      namedNode(`${rdfs}comment`),
      literal(`An LDPC that uses a predefined predicate to simply link to its contained resources.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}BasicContainer`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}BasicContainer`),
      namedNode(`${rdfs}label`),
      literal(`BasicContainer`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}BasicContainer`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ldp}Container`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}BasicContainer`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Container`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Container`),
      namedNode(`${rdfs}comment`),
      literal(`A Linked Data Platform RDF Source (LDP-RS) that also conforms to additional patterns and conventions for managing membership. Readers should refer to the specification defining this ontology for the list of behaviors associated with it.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Container`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Container`),
      namedNode(`${rdfs}label`),
      literal(`Container`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Container`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ldp}RDFSource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Container`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Descending`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Individual`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Descending`),
      namedNode(`${rdfs}comment`),
      literal(`Descending order.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Descending`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Descending`),
      namedNode(`${rdfs}label`),
      literal(`Descending`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Descending`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}DirectContainer`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}DirectContainer`),
      namedNode(`${rdfs}comment`),
      literal(`An LDPC that is similar to a LDP-DC but it allows an indirection with the ability to list as member a resource, such as a URI representing a real-world object, that is different from the resource that is created.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}DirectContainer`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}DirectContainer`),
      namedNode(`${rdfs}label`),
      literal(`DirectContainer`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}DirectContainer`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ldp}Container`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}DirectContainer`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}IndirectContainer`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}IndirectContainer`),
      namedNode(`${rdfs}comment`),
      literal(`An LDPC that has the flexibility of choosing what form the membership triples take.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}IndirectContainer`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}IndirectContainer`),
      namedNode(`${rdfs}label`),
      literal(`IndirectContainer`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}IndirectContainer`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ldp}Container`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}IndirectContainer`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}MemberSubject`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Individual`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}MemberSubject`),
      namedNode(`${rdfs}comment`),
      literal(`Used to indicate default and typical behavior for ldp:insertedContentRelation, where the member-URI value in the membership triple added when a creation request is successful is the URI assigned to the newly created resource.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}MemberSubject`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}MemberSubject`),
      namedNode(`${rdfs}label`),
      literal(`MemberSubject`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}MemberSubject`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}NonRDFSource`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}NonRDFSource`),
      namedNode(`${rdfs}comment`),
      literal(`A Linked Data Platform Resource (LDPR) whose state is NOT represented as RDF.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}NonRDFSource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}NonRDFSource`),
      namedNode(`${rdfs}label`),
      literal(`NonRDFSource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}NonRDFSource`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ldp}Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}NonRDFSource`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Page`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Page`),
      namedNode(`${rdfs}comment`),
      literal(`URI signifying that the resource is an in-sequence page resource, as defined by LDP Paging.  Typically used on Link rel='type' response headers.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Page`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Page`),
      namedNode(`${rdfs}label`),
      literal(`Page`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Page`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PageSortCriterion`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PageSortCriterion`),
      namedNode(`${rdfs}comment`),
      literal(`Element in the list of sorting criteria used by the server to assign container members to pages.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PageSortCriterion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PageSortCriterion`),
      namedNode(`${rdfs}label`),
      literal(`PageSortCriterion`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PageSortCriterion`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferContainment`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Individual`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferContainment`),
      namedNode(`${rdfs}comment`),
      literal(`URI identifying a LDPC's containment triples, for example to allow clients to express interest in receiving them.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferContainment`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferContainment`),
      namedNode(`${rdfs}label`),
      literal(`PreferContainment`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferContainment`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferEmptyContainer`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Individual`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferEmptyContainer`),
      namedNode(`${rdfs}comment`),
      literal(`Archaic alias for ldp:PreferMinimalContainer`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferEmptyContainer`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferEmptyContainer`),
      namedNode(`${rdfs}label`),
      literal(`PreferEmptyContainer`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferEmptyContainer`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ldp}PreferMinimalContainer`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferEmptyContainer`),
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${ldp}PreferMinimalContainer`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferEmptyContainer`),
      namedNode(`${vs}term_status`),
      literal(`archaic`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMembership`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Individual`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMembership`),
      namedNode(`${rdfs}comment`),
      literal(`URI identifying a LDPC's membership triples, for example to allow clients to express interest in receiving them.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMembership`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMembership`),
      namedNode(`${rdfs}label`),
      literal(`PreferMembership`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMembership`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMinimalContainer`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Individual`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMinimalContainer`),
      namedNode(`${rdfs}comment`),
      literal(`URI identifying the subset of a LDPC's triples present in an empty LDPC, for example to allow clients to express interest in receiving them.  Currently this excludes containment and membership triples, but in the future other exclusions might be added.  This definition is written to automatically exclude those new classes of triples.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMinimalContainer`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMinimalContainer`),
      namedNode(`${rdfs}label`),
      literal(`PreferMinimalContainer`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}PreferMinimalContainer`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}RDFSource`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}RDFSource`),
      namedNode(`${rdfs}comment`),
      literal(`A Linked Data Platform Resource (LDPR) whose state is represented as RDF.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}RDFSource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}RDFSource`),
      namedNode(`${rdfs}label`),
      literal(`RDFSource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}RDFSource`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ldp}Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}RDFSource`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Resource`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Resource`),
      namedNode(`${rdfs}comment`),
      literal(`A HTTP-addressable resource whose lifecycle is managed by a LDP server.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Resource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Resource`),
      namedNode(`${rdfs}label`),
      literal(`Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}Resource`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}constrainedBy`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}constrainedBy`),
      namedNode(`${rdfs}comment`),
      literal(`Links a resource with constraints that the server requires requests like creation and update to conform to.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}constrainedBy`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}constrainedBy`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}constrainedBy`),
      namedNode(`${rdfs}label`),
      literal(`constrainedBy`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}constrainedBy`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}constrainedBy`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}contains`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}contains`),
      namedNode(`${rdfs}comment`),
      literal(`Links a container with resources created through the container.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}contains`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}Container`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}contains`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}contains`),
      namedNode(`${rdfs}label`),
      literal(`contains`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}contains`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}contains`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}hasMemberRelation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}hasMemberRelation`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates which predicate is used in membership triples, and that the membership triple pattern is < membership-constant-URI , object-of-hasMemberRelation, member-URI >.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}hasMemberRelation`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}Container`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}hasMemberRelation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}hasMemberRelation`),
      namedNode(`${rdfs}label`),
      literal(`hasMemberRelation`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}hasMemberRelation`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}hasMemberRelation`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}inbox`),
      namedNode(`${dcterms}creator`),
      namedNode(`${ns16}i`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}inbox`),
      namedNode(`${dcterms}creator`),
      namedNode(`${ns17}me`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}inbox`),
      namedNode(`${dcterms}issued`),
      literal(`2016-09-29`, namedNode(`${xsd}date`)),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}inbox`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}inbox`),
      namedNode(`${rdfs}comment`),
      literal(`Links a resource to a container where notifications for the resource can be created and discovered.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}inbox`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns18),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}inbox`),
      namedNode(`${rdfs}label`),
      literal(`inbox`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}inbox`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}insertedContentRelation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}insertedContentRelation`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates which triple in a creation request should be used as the member-URI value in the membership triple added when the creation request is successful.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}insertedContentRelation`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}Container`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}insertedContentRelation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}insertedContentRelation`),
      namedNode(`${rdfs}label`),
      literal(`insertedContentRelation`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}insertedContentRelation`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}insertedContentRelation`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}isMemberOfRelation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}isMemberOfRelation`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates which predicate is used in membership triples, and that the membership triple pattern is < member-URI , object-of-isMemberOfRelation, membership-constant-URI >.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}isMemberOfRelation`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}Container`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}isMemberOfRelation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}isMemberOfRelation`),
      namedNode(`${rdfs}label`),
      literal(`isMemmberOfRelation`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}isMemberOfRelation`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}isMemberOfRelation`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}member`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}member`),
      namedNode(`${rdfs}comment`),
      literal(`LDP servers should use this predicate as the membership predicate if there is no obvious predicate from an application vocabulary to use.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}member`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}member`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}member`),
      namedNode(`${rdfs}label`),
      literal(`member`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}member`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}member`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}membershipResource`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}membershipResource`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates the membership-constant-URI in a membership triple.  Depending upon the membership triple pattern a container uses, as indicated by the presence of ldp:hasMemberRelation or ldp:isMemberOfRelation, the membership-constant-URI might occupy either the subject or object position in membership triples.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}membershipResource`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}Container`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}membershipResource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}membershipResource`),
      namedNode(`${rdfs}label`),
      literal(`membershipResource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}membershipResource`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}membershipResource`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSequence`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSequence`),
      namedNode(`${rdfs}comment`),
      literal(`Link to a page sequence resource, as defined by LDP Paging.  Typically used to communicate the sorting criteria used to allocate LDPC members to pages.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSequence`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSequence`),
      namedNode(`${rdfs}label`),
      literal(`Page`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSequence`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCollation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCollation`),
      namedNode(`${rdfs}comment`),
      literal(`The collation used to order the members across pages in a page sequence when comparing strings.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCollation`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}PageSortCriterion`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCollation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCollation`),
      namedNode(`${rdfs}label`),
      literal(`pageSortCollation`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCollation`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCollation`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCriteria`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCriteria`),
      namedNode(`${rdfs}comment`),
      literal(`Link to the list of sorting criteria used by the server in a representation.  Typically used on Link response headers as an extension link relation URI in the rel= parameter.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCriteria`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}Page`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCriteria`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCriteria`),
      namedNode(`${rdfs}label`),
      literal(`pageSortCriteria`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCriteria`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortCriteria`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortOrder`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortOrder`),
      namedNode(`${rdfs}comment`),
      literal(`The ascending/descending/etc order used to order the members across pages in a page sequence.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortOrder`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}PageSortCriterion`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortOrder`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortOrder`),
      namedNode(`${rdfs}label`),
      literal(`pageSortOrder`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortOrder`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Resource`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortOrder`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortPredicate`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortPredicate`),
      namedNode(`${rdfs}comment`),
      literal(`Predicate used to specify the order of the members across a page sequence's in-sequence page resources; it asserts nothing about the order of members in the representation of a single page.`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortPredicate`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ldp}PageSortCriterion`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortPredicate`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ldp),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortPredicate`),
      namedNode(`${rdfs}label`),
      literal(`pageSortPredicate`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortPredicate`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(ldp)
    ),
    quad(
      namedNode(`${ldp}pageSortPredicate`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(ldp)
    ),
    quad(
      blankNodes[0],
      namedNode(`${foaf}name`),
      literal(`Ashok Malhotra`),
      namedNode(ldp)
    ),
    quad(
      blankNodes[1],
      namedNode(`${foaf}name`),
      literal(`Steve Speicher`),
      namedNode(ldp)
    ),
    quad(
      blankNodes[3],
      namedNode(`${foaf}homepage`),
      namedNode(`${ns10}ldp`),
      namedNode(ldp)
    ),
    quad(
      blankNodes[2],
      namedNode(`${foaf}name`),
      literal(`John Arwe`),
      namedNode(ldp)
    ),

  ]
}
