/* This file was automatically generated. Do not edit by hand. */

const {
  csvw,
  dcterms,
  xsd,
  rdf,
  owl,
  rdfs,
  ns7,
  ns8,
  ns9,
  prov
} = {
  'csvw': 'http://www.w3.org/ns/csvw#',
  'dcterms': 'http://purl.org/dc/terms/',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'ns7': 'http://www.w3.org/TR/',
  'ns8': 'http://www.w3.org/ns/',
  'ns9': 'https://github.com/w3c/csvw/commit/',
  'prov': 'http://www.w3.org/ns/prov#'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 97; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(csvw),
      namedNode(`${dcterms}date`),
      literal(`2017-06-06`, namedNode(`${xsd}date`)),
      namedNode(csvw)
    ),
    quad(
      namedNode(csvw),
      namedNode(`${dcterms}description`),
      literal(`This document describes the RDFS vocabulary description used in the Metadata Vocabulary for Tabular Data [[tabular-metadata]] along with the default JSON-LD Context.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(csvw),
      namedNode(`${dcterms}title`),
      literal(`CSVW Namespace Vocabulary Terms`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(csvw),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(csvw)
    ),
    quad(
      namedNode(csvw),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns7}tabular-metadata`),
      namedNode(csvw)
    ),
    quad(
      namedNode(csvw),
      namedNode(`${owl}imports`),
      namedNode(`${ns8}prov`),
      namedNode(csvw)
    ),
    quad(
      namedNode(csvw),
      namedNode(`${owl}versionInfo`),
      namedNode(`${ns9}fcc9db20ba4de10e41e964eee1b5d01defa4c664`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Cell`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Cell`),
      namedNode(`${rdfs}comment`),
      literal(`A Cell represents a cell at the intersection of a Row and a Column within a Table.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Cell`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Cell`),
      namedNode(`${rdfs}label`),
      literal(`Cell`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Column`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Column`),
      namedNode(`${rdfs}comment`),
      literal(`A Column represents a vertical arrangement of Cells within a Table.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Column`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Column`),
      namedNode(`${rdfs}label`),
      literal(`Column Description`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Datatype`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Datatype`),
      namedNode(`${rdfs}comment`),
      literal(`Describes facets of a datatype.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Datatype`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Datatype`),
      namedNode(`${rdfs}label`),
      literal(`Datatype`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Dialect`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Dialect`),
      namedNode(`${rdfs}comment`),
      literal(`A Dialect Description provides hints to parsers about how to parse a linked file.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Dialect`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Dialect`),
      namedNode(`${rdfs}label`),
      literal(`Dialect Description`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Direction`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Direction`),
      namedNode(`${rdfs}comment`),
      literal(`The class of table/text directions.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Direction`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Direction`),
      namedNode(`${rdfs}label`),
      literal(`Direction`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ForeignKey`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ForeignKey`),
      namedNode(`${rdfs}comment`),
      literal(`Describes relationships between Columns in one or more Tables.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ForeignKey`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ForeignKey`),
      namedNode(`${rdfs}label`),
      literal(`Foreign Key Definition`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}JSON`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}JSON`),
      namedNode(`${rdfs}comment`),
      literal(`A literal containing JSON.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}JSON`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}JSON`),
      namedNode(`${rdfs}label`),
      literal(`JSON`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}JSON`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}NumericFormat`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}NumericFormat`),
      namedNode(`${rdfs}comment`),
      literal(`If the datatype is a numeric type, the format property indicates the expected format for that number. Its value must be either a single string or an object with one or more properties.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}NumericFormat`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}NumericFormat`),
      namedNode(`${rdfs}label`),
      literal(`Numeric Format`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Row`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Row`),
      namedNode(`${rdfs}comment`),
      literal(`A Row represents a horizontal arrangement of cells within a Table.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Row`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Row`),
      namedNode(`${rdfs}label`),
      literal(`Row`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Schema`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Schema`),
      namedNode(`${rdfs}comment`),
      literal(`A Schema is a definition of a tabular format that may be common to multiple tables.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Schema`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Schema`),
      namedNode(`${rdfs}label`),
      literal(`Schema`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Table`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Table`),
      namedNode(`${rdfs}comment`),
      literal(`An annotated table is a table that is annotated with additional metadata.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Table`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Table`),
      namedNode(`${rdfs}label`),
      literal(`Annotated Table`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}TableGroup`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}TableGroup`),
      namedNode(`${rdfs}comment`),
      literal(`A Group of Tables comprises a set of Annotated Tables and a set of annotations that relate to those Tables.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}TableGroup`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}TableGroup`),
      namedNode(`${rdfs}label`),
      literal(`Group of Tables`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}TableReference`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}TableReference`),
      namedNode(`${rdfs}comment`),
      literal(`An object property that identifies a referenced table and a set of referenced columns within that table.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}TableReference`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}TableReference`),
      namedNode(`${rdfs}label`),
      literal(`Table Reference`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Transformation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Transformation`),
      namedNode(`${rdfs}comment`),
      literal(`A Transformation Definition is a definition of how tabular data can be transformed into another format.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Transformation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}Transformation`),
      namedNode(`${rdfs}label`),
      literal(`Transformation Definition`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}aboutUrl`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}aboutUrl`),
      namedNode(`${rdfs}comment`),
      literal(`A URI template property that MAY be used to indicate what a cell contains information about.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}aboutUrl`),
      namedNode(`${rdfs}domain`),
      blankNodes[0],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}aboutUrl`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}aboutUrl`),
      namedNode(`${rdfs}label`),
      literal(`about URL`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}aboutUrl`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}uriTemplate`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}auto`),
      namedNode(`${rdf}type`),
      namedNode(`${csvw}Direction`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}auto`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates whether the tables in the group should be displayed based on the first character in the table that has a specific direction.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}auto`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}auto`),
      namedNode(`${rdfs}label`),
      literal(`auto`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}base`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}base`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that contains a single string: a term defined in the default context representing a built-in datatype URL, as listed above.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}base`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}base`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}base`),
      namedNode(`${rdfs}label`),
      literal(`base`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}base`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}column`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}column`),
      namedNode(`${rdfs}comment`),
      literal(`An array property of column descriptions as described in section 5.6 Columns.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}column`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}column`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}column`),
      namedNode(`${rdfs}label`),
      literal(`column`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}column`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}columnReference`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}columnReference`),
      namedNode(`${rdfs}comment`),
      literal(`A column reference property that holds either a single reference to a column description object within this schema, or an array of references. These form the referencing columns for the foreign key definition.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}columnReference`),
      namedNode(`${rdfs}domain`),
      blankNodes[1],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}columnReference`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}columnReference`),
      namedNode(`${rdfs}label`),
      literal(`column reference`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}columnReference`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}commentPrefix`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}commentPrefix`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that sets the comment prefix flag to the single provided value, which MUST be a string.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}commentPrefix`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}commentPrefix`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}commentPrefix`),
      namedNode(`${rdfs}label`),
      literal(`comment prefix`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}commentPrefix`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}csvEncodedTabularData`),
      namedNode(`${rdf}type`),
      namedNode(`${prov}Role`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}csvEncodedTabularData`),
      namedNode(`${rdfs}comment`),
      literal(`Describes the role of a CSV file in the tabular data mapping.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}csvEncodedTabularData`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}csvEncodedTabularData`),
      namedNode(`${rdfs}label`),
      literal(`CSV Encoded Tabular Data`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}datatype`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}datatype`),
      namedNode(`${rdfs}comment`),
      literal(`An object property that contains either a single string that is the main datatype of the values of the cell or a datatype description object. If the value of this property is a string, it MUST be one of the built-in datatypes defined in section 5.11.1 Built-in Datatypes or an absolute URL; if it is an object then it describes a more specialised datatype.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}datatype`),
      namedNode(`${rdfs}domain`),
      blankNodes[2],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}datatype`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}datatype`),
      namedNode(`${rdfs}label`),
      literal(`datatype`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}datatype`),
      namedNode(`${rdfs}range`),
      blankNodes[3],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}decimalChar`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}decimalChar`),
      namedNode(`${rdfs}comment`),
      literal(`A string whose value is used to represent a decimal point within the number.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}decimalChar`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}NumericFormat`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}decimalChar`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}decimalChar`),
      namedNode(`${rdfs}label`),
      literal(`decimal character`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}decimalChar`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}default`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}default`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property holding a single string that is used to create a default value for the cell in cases where the original string value is an empty string.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}default`),
      namedNode(`${rdfs}domain`),
      blankNodes[4],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}default`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}default`),
      namedNode(`${rdfs}label`),
      literal(`default`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}default`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}delimiter`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}delimiter`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that sets the delimiter flag to the single provided value, which MUST be a string.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}delimiter`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}delimiter`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}delimiter`),
      namedNode(`${rdfs}label`),
      literal(`delimiter`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}delimiter`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}describes`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}describes`),
      namedNode(`${rdfs}comment`),
      literal(`From IANA describes: The relationship A 'describes' B asserts that resource A provides a description of resource B. There are no constraints on the format or representation of either A or B, neither are there any further constraints on either resource.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}describes`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Row`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}describes`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}describes`),
      namedNode(`${rdfs}label`),
      literal(`describes`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}dialect`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}dialect`),
      namedNode(`${rdfs}comment`),
      literal(`An object property that provides a single dialect description. If provided, dialect provides hints to processors about how to parse the referenced files to create tabular data models for the tables in the group.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}dialect`),
      namedNode(`${rdfs}domain`),
      blankNodes[5],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}dialect`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}dialect`),
      namedNode(`${rdfs}label`),
      literal(`dialect`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}dialect`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}doubleQuote`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}doubleQuote`),
      namedNode(`${rdfs}comment`),
      literal(`A boolean atomic property that, if \`true\`, sets the escape character flag to \`"\`.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}doubleQuote`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}doubleQuote`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}doubleQuote`),
      namedNode(`${rdfs}label`),
      literal(`double quote`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}doubleQuote`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}boolean`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}encoding`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}encoding`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that sets the encoding flag to the single provided string value, which MUST be a defined in [[encoding]]. The default is "utf-8".`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}encoding`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}encoding`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}encoding`),
      namedNode(`${rdfs}label`),
      literal(`encoding`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}encoding`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}foreignKey`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}foreignKey`),
      namedNode(`${rdfs}comment`),
      literal(`For a Table: a list of foreign keys on the table.

For a Schema: an array property of foreign key definitions that define how the values from specified columns within this table link to rows within this table or other tables.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}foreignKey`),
      namedNode(`${rdfs}domain`),
      blankNodes[6],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}foreignKey`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}foreignKey`),
      namedNode(`${rdfs}label`),
      literal(`foreign key`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}foreignKey`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}ForeignKey`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}format`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}format`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that contains either a single string or an object that defines the format of a value of this type, used when parsing a string value as described in Parsing Cells in [[tabular-data-model]].`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}format`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}format`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}format`),
      namedNode(`${rdfs}label`),
      literal(`format`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}format`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}groupChar`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}groupChar`),
      namedNode(`${rdfs}comment`),
      literal(`A string whose value is used to group digits within the number.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}groupChar`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}NumericFormat`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}groupChar`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}groupChar`),
      namedNode(`${rdfs}label`),
      literal(`group character`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}groupChar`),
      namedNode(`${rdfs}range`),
      blankNodes[7],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}header`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}header`),
      namedNode(`${rdfs}comment`),
      literal(`A boolean atomic property that, if \`true\`, sets the header row count flag to \`1\`, and if \`false\` to \`0\`, unless headerRowCount is provided, in which case the value provided for the header property is ignored.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}header`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}header`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}header`),
      namedNode(`${rdfs}label`),
      literal(`header`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}header`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}boolean`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}headerRowCount`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}headerRowCount`),
      namedNode(`${rdfs}comment`),
      literal(`An numeric atomic property that sets the header row count flag to the single provided value, which must be a non-negative integer.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}headerRowCount`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}headerRowCount`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}headerRowCount`),
      namedNode(`${rdfs}label`),
      literal(`header row count`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}headerRowCount`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}inherit`),
      namedNode(`${rdf}type`),
      namedNode(`${csvw}Direction`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}inherit`),
      namedNode(`${rdfs}comment`),
      literal(`For \`textDirection\`, indicates that the direction is inherited from the \`tableDirection\` annotation of the \`table\`.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}inherit`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}inherit`),
      namedNode(`${rdfs}label`),
      literal(`inherit`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lang`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lang`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property giving a single string language code as defined by [[BCP47]].`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lang`),
      namedNode(`${rdfs}domain`),
      blankNodes[8],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lang`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lang`),
      namedNode(`${rdfs}label`),
      literal(`language`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lang`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}length`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}length`),
      namedNode(`${rdfs}comment`),
      literal(`The exact length of the value of the cell.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}length`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}length`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}length`),
      namedNode(`${rdfs}label`),
      literal(`length`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}length`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lineTerminators`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lineTerminators`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that sets the line terminators flag to either an array containing the single provided string value, or the provided array.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lineTerminators`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lineTerminators`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lineTerminators`),
      namedNode(`${rdfs}label`),
      literal(`line terminators`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}lineTerminators`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ltr`),
      namedNode(`${rdf}type`),
      namedNode(`${csvw}Direction`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ltr`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates whether the tables in the group should be displayed with the first column on the right.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ltr`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ltr`),
      namedNode(`${rdfs}label`),
      literal(`left to right`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxExclusive`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxExclusive`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that contains a single number that is the maximum valid value (exclusive).`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxExclusive`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxExclusive`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxExclusive`),
      namedNode(`${rdfs}label`),
      literal(`max exclusive`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxExclusive`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxInclusive`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxInclusive`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that contains a single number that is the maximum valid value (inclusive).`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxInclusive`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxInclusive`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxInclusive`),
      namedNode(`${rdfs}label`),
      literal(`max inclusive`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxInclusive`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxLength`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxLength`),
      namedNode(`${rdfs}comment`),
      literal(`A numeric atomic property that contains a single integer that is the maximum length of the value.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxLength`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxLength`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxLength`),
      namedNode(`${rdfs}label`),
      literal(`max length`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}maxLength`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minExclusive`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minExclusive`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that contains a single number that is the minimum valid value (exclusive).`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minExclusive`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minExclusive`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minExclusive`),
      namedNode(`${rdfs}label`),
      literal(`min exclusive`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minExclusive`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minInclusive`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minInclusive`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that contains a single number that is the minimum valid value (inclusive).`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minInclusive`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minInclusive`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minInclusive`),
      namedNode(`${rdfs}label`),
      literal(`min inclusive`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minInclusive`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minLength`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minLength`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that contains a single integer that is the minimum length of the value.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minLength`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minLength`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minLength`),
      namedNode(`${rdfs}label`),
      literal(`min length`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}minLength`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}name`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}name`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that gives a single canonical name for the column. The value of this property becomes the name annotation for the described column.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}name`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}name`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}name`),
      namedNode(`${rdfs}label`),
      literal(`name`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}name`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}note`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}note`),
      namedNode(`${rdfs}comment`),
      literal(`An array property that provides an array of objects representing arbitrary annotations on the annotated tabular data model.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}note`),
      namedNode(`${rdfs}domain`),
      blankNodes[9],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}note`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}note`),
      namedNode(`${rdfs}label`),
      literal(`note`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}null`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}null`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property giving the string or strings used for null values within the data. If the string value of the cell is equal to any one of these values, the cell value is \`null\`.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}null`),
      namedNode(`${rdfs}domain`),
      blankNodes[10],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}null`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}null`),
      namedNode(`${rdfs}label`),
      literal(`null`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}null`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ordered`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ordered`),
      namedNode(`${rdfs}comment`),
      literal(`A boolean atomic property taking a single value which indicates whether a list that is the value of the cell is ordered (if \`true\`) or unordered (if \`false\`).`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ordered`),
      namedNode(`${rdfs}domain`),
      blankNodes[11],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ordered`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ordered`),
      namedNode(`${rdfs}label`),
      literal(`ordered`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}ordered`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}boolean`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}pattern`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}pattern`),
      namedNode(`${rdfs}comment`),
      literal(`A regular expression string, in the syntax and interpreted as defined by [[ECMASCRIPT]].`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}pattern`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}NumericFormat`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}pattern`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}pattern`),
      namedNode(`${rdfs}label`),
      literal(`pattern`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}pattern`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}primaryKey`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}primaryKey`),
      namedNode(`${rdfs}comment`),
      literal(`For Schema: A column reference property that holds either a single reference to a column description object or an array of references.

For Row: a possibly empty list of cells whose values together provide a unique identifier for this row. This is similar to the name of a column.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}primaryKey`),
      namedNode(`${rdfs}domain`),
      blankNodes[12],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}primaryKey`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}primaryKey`),
      namedNode(`${rdfs}label`),
      literal(`primary key`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}primaryKey`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}propertyUrl`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}propertyUrl`),
      namedNode(`${rdfs}comment`),
      literal(`An URI template property that MAY be used to create a URI for a property if the table is mapped to another format. `, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}propertyUrl`),
      namedNode(`${rdfs}domain`),
      blankNodes[13],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}propertyUrl`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}propertyUrl`),
      namedNode(`${rdfs}label`),
      literal(`property URL`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}propertyUrl`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}uriTemplate`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}quoteChar`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}quoteChar`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that sets the quote character flag to the single provided value, which must be a string or \`null\`.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}quoteChar`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}quoteChar`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}quoteChar`),
      namedNode(`${rdfs}label`),
      literal(`quote char`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}quoteChar`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}reference`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}reference`),
      namedNode(`${rdfs}comment`),
      literal(`An object property that identifies a **referenced table** and a set of **referenced columns** within that table.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}reference`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}ForeignKey`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}reference`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}reference`),
      namedNode(`${rdfs}label`),
      literal(`reference`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}reference`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}TableReference`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}referencedRow`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}referencedRow`),
      namedNode(`${rdfs}comment`),
      literal(`A possibly empty list of pairs of a foreign key and a row in a table within the same group of tables.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}referencedRow`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Row`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}referencedRow`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}referencedRow`),
      namedNode(`${rdfs}label`),
      literal(`referenced rows`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}required`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}required`),
      namedNode(`${rdfs}comment`),
      literal(`A boolean atomic property taking a single value which indicates whether the cell must have a non-null value. The default is \`false\`. `, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}required`),
      namedNode(`${rdfs}domain`),
      blankNodes[14],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}required`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}required`),
      namedNode(`${rdfs}label`),
      literal(`required`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}required`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}boolean`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}resource`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}resource`),
      namedNode(`${rdfs}comment`),
      literal(`A link property holding a URL that is the identifier for a specific table that is being referenced.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}resource`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}TableReference`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}resource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}resource`),
      namedNode(`${rdfs}label`),
      literal(`resource`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}resource`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}row`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}row`),
      namedNode(`${rdfs}comment`),
      literal(`Relates a Table to each Row output.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}row`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}row`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}row`),
      namedNode(`${rdfs}label`),
      literal(`row`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}row`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}Row`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}row`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}member`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rowTitle`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rowTitle`),
      namedNode(`${rdfs}comment`),
      literal(`A column reference property that holds either a single reference to a column description object or an array of references.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rowTitle`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rowTitle`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rowTitle`),
      namedNode(`${rdfs}label`),
      literal(`row titles`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rowTitle`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rownum`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rownum`),
      namedNode(`${rdfs}comment`),
      literal(`The position of the row amongst the rows of the Annotated Tabl, starting from 1`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rownum`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rownum`),
      namedNode(`${rdfs}label`),
      literal(`row number`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rownum`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rtl`),
      namedNode(`${rdf}type`),
      namedNode(`${csvw}Direction`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rtl`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates whether the tables in the group should be displayed with the first column on the left.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rtl`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}rtl`),
      namedNode(`${rdfs}label`),
      literal(`right to left`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}schemaReference`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}schemaReference`),
      namedNode(`${rdfs}comment`),
      literal(`A link property holding a URL that is the identifier for a schema that is being referenced.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}schemaReference`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}TableReference`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}schemaReference`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}schemaReference`),
      namedNode(`${rdfs}label`),
      literal(`schema reference`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}schemaReference`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}scriptFormat`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}scriptFormat`),
      namedNode(`${rdfs}comment`),
      literal(`A link property giving the single URL for the format that is used by the script or template.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}scriptFormat`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Transformation`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}scriptFormat`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}scriptFormat`),
      namedNode(`${rdfs}label`),
      literal(`script format`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}scriptFormat`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}separator`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}separator`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that MUST have a single string value that is the character used to separate items in the string value of the cell.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}separator`),
      namedNode(`${rdfs}domain`),
      blankNodes[15],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}separator`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}separator`),
      namedNode(`${rdfs}label`),
      literal(`separator`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}separator`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipBlankRows`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipBlankRows`),
      namedNode(`${rdfs}comment`),
      literal(`An boolean atomic property that sets the \`skip blank rows\` flag to the single provided boolean value.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipBlankRows`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipBlankRows`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipBlankRows`),
      namedNode(`${rdfs}label`),
      literal(`skip blank rows`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipBlankRows`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}boolean`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipColumns`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipColumns`),
      namedNode(`${rdfs}comment`),
      literal(`An numeric atomic property that sets the \`skip columns\` flag to the single provided numeric value, which MUST be a non-negative integer.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipColumns`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipColumns`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipColumns`),
      namedNode(`${rdfs}label`),
      literal(`skip columns`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipColumns`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipInitialSpace`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipInitialSpace`),
      namedNode(`${rdfs}comment`),
      literal(`A boolean atomic property that, if \`true\`, sets the trim flag to "start". If \`false\`, to \`false\`.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipInitialSpace`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipInitialSpace`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipInitialSpace`),
      namedNode(`${rdfs}label`),
      literal(`skip initial space`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipInitialSpace`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}boolean`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipRows`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipRows`),
      namedNode(`${rdfs}comment`),
      literal(`An numeric atomic property that sets the \`skip rows\` flag to the single provided numeric value, which MUST be a non-negative integer.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipRows`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipRows`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipRows`),
      namedNode(`${rdfs}label`),
      literal(`skip rows`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}skipRows`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}source`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}source`),
      namedNode(`${rdfs}comment`),
      literal(`A single string atomic property that provides, if specified, the format to which the tabular data should be transformed prior to the transformation using the script or template.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}source`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Transformation`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}source`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}source`),
      namedNode(`${rdfs}label`),
      literal(`source`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}source`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}suppressOutput`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}suppressOutput`),
      namedNode(`${rdfs}comment`),
      literal(`A boolean atomic property. If \`true\`, suppresses any output that would be generated when converting a table or cells within a column.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}suppressOutput`),
      namedNode(`${rdfs}domain`),
      blankNodes[16],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}suppressOutput`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}suppressOutput`),
      namedNode(`${rdfs}label`),
      literal(`suppress output`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}suppressOutput`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}boolean`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}table`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}table`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an Table group to annotated tables.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}table`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}table`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}table`),
      namedNode(`${rdfs}label`),
      literal(`table`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}table`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}table`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}member`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableDirection`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableDirection`),
      namedNode(`${rdfs}comment`),
      literal(`One of \`rtl\`, \`ltr\` or \`auto\`. Indicates whether the tables in the group should be displayed with the first column on the right, on the left, or based on the first character in the table that has a specific direction.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableDirection`),
      namedNode(`${rdfs}domain`),
      blankNodes[17],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableDirection`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableDirection`),
      namedNode(`${rdfs}label`),
      literal(`table direction`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableDirection`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}Direction`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableSchema`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableSchema`),
      namedNode(`${rdfs}comment`),
      literal(`An object property that provides a single schema description as described in section 5.5 Schemas, used as the default for all the tables in the group`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableSchema`),
      namedNode(`${rdfs}domain`),
      blankNodes[18],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableSchema`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableSchema`),
      namedNode(`${rdfs}label`),
      literal(`table schema`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tableSchema`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tabularMetadata`),
      namedNode(`${rdf}type`),
      namedNode(`${prov}Role`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tabularMetadata`),
      namedNode(`${rdfs}comment`),
      literal(`Describes the role of a Metadata file in the tabular data mapping.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tabularMetadata`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}tabularMetadata`),
      namedNode(`${rdfs}label`),
      literal(`Tabular Metadata`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}targetFormat`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}targetFormat`),
      namedNode(`${rdfs}comment`),
      literal(`A link property giving the single URL for the format that will be created through the transformation.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}targetFormat`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Transformation`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}targetFormat`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}targetFormat`),
      namedNode(`${rdfs}label`),
      literal(`target format`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}targetFormat`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}textDirection`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}textDirection`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that must have a single value that is one of \`rtl\` or \`ltr\` (the default).`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}textDirection`),
      namedNode(`${rdfs}domain`),
      blankNodes[19],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}textDirection`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}textDirection`),
      namedNode(`${rdfs}label`),
      literal(`text direction`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}textDirection`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}Direction`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}title`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}title`),
      namedNode(`${rdfs}comment`),
      literal(`For a Transformation A natural language property that describes the format that will be generated from the transformation.

For a Column: A natural language property that provides possible alternative names for the column.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}title`),
      namedNode(`${rdfs}domain`),
      blankNodes[20],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}title`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}title`),
      namedNode(`${rdfs}label`),
      literal(`title`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}transformations`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}transformations`),
      namedNode(`${rdfs}comment`),
      literal(`An array property of transformation definitions that provide mechanisms to transform the tabular data into other formats.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}transformations`),
      namedNode(`${rdfs}domain`),
      blankNodes[21],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}transformations`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}transformations`),
      namedNode(`${rdfs}label`),
      literal(`transformations`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}transformations`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}Transformation`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}trim`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}trim`),
      namedNode(`${rdfs}comment`),
      literal(`An atomic property that, if the boolean \`true\`, sets the trim flag to \`true\` and if the boolean \`false\` to \`false\`. If the value provided is a string, sets the trim flag to the provided value, which must be one of "true", "false", "start" or "end".`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}trim`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Dialect`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}trim`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}trim`),
      namedNode(`${rdfs}label`),
      literal(`trim`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}trim`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}boolean`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}uriTemplate`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}uriTemplate`),
      namedNode(`${rdfs}comment`),
      literal(``, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}uriTemplate`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}uriTemplate`),
      namedNode(`${rdfs}label`),
      literal(`uri template`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}uriTemplate`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}url`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}url`),
      namedNode(`${rdfs}comment`),
      literal(`For a Table: This link property gives the single URL of the CSV file that the table is held in, relative to the location of the metadata document.

For a Transformation: A link property giving the single URL of the file that the script or template is held in, relative to the location of the metadata document.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}url`),
      namedNode(`${rdfs}domain`),
      blankNodes[22],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}url`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}url`),
      namedNode(`${rdfs}label`),
      literal(`url`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}url`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}valueUrl`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}valueUrl`),
      namedNode(`${rdfs}comment`),
      literal(`An URI template property that is used to map the values of cells into URLs.`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}valueUrl`),
      namedNode(`${rdfs}domain`),
      blankNodes[23],
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}valueUrl`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}valueUrl`),
      namedNode(`${rdfs}label`),
      literal(`valueUrl`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}valueUrl`),
      namedNode(`${rdfs}range`),
      namedNode(`${csvw}uriTemplate`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}virtual`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}virtual`),
      namedNode(`${rdfs}comment`),
      literal(`A boolean atomic property taking a single value which indicates whether the column is a virtual column not present in the original source`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}virtual`),
      namedNode(`${rdfs}domain`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}virtual`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(csvw),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}virtual`),
      namedNode(`${rdfs}label`),
      literal(`virtual`, 'en'),
      namedNode(csvw)
    ),
    quad(
      namedNode(`${csvw}virtual`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}boolean`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[23],
      namedNode(`${owl}unionOf`),
      blankNodes[24],
      namedNode(csvw)
    ),
    quad(
      blankNodes[25],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[25],
      namedNode(`${rdf}rest`),
      blankNodes[26],
      namedNode(csvw)
    ),
    quad(
      blankNodes[10],
      namedNode(`${owl}unionOf`),
      blankNodes[27],
      namedNode(csvw)
    ),
    quad(
      blankNodes[3],
      namedNode(`${owl}unionOf`),
      blankNodes[28],
      namedNode(csvw)
    ),
    quad(
      blankNodes[9],
      namedNode(`${owl}unionOf`),
      blankNodes[29],
      namedNode(csvw)
    ),
    quad(
      blankNodes[5],
      namedNode(`${owl}unionOf`),
      blankNodes[30],
      namedNode(csvw)
    ),
    quad(
      blankNodes[18],
      namedNode(`${owl}unionOf`),
      blankNodes[31],
      namedNode(csvw)
    ),
    quad(
      blankNodes[28],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Datatype`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[28],
      namedNode(`${rdf}rest`),
      blankNodes[32],
      namedNode(csvw)
    ),
    quad(
      blankNodes[20],
      namedNode(`${owl}unionOf`),
      blankNodes[33],
      namedNode(csvw)
    ),
    quad(
      blankNodes[7],
      namedNode(`${owl}unionOf`),
      blankNodes[34],
      namedNode(csvw)
    ),
    quad(
      blankNodes[0],
      namedNode(`${owl}unionOf`),
      blankNodes[35],
      namedNode(csvw)
    ),
    quad(
      blankNodes[14],
      namedNode(`${owl}unionOf`),
      blankNodes[36],
      namedNode(csvw)
    ),
    quad(
      blankNodes[1],
      namedNode(`${owl}unionOf`),
      blankNodes[37],
      namedNode(csvw)
    ),
    quad(
      blankNodes[38],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[38],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[39],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Transformation`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[39],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[8],
      namedNode(`${owl}unionOf`),
      blankNodes[40],
      namedNode(csvw)
    ),
    quad(
      blankNodes[17],
      namedNode(`${owl}unionOf`),
      blankNodes[41],
      namedNode(csvw)
    ),
    quad(
      blankNodes[15],
      namedNode(`${owl}unionOf`),
      blankNodes[42],
      namedNode(csvw)
    ),
    quad(
      blankNodes[34],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}NumericFormat`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[34],
      namedNode(`${rdf}rest`),
      blankNodes[43],
      namedNode(csvw)
    ),
    quad(
      blankNodes[37],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}ForeignKey`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[37],
      namedNode(`${rdf}rest`),
      blankNodes[44],
      namedNode(csvw)
    ),
    quad(
      blankNodes[13],
      namedNode(`${owl}unionOf`),
      blankNodes[45],
      namedNode(csvw)
    ),
    quad(
      blankNodes[21],
      namedNode(`${owl}unionOf`),
      blankNodes[46],
      namedNode(csvw)
    ),
    quad(
      blankNodes[6],
      namedNode(`${owl}unionOf`),
      blankNodes[47],
      namedNode(csvw)
    ),
    quad(
      blankNodes[2],
      namedNode(`${owl}unionOf`),
      blankNodes[48],
      namedNode(csvw)
    ),
    quad(
      blankNodes[12],
      namedNode(`${owl}unionOf`),
      blankNodes[49],
      namedNode(csvw)
    ),
    quad(
      blankNodes[16],
      namedNode(`${owl}unionOf`),
      blankNodes[50],
      namedNode(csvw)
    ),
    quad(
      blankNodes[33],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Transformation`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[33],
      namedNode(`${rdf}rest`),
      blankNodes[25],
      namedNode(csvw)
    ),
    quad(
      blankNodes[43],
      namedNode(`${rdf}first`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[43],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[32],
      namedNode(`${rdf}first`),
      namedNode(`${xsd}string`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[32],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[51],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[51],
      namedNode(`${rdf}rest`),
      blankNodes[39],
      namedNode(csvw)
    ),
    quad(
      blankNodes[50],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[50],
      namedNode(`${rdf}rest`),
      blankNodes[52],
      namedNode(csvw)
    ),
    quad(
      blankNodes[52],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[52],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[47],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[47],
      namedNode(`${rdf}rest`),
      blankNodes[38],
      namedNode(csvw)
    ),
    quad(
      blankNodes[42],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[42],
      namedNode(`${rdf}rest`),
      blankNodes[53],
      namedNode(csvw)
    ),
    quad(
      blankNodes[44],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableReference`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[44],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[53],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[53],
      namedNode(`${rdf}rest`),
      blankNodes[54],
      namedNode(csvw)
    ),
    quad(
      blankNodes[54],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[54],
      namedNode(`${rdf}rest`),
      blankNodes[55],
      namedNode(csvw)
    ),
    quad(
      blankNodes[55],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[55],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[35],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[35],
      namedNode(`${rdf}rest`),
      blankNodes[56],
      namedNode(csvw)
    ),
    quad(
      blankNodes[56],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[56],
      namedNode(`${rdf}rest`),
      blankNodes[57],
      namedNode(csvw)
    ),
    quad(
      blankNodes[57],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[57],
      namedNode(`${rdf}rest`),
      blankNodes[58],
      namedNode(csvw)
    ),
    quad(
      blankNodes[58],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[58],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[40],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[40],
      namedNode(`${rdf}rest`),
      blankNodes[59],
      namedNode(csvw)
    ),
    quad(
      blankNodes[59],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[59],
      namedNode(`${rdf}rest`),
      blankNodes[60],
      namedNode(csvw)
    ),
    quad(
      blankNodes[60],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[60],
      namedNode(`${rdf}rest`),
      blankNodes[61],
      namedNode(csvw)
    ),
    quad(
      blankNodes[22],
      namedNode(`${owl}unionOf`),
      blankNodes[51],
      namedNode(csvw)
    ),
    quad(
      blankNodes[61],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[61],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[45],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[45],
      namedNode(`${rdf}rest`),
      blankNodes[62],
      namedNode(csvw)
    ),
    quad(
      blankNodes[62],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[62],
      namedNode(`${rdf}rest`),
      blankNodes[63],
      namedNode(csvw)
    ),
    quad(
      blankNodes[63],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[63],
      namedNode(`${rdf}rest`),
      blankNodes[64],
      namedNode(csvw)
    ),
    quad(
      blankNodes[64],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[64],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[65],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[65],
      namedNode(`${rdf}rest`),
      blankNodes[66],
      namedNode(csvw)
    ),
    quad(
      blankNodes[66],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[66],
      namedNode(`${rdf}rest`),
      blankNodes[67],
      namedNode(csvw)
    ),
    quad(
      blankNodes[67],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[67],
      namedNode(`${rdf}rest`),
      blankNodes[68],
      namedNode(csvw)
    ),
    quad(
      blankNodes[68],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[68],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[48],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[48],
      namedNode(`${rdf}rest`),
      blankNodes[69],
      namedNode(csvw)
    ),
    quad(
      blankNodes[19],
      namedNode(`${owl}unionOf`),
      blankNodes[70],
      namedNode(csvw)
    ),
    quad(
      blankNodes[69],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[69],
      namedNode(`${rdf}rest`),
      blankNodes[71],
      namedNode(csvw)
    ),
    quad(
      blankNodes[71],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[71],
      namedNode(`${rdf}rest`),
      blankNodes[72],
      namedNode(csvw)
    ),
    quad(
      blankNodes[72],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[72],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[36],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[36],
      namedNode(`${rdf}rest`),
      blankNodes[73],
      namedNode(csvw)
    ),
    quad(
      blankNodes[73],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[73],
      namedNode(`${rdf}rest`),
      blankNodes[74],
      namedNode(csvw)
    ),
    quad(
      blankNodes[74],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[74],
      namedNode(`${rdf}rest`),
      blankNodes[75],
      namedNode(csvw)
    ),
    quad(
      blankNodes[75],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[75],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[31],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[31],
      namedNode(`${rdf}rest`),
      blankNodes[76],
      namedNode(csvw)
    ),
    quad(
      blankNodes[76],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[76],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[30],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[30],
      namedNode(`${rdf}rest`),
      blankNodes[77],
      namedNode(csvw)
    ),
    quad(
      blankNodes[11],
      namedNode(`${owl}unionOf`),
      blankNodes[78],
      namedNode(csvw)
    ),
    quad(
      blankNodes[77],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[77],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[29],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[29],
      namedNode(`${rdf}rest`),
      blankNodes[79],
      namedNode(csvw)
    ),
    quad(
      blankNodes[79],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[79],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[41],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[41],
      namedNode(`${rdf}rest`),
      blankNodes[80],
      namedNode(csvw)
    ),
    quad(
      blankNodes[80],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[80],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[46],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[46],
      namedNode(`${rdf}rest`),
      blankNodes[81],
      namedNode(csvw)
    ),
    quad(
      blankNodes[81],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[81],
      namedNode(`${rdf}rest`),
      blankNodes[82],
      namedNode(csvw)
    ),
    quad(
      blankNodes[82],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[82],
      namedNode(`${rdf}rest`),
      blankNodes[83],
      namedNode(csvw)
    ),
    quad(
      blankNodes[83],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[83],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[70],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[70],
      namedNode(`${rdf}rest`),
      blankNodes[84],
      namedNode(csvw)
    ),
    quad(
      blankNodes[4],
      namedNode(`${owl}unionOf`),
      blankNodes[65],
      namedNode(csvw)
    ),
    quad(
      blankNodes[84],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[84],
      namedNode(`${rdf}rest`),
      blankNodes[85],
      namedNode(csvw)
    ),
    quad(
      blankNodes[85],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[85],
      namedNode(`${rdf}rest`),
      blankNodes[86],
      namedNode(csvw)
    ),
    quad(
      blankNodes[86],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[86],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[24],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[24],
      namedNode(`${rdf}rest`),
      blankNodes[87],
      namedNode(csvw)
    ),
    quad(
      blankNodes[87],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[87],
      namedNode(`${rdf}rest`),
      blankNodes[88],
      namedNode(csvw)
    ),
    quad(
      blankNodes[88],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[88],
      namedNode(`${rdf}rest`),
      blankNodes[89],
      namedNode(csvw)
    ),
    quad(
      blankNodes[89],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[89],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[27],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[27],
      namedNode(`${rdf}rest`),
      blankNodes[90],
      namedNode(csvw)
    ),
    quad(
      blankNodes[90],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[90],
      namedNode(`${rdf}rest`),
      blankNodes[91],
      namedNode(csvw)
    ),
    quad(
      blankNodes[91],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[91],
      namedNode(`${rdf}rest`),
      blankNodes[92],
      namedNode(csvw)
    ),
    quad(
      blankNodes[49],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[49],
      namedNode(`${rdf}rest`),
      blankNodes[93],
      namedNode(csvw)
    ),
    quad(
      blankNodes[92],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[92],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[78],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}TableGroup`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[78],
      namedNode(`${rdf}rest`),
      blankNodes[94],
      namedNode(csvw)
    ),
    quad(
      blankNodes[94],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Table`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[94],
      namedNode(`${rdf}rest`),
      blankNodes[95],
      namedNode(csvw)
    ),
    quad(
      blankNodes[95],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Schema`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[95],
      namedNode(`${rdf}rest`),
      blankNodes[96],
      namedNode(csvw)
    ),
    quad(
      blankNodes[96],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Column`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[96],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[93],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Row`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[93],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[26],
      namedNode(`${rdf}first`),
      namedNode(`${csvw}Row`),
      namedNode(csvw)
    ),
    quad(
      blankNodes[26],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(csvw)
    ),

  ]
}
