import prefixesOnly from './lib/prefixesOnly.js'

const packagedPrefixes = {
  xsd: 'http://www.w3.org/2001/XMLSchema#',
  xkos: 'http://rdf-vocabulary.ddialliance.org/xkos#',
  xhv: 'http://www.w3.org/1999/xhtml/vocab#',
  wgs: 'http://www.w3.org/2003/01/geo/wgs84_pos#',
  wdrs: 'http://www.w3.org/2007/05/powder-s#',
  vso: 'http://purl.org/vso/ns#',
  vs: 'http://www.w3.org/2003/06/sw-vocab-status/ns#',
  void: 'http://rdfs.org/ns/void#',
  vcard: 'http://www.w3.org/2006/vcard/ns#',
  vann: 'http://purl.org/vocab/vann/',
  vaem: 'http://www.linkedmodel.org/schema/vaem#',
  unit: 'http://qudt.org/vocab/unit/',
  time: 'http://www.w3.org/2006/time#',
  test: 'http://www.w3.org/2006/03/test-description#',
  string: 'http://www.w3.org/2000/10/swap/string#',
  stat: 'http://www.w3.org/ns/posix/stat#',
  ssn: 'http://www.w3.org/ns/ssn/',
  sou: 'http://qudt.org/vocab/sou/',
  sosa: 'http://www.w3.org/ns/sosa/',
  solid: 'http://www.w3.org/ns/solid/terms#',
  skosxl: 'http://www.w3.org/2008/05/skos-xl#',
  skos: 'http://www.w3.org/2004/02/skos/core#',
  sioc: 'http://rdfs.org/sioc/ns#',
  shsh: 'http://www.w3.org/ns/shacl-shacl#',
  shex: 'http://www.w3.org/ns/shex#',
  sh: 'http://www.w3.org/ns/shacl#',
  sf: 'http://www.opengis.net/ont/sf#',
  set: 'http://www.w3.org/2000/10/swap/set#',
  sem: 'http://semanticweb.cs.vu.nl/2009/11/sem/',
  sdmx: 'http://purl.org/linked-data/sdmx#',
  sd: 'http://www.w3.org/ns/sparql-service-description#',
  schema: 'http://schema.org/',
  rss: 'http://purl.org/rss/1.0/',
  rr: 'http://www.w3.org/ns/r2rml#',
  rico: 'https://www.ica.org/standards/RiC/ontology#',
  rev: 'http://purl.org/stuff/rev#',
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
  rdfa: 'http://www.w3.org/ns/rdfa#',
  rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  rdau: 'http://rdaregistry.info/Elements/u/',
  qudt: 'http://qudt.org/schema/qudt/',
  quantitykind: 'http://qudt.org/vocab/quantitykind/',
  qkdv: 'http://qudt.org/vocab/dimensionvector/',
  qb: 'http://purl.org/linked-data/cube#',
  prov: 'http://www.w3.org/ns/prov#',
  prefix: 'http://qudt.org/vocab/prefix/',
  pim: 'http://www.w3.org/ns/pim/space#',
  owl: 'http://www.w3.org/2002/07/owl#',
  org: 'http://www.w3.org/ns/org#',
  oidc: 'http://www.w3.org/ns/solid/oidc#',
  og: 'http://ogp.me/ns#',
  oa: 'http://www.w3.org/ns/oa#',
  math: 'http://www.w3.org/2000/10/swap/math#',
  mads: 'http://www.loc.gov/mads/rdf/v1#',
  ma: 'http://www.w3.org/ns/ma-ont#',
  m4i: 'http://w3id.org/nfdi4ing/metadata4ing#',
  lvont: 'http://lexvo.org/ontology#',
  log: 'http://www.w3.org/2000/10/swap/log#',
  locn: 'http://www.w3.org/ns/locn#',
  list: 'http://www.w3.org/2000/10/swap/list#',
  ldp: 'http://www.w3.org/ns/ldp#',
  la: 'https://linked.art/ns/terms/',
  ical: 'http://www.w3.org/2002/12/cal/icaltzd#',
  hydra: 'http://www.w3.org/ns/hydra/core#',
  http: 'http://www.w3.org/2011/http#',
  gtfs: 'http://vocab.gtfs.org/terms#',
  gs1: 'https://gs1.org/voc/',
  grddl: 'http://www.w3.org/2003/g/data-view#',
  gr: 'http://purl.org/goodrelations/v1#',
  gn: 'http://www.geonames.org/ontology#',
  gml: 'http://www.opengis.net/ont/gml#',
  geor: 'http://www.opengis.net/def/rule/geosparql/',
  geof: 'http://www.opengis.net/def/function/geosparql/',
  geo: 'http://www.opengis.net/ont/geosparql#',
  frbr: 'http://purl.org/vocab/frbr/core#',
  foaf: 'http://xmlns.com/foaf/0.1/',
  exif: 'http://www.w3.org/2003/12/exif/ns#',
  ebucore: 'http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#',
  earl: 'http://www.w3.org/ns/earl#',
  duv: 'http://www.w3.org/ns/duv#',
  dtype: 'http://www.linkedmodel.org/schema/dtype#',
  dqv: 'http://www.w3.org/ns/dqv#',
  dpv: 'http://www.w3.org/ns/dpv#',
  dprod: 'https://ekgf.github.io/dprod/',
  doap: 'http://usefulinc.com/ns/doap#',
  discipline: 'http://qudt.org/vocab/discipline/',
  dig: 'http://www.ics.forth.gr/isl/CRMdig/',
  dcterms: 'http://purl.org/dc/terms/',
  dcmitype: 'http://purl.org/dc/dcmitype/',
  dcat: 'http://www.w3.org/ns/dcat#',
  dcam: 'http://purl.org/dc/dcam/',
  dc11: 'http://purl.org/dc/elements/1.1/',
  dbo: 'http://dbpedia.org/ontology/',
  'dash-sparql': 'http://datashapes.org/sparql#',
  dash: 'http://datashapes.org/dash#',
  cur: 'http://qudt.org/vocab/currency/',
  cube: 'https://cube.link/',
  ctag: 'http://commontag.org/ns#',
  csvw: 'http://www.w3.org/ns/csvw#',
  crm: 'http://www.cidoc-crm.org/cidoc-crm/',
  constant: 'http://qudt.org/vocab/constant/',
  cnt: 'http://www.w3.org/2011/content#',
  cert: 'http://www.w3.org/ns/auth/cert#',
  cc: 'http://creativecommons.org/ns#',
  bibo: 'http://purl.org/ontology/bibo/',
  as: 'https://www.w3.org/ns/activitystreams#',
  acl: 'http://www.w3.org/ns/auth/acl#',
}

const prefixes = {
  ...packagedPrefixes,
  ...prefixesOnly,
} as const

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface Prefixes extends Readonly<typeof prefixes> {

}
export interface CustomPrefixes {
  [key: string]: string
}

export default prefixes as Prefixes & CustomPrefixes
