module.exports = {
  as: { skip: true },
  cc: { file: 'https://creativecommons.org/schema.rdf' },
  ctag: { skip: true },
  geo: { file: 'http://www.modelservers.org/public/ontologies/vcon/geosparql_vocab_all.rdf' },
  gml: { skip: true },
  gtfs: { mediaType: 'text/n3' },
  ical: { skip: true },
  qb: { mediaType: 'text/turtle' },
  rev: { skip: true },
  rif: { skip: true },
  rss: { file: 'http://purl.org/rss/1.0/schema.rdf' },
  schema: { file: 'http://schema.org/version/latest/schema.nt' },
  sf: { skip: true },
  sioc: { skip: true },
  v: { skip: true },
  void: { file: 'http://vocab.deri.ie/void.ttl' },
  wdr: { skip: true },
  wdrs: { skip: true },
  xhv: { skip: true },
  xml: { skip: true },
  xsd: { file: 'https://raw.githubusercontent.com/ruby-rdf/rdf/develop/etc/xsd.ttl', mediaType: 'text/turtle' }
}
