/* This file was automatically generated. Do not edit by hand. */

const {
  http,
  rdf,
  rdfs,
  owl,
  ns5,
  cnt,
  xsd,
  dcterms,
  ns9,
  ns10,
  ns11,
  ns12
} = {
  'http': 'http://www.w3.org/2011/http#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'ns5': 'http://www.ietf.org/rfc/',
  'cnt': 'http://www.w3.org/2011/content#',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'dcterms': 'http://purl.org/dc/terms/',
  'ns9': 'http://www.w3.org/2011/',
  'ns10': 'http://www.w3.org/TR/HTTP-in-RDF/',
  'ns11': 'http://www.w3.org/TR/Content-in-RDF/',
  'ns12': 'http://www.w3.org/WAI/intro/'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(`${http}Connection`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Connection`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Connection`),
      namedNode(`${rdfs}comment`),
      literal(`A connection used for HTTP transfer.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Connection`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Connection`),
      namedNode(`${rdfs}label`),
      literal(`Connection`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}EntityHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}EntityHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}EntityHeader`),
      namedNode(`${rdfs}comment`),
      literal(`An entity header in an HTTP message.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}EntityHeader`),
      namedNode(`${rdfs}label`),
      literal(`Entity Header`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}EntityHeader`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${http}MessageHeader`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}GeneralHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}GeneralHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}GeneralHeader`),
      namedNode(`${rdfs}comment`),
      literal(`A general header in an HTTP message.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}GeneralHeader`),
      namedNode(`${rdfs}label`),
      literal(`General Header`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}GeneralHeader`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${http}MessageHeader`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}HeaderElement`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}HeaderElement`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}HeaderElement`),
      namedNode(`${rdfs}comment`),
      literal(`A part of a deconstructed header value.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}HeaderElement`),
      namedNode(`${rdfs}label`),
      literal(`Header Element`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}HeaderName`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}HeaderName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}HeaderName`),
      namedNode(`${rdfs}comment`),
      literal(`A header name.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}HeaderName`),
      namedNode(`${rdfs}label`),
      literal(`Header Name`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Message`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Message`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Message`),
      namedNode(`${rdfs}comment`),
      literal(`An HTTP message.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Message`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Message`),
      namedNode(`${rdfs}label`),
      literal(`Message`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}MessageHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}MessageHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}MessageHeader`),
      namedNode(`${rdfs}comment`),
      literal(`A header in an HTTP message.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}MessageHeader`),
      namedNode(`${rdfs}label`),
      literal(`Message Header`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Method`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Method`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Method`),
      namedNode(`${rdfs}comment`),
      literal(`The HTTP method used for the request.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Method`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Method`),
      namedNode(`${rdfs}label`),
      literal(`Method`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Parameter`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Parameter`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Parameter`),
      namedNode(`${rdfs}comment`),
      literal(`A parameter for a part of a header value.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Parameter`),
      namedNode(`${rdfs}label`),
      literal(`Parameter`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Request`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Request`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Request`),
      namedNode(`${rdfs}comment`),
      literal(`An HTTP request.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Request`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Request`),
      namedNode(`${rdfs}label`),
      literal(`Request`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Request`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${http}Message`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}RequestHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}RequestHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}RequestHeader`),
      namedNode(`${rdfs}comment`),
      literal(`A header in an HTTP request message.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}RequestHeader`),
      namedNode(`${rdfs}label`),
      literal(`Request Header`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}RequestHeader`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${http}MessageHeader`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Response`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Response`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Response`),
      namedNode(`${rdfs}comment`),
      literal(`An HTTP response.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Response`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Response`),
      namedNode(`${rdfs}label`),
      literal(`Response`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}Response`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${http}Message`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}ResponseHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}ResponseHeader`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}ResponseHeader`),
      namedNode(`${rdfs}comment`),
      literal(`A header in an HTTP response message.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}ResponseHeader`),
      namedNode(`${rdfs}label`),
      literal(`Response Header`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}ResponseHeader`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${http}MessageHeader`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}StatusCode`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}StatusCode`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}StatusCode`),
      namedNode(`${rdfs}comment`),
      literal(`The status code of an HTTP response.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}StatusCode`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}StatusCode`),
      namedNode(`${rdfs}label`),
      literal(`Status code`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}absolutePath`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}absolutePath`),
      namedNode(`${rdfs}comment`),
      literal(`The absolute path sort of request URI.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}absolutePath`),
      namedNode(`${rdfs}label`),
      literal(`Absolute path`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}absolutePath`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${http}requestURI`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}absoluteURI`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}absoluteURI`),
      namedNode(`${rdfs}comment`),
      literal(`The absolute request URI.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}absoluteURI`),
      namedNode(`${rdfs}label`),
      literal(`Absolute URI`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}absoluteURI`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${http}requestURI`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}authority`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}authority`),
      namedNode(`${rdfs}comment`),
      literal(`The authority sort of request URI.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}authority`),
      namedNode(`${rdfs}label`),
      literal(`Authority`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}authority`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${http}requestURI`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}body`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}body`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}body`),
      namedNode(`${rdfs}comment`),
      literal(`The entity body of an HTTP message.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}body`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Message`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}body`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}body`),
      namedNode(`${rdfs}label`),
      literal(`Entity Body`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}body`),
      namedNode(`${rdfs}range`),
      namedNode(`${cnt}ContentAsBase64`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}connectionAuthority`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}connectionAuthority`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}connectionAuthority`),
      namedNode(`${rdfs}comment`),
      literal(`The authority of a connection used for the HTTP transfer.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}connectionAuthority`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Connection`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}connectionAuthority`),
      namedNode(`${rdfs}label`),
      literal(`Connection authority`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}connectionAuthority`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementName`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementName`),
      namedNode(`${rdfs}comment`),
      literal(`The name of a header element.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}HeaderElement`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementName`),
      namedNode(`${rdfs}label`),
      literal(`Header element name`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementName`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementValue`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementValue`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementValue`),
      namedNode(`${rdfs}comment`),
      literal(`The value of a header element.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementValue`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}HeaderElement`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementValue`),
      namedNode(`${rdfs}label`),
      literal(`Header element value`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}elementValue`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldName`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldName`),
      namedNode(`${rdfs}comment`),
      literal(`The name of an HTTP header field.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}MessageHeader`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldName`),
      namedNode(`${rdfs}label`),
      literal(`Field name`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldName`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldValue`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldValue`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldValue`),
      namedNode(`${rdfs}comment`),
      literal(`The value of an HTTP header field.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldValue`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}MessageHeader`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldValue`),
      namedNode(`${rdfs}label`),
      literal(`Field value`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}fieldValue`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}hdrName`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}hdrName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}hdrName`),
      namedNode(`${rdfs}comment`),
      literal(`The name of an HTTP header.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}hdrName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}MessageHeader`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}hdrName`),
      namedNode(`${rdfs}label`),
      literal(`Header name`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}hdrName`),
      namedNode(`${rdfs}range`),
      namedNode(`${http}HeaderName`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headerElements`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headerElements`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headerElements`),
      namedNode(`${rdfs}comment`),
      literal(`The deconstructed parts of an HTTP header value.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headerElements`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}MessageHeader`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headerElements`),
      namedNode(`${rdfs}label`),
      literal(`Header elements`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headers`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headers`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headers`),
      namedNode(`${rdfs}comment`),
      literal(`The headers in an HTTP message.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headers`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Message`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headers`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}headers`),
      namedNode(`${rdfs}label`),
      literal(`Headers`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}httpVersion`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}httpVersion`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}httpVersion`),
      namedNode(`${rdfs}comment`),
      literal(`The HTTP version of an HTTP message.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}httpVersion`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Message`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}httpVersion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}httpVersion`),
      namedNode(`${rdfs}label`),
      literal(`HTTP version`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}httpVersion`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}methodName`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}methodName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}methodName`),
      namedNode(`${rdfs}comment`),
      literal(`The HTTP method name used for the HTTP request.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}methodName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Request`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}methodName`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}methodName`),
      namedNode(`${rdfs}label`),
      literal(`Method name`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}methodName`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}mthd`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}mthd`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}mthd`),
      namedNode(`${rdfs}comment`),
      literal(`The HTTP method used for the HTTP request.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}mthd`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Request`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}mthd`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}mthd`),
      namedNode(`${rdfs}label`),
      literal(`Method`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}mthd`),
      namedNode(`${rdfs}range`),
      namedNode(`${http}Method`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramName`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramName`),
      namedNode(`${rdfs}comment`),
      literal(`The name of a parameter in a part of a deconstructed HTTP header value.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Parameter`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramName`),
      namedNode(`${rdfs}label`),
      literal(`Parameter name`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramName`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramValue`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramValue`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramValue`),
      namedNode(`${rdfs}comment`),
      literal(`The value of a parameter in a part of a deconstructed HTTP header value.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramValue`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Parameter`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramValue`),
      namedNode(`${rdfs}label`),
      literal(`Parameter value`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}paramValue`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}params`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}params`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}params`),
      namedNode(`${rdfs}comment`),
      literal(`The parameters in a part of a deconstructed HTTP header value.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}params`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}HeaderElement`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}params`),
      namedNode(`${rdfs}label`),
      literal(`Header parameters`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}reasonPhrase`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}reasonPhrase`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}reasonPhrase`),
      namedNode(`${rdfs}comment`),
      literal(`The reason phrase (status text) of an HTTP response.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}reasonPhrase`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Response`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}reasonPhrase`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}reasonPhrase`),
      namedNode(`${rdfs}label`),
      literal(`Reason phrase`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}reasonPhrase`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requestURI`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requestURI`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requestURI`),
      namedNode(`${rdfs}comment`),
      literal(`The request URI of an HTTP request.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requestURI`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Request`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requestURI`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requestURI`),
      namedNode(`${rdfs}label`),
      literal(`Request URI`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requestURI`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requests`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requests`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requests`),
      namedNode(`${rdfs}comment`),
      literal(`The HTTP requests made via a connection.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requests`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Connection`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requests`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}requests`),
      namedNode(`${rdfs}label`),
      literal(`Requests`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}resp`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}resp`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}resp`),
      namedNode(`${rdfs}comment`),
      literal(`The HTTP response sent in answer to an HTTP request.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}resp`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Request`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}resp`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}resp`),
      namedNode(`${rdfs}label`),
      literal(`Response`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}resp`),
      namedNode(`${rdfs}range`),
      namedNode(`${http}Response`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}sc`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}sc`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}sc`),
      namedNode(`${rdfs}comment`),
      literal(`The status code of an HTTP response.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}sc`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Response`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}sc`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}sc`),
      namedNode(`${rdfs}label`),
      literal(`Status code`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}sc`),
      namedNode(`${rdfs}range`),
      namedNode(`${http}StatusCode`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeNumber`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeNumber`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeNumber`),
      namedNode(`${rdfs}comment`),
      literal(`The status code number.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeNumber`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}StatusCode`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeNumber`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeNumber`),
      namedNode(`${rdfs}label`),
      literal(`Status code`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeNumber`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}int`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeNumber`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${dcterms}identifier`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeValue`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeValue`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeValue`),
      namedNode(`${rdfs}comment`),
      literal(`The status code value of an HTTP response.`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeValue`),
      namedNode(`${rdfs}domain`),
      namedNode(`${http}Response`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeValue`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}rfc2616.txt`),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeValue`),
      namedNode(`${rdfs}label`),
      literal(`Status code`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${http}statusCodeValue`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(http)
    ),
    quad(
      namedNode(`${ns9}http`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(http)
    ),
    quad(
      namedNode(`${ns9}http`),
      namedNode(`${rdfs}comment`),
      literal(`A namespace for describing HTTP messages (http://www.w3.org/Protocols/rfc2616/rfc2616.html)`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${ns9}http`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns10),
      namedNode(http)
    ),
    quad(
      namedNode(`${ns9}http`),
      namedNode(`${rdfs}label`),
      literal(`HTTP in RDF`, 'en'),
      namedNode(http)
    ),
    quad(
      namedNode(`${ns9}http`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(ns11),
      namedNode(http)
    ),
    quad(
      namedNode(`${ns9}http`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns12}earl`),
      namedNode(http)
    ),
    quad(
      namedNode(`${ns9}http`),
      namedNode(`${owl}imports`),
      namedNode(dcterms),
      namedNode(http)
    ),
    quad(
      namedNode(`${ns9}http`),
      namedNode(`${owl}imports`),
      namedNode(cnt),
      namedNode(http)
    ),
    quad(
      namedNode(`${ns9}http`),
      namedNode(`${owl}versionInfo`),
      literal(`Working Draft 29 April 2011`, 'en'),
      namedNode(http)
    ),

  ]
}
