/* This file was automatically generated. Do not edit by hand. */

const {
  dc11,
  rdf,
  owl,
  ma,
  rdfs,
  xsd,
  ns7,
  ns8
} = {
  'dc11': 'http://purl.org/dc/elements/1.1/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'ma': 'http://www.w3.org/ns/ma-ont#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'ns7': 'http://www.w3.org/ns/',
  'ns8': 'http://dublincore.org/2008/01/14/'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 8; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(`${dc11}date`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${owl}Thing`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Agent`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Agent`),
      namedNode(`${rdfs}comment`),
      literal(`A person or organisation contributing to the media resource.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Agent`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}Collection`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Agent`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}Location`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Agent`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Agent`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Agent`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}TargetAudience`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}AudioTrack`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}AudioTrack`),
      namedNode(`${rdfs}comment`),
      literal(`A specialisation of Track for Audio to provide a link to specific data properties such as sampleRate, etc. Specialisation is defined through object properties.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}AudioTrack`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ma}Track`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}AudioTrack`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}DataTrack`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}AudioTrack`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}VideoTrack`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Collection`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Collection`),
      namedNode(`${rdfs}comment`),
      literal(`Any group of media resource e.g. a series.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Collection`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}Location`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Collection`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Collection`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Collection`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}TargetAudience`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}DataTrack`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}DataTrack`),
      namedNode(`${rdfs}comment`),
      literal(`Ancillary data track e.g. captioning  in addition to video and audio tracks. Specialisation is made through the use of appropriate object properties.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}DataTrack`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ma}Track`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}DataTrack`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}VideoTrack`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Image`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Image`),
      namedNode(`${rdfs}comment`),
      literal(`A still image / thumbnail / key frame related to the media resource or being the media resource itself.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Image`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Location`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Location`),
      namedNode(`${rdfs}comment`),
      literal(`A location related to the media resource, e.g. depicted in the resource (possibly fictional) or where the resource was created (shooting location), etc.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Location`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Location`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Location`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}TargetAudience`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}MediaFragment`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}MediaFragment`),
      namedNode(`${rdfs}comment`),
      literal(`A media fragment (spatial, temporal, track...) composing a media resource. In other ontologies fragment is sometimes referred to as a 'part' or 'segment'.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}MediaFragment`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}MediaResource`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}MediaResource`),
      namedNode(`${rdfs}comment`),
      literal(`An image or an audiovisual media resource, which can be composed of one or more fragment / track.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}MediaResource`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}MediaResource`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}TargetAudience`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Organisation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Organisation`),
      namedNode(`${rdfs}comment`),
      literal(`An organisation or moral agent.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Organisation`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ma}Agent`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Organisation`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}Person`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Person`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Person`),
      namedNode(`${rdfs}comment`),
      literal(`A physical person.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Person`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ma}Agent`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Rating`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Rating`),
      namedNode(`${rdfs}comment`),
      literal(`Information about the rating given to a media resource.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Rating`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${ma}TargetAudience`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}TargetAudience`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}TargetAudience`),
      namedNode(`${rdfs}comment`),
      literal(`Information about The target audience (target region, target audience category but also parental guidance recommendation) for which a media resource is intended.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Track`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Track`),
      namedNode(`${rdfs}comment`),
      literal(`A specialisation of MediaFragment for audiovisual content.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}Track`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ma}MediaFragment`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}VideoTrack`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}VideoTrack`),
      namedNode(`${rdfs}comment`),
      literal(`A specialisation of Track for Video to provide a link to specific data properties such as frameRate, etc. Signing is another possible example of video track. Specialisation is defined through object properties.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}VideoTrack`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ma}Track`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}alternativeTitle`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}alternativeTitle`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'title.title' in the Ontology for Media Resources with a 'title.type' meaning "alternative".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}alternativeTitle`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}title`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}averageBitRate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}averageBitRate`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'averageBitRate' in the Ontology for Media Resources, expressed in kilobits/second.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}averageBitRate`),
      namedNode(`${rdfs}domain`),
      blankNodes[0],
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}averageBitRate`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}collectionName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}collectionName`),
      namedNode(`${rdfs}comment`),
      literal(`The name by which a collection (e.g. series) is known.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}collectionName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Collection`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}copyright`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}copyright`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'copyright.copyright' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}copyright`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}createdIn`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}createdIn`),
      namedNode(`${rdfs}comment`),
      literal(`A subproperty of 'hasRelatedLocation" used to specify where material shooting took place.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}createdIn`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasRelatedLocation`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}createdIn`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isCreationLocationOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}creationDate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}creationDate`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'date.date' in the Ontology for Media Resources with a 'date.type' meaning "creationDate".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}creationDate`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}date`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}date`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}date`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to date.date in the ontology for Media Resources. Subproperties can be used to distinguish different values of 'date.type'. The recommended range is 'xsd:dateTime' (for compliance with OWL2-QL and OWL2-RL) but other time-related datatypes may be used (e.g. 'xsd:gYear', 'xsd:date'...).`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}date`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}depictsFictionalLocation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}depictsFictionalLocation`),
      namedNode(`${rdfs}comment`),
      literal(`A subproperty of 'hasRelatedLocation' used to specify where the action depicted in the media is supposed to take place, as opposed to the location where shooting actually took place (see 'createdIn').`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}depictsFictionalLocation`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasRelatedLocation`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}depictsFictionalLocation`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isFictionalLocationDepictedIn`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}description`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}description`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'description' in the Ontology for Media Resources. This can be specialised by using sub-properties e.g. 'summary' or 'script'.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}description`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}duration`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}duration`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'duration' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}duration`),
      namedNode(`${rdfs}domain`),
      blankNodes[1],
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}duration`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}editDate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}editDate`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'date.date' in the Ontology for Media Resources with a 'date.type' meaning "editDate".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}editDate`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}date`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}features`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}features`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'contributor.contributor' in the Ontology for Media Resources with a 'contributor.role' meaning "actor".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}features`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}Person`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}features`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasContributor`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}features`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}playsIn`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}fragmentName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}fragmentName`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'namedFragment.label' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}fragmentName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaFragment`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameHeight`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameHeight`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'frameSize.height' in the Ontology for Media Resources, measured in frameSizeUnit.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameHeight`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameHeight`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameRate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameRate`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'frameRate' in the Ontology for Media Resources, in frame per second.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameRate`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameRate`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameSizeUnit`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameSizeUnit`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'frameSize.unit' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameSizeUnit`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameWidth`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameWidth`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'frameSize.width' in the Ontology for Media Resources measured in frameSizeUnit.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameWidth`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}frameWidth`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasAccessConditions`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasAccessConditions`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'policy' in the Ontology for Media Resources with a 'policy.type' "access conditions".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasAccessConditions`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasPolicy`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasAudioDescription`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasAudioDescription`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'fragment' in the Ontology for Media Resources with a 'fragment.role' meaning "audio-description".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasAudioDescription`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasCaptioning`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCaptioning`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCaptioning`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'fragment' in the Ontology for Media Resources with a 'fragment.role' meaning "captioning". This property can for example point to a spatial fragment, a VideoTrack or a DataTrack. The language of the captioning track can be expressed by attaching a 'hasLanguage' property to the specific track.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCaptioning`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasFragment`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCaptioning`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isCaptioningOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasChapter`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasChapter`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'fragment' in the Ontology for Media Resources with a 'fragment.role' meaning "chapter".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasChapter`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasFragment`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasChapter`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isChapterOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasClassification`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasClassification`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'targetAudience.classification' in the Ontology for Media Resources. This property is used to provide a value characterising the target audience.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasClassification`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}TargetAudience`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasClassificationSystem`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasClassificationSystem`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'targetAudience.identifier' in the Ontology for Media Resources. This is used to identify the reference sheme against which the target audience has been characterised.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasClassificationSystem`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}TargetAudience`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCompression`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCompression`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'compression' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCompression`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasContributedTo`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasContributor`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasContributor`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'contributor.contributor' in the Ontology for Media Resources. Subproperties can be used to distinguish different values of 'contributor.role'.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasContributor`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasContributor`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}Agent`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasContributor`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}hasContributedTo`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCopyrightOver`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCreated`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCreator`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCreator`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'creator.creator' in the Ontology for Media Resources. Subproperties can be used to distinguish different values of 'creator.role'. Note that this property is semantically a subproperty of 'hasContributor'.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCreator`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasContributor`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasCreator`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}hasCreated`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasFormat`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasFormat`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'format' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasFormat`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasFragment`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasFragment`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'fragment' in the Ontology for Media Resources. Subproperties can be used to distinguish different values of 'fragment.role'.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasFragment`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasFragment`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}MediaFragment`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasFragment`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isFragmentOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasGenre`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasGenre`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'genre' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasGenre`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasKeyword`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasKeyword`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'keyword' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasKeyword`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasLanguage`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasLanguage`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'language' in the Ontology for Media Resources. The language used in the resource. A controlled vocabulary such as defined in BCP 47 SHOULD be used. This property can also be used to identify the presence of sign language (RFC 5646). By inheritance, the hasLanguage property applies indifferently at the media resource / fragment / track levels.  Best practice recommends to use to best possible level of granularity fo describe the usage of language within a media resource including at fragment and track levels.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasLanguage`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasLocationCoordinateSystem`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasLocationCoordinateSystem`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'location.coordinateSystem' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasLocationCoordinateSystem`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Location`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasMember`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasNamedFragment`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasNamedFragment`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'namedFragment' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasNamedFragment`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasFragment`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasNamedFragment`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isNamedFragmentOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPermissions`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPermissions`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'policy' in the Ontology for Media Resources with a  'policy.type' meaning "permissions".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPermissions`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasPolicy`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPolicy`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPolicy`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'policy' in the Ontology for Media Resources. Subproperties can be used to distinguish different values of 'policy.type'.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPolicy`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPublished`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPublisher`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPublisher`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'publisher' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPublisher`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasContributor`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasPublisher`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}hasPublished`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRating`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRating`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'rating' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRating`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRating`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRating`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isRatingOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRatingSystem`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRatingSystem`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'rating.type' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRatingSystem`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedImage`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedImage`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'relation' and in the Ontology for Media Resources with a 'relation.type' meaning "related image".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedImage`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}Image`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedImage`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasRelatedResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedImage`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isImageRelatedTo`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedLocation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedLocation`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'location' in the Ontology for Media Resources. Subproperties are provided to specify, when possible, the relation between the media resource and the location.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedLocation`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedLocation`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}Location`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedLocation`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isLocationRelatedTo`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedResource`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedResource`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'relation' and in the Ontology for Media Resources. Subproperties can be used to distinguish different values of 'relation.type'.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedResource`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasRelatedResource`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isRelatedTo`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSigning`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSigning`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'fragment' in the Ontology for Media Resources with a 'fragment.role' meaning "signing". This property can for example point to a spatial fragment or a VideoTrack. The sign language of the captioning track can be expressed by attaching a 'hasLanguage' property to the specific track.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSigning`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasFragment`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSigning`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isSigningOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSource`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSource`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'relation' and in the Ontology for Media Resources with a 'relation.type' meaning "source".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSource`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasRelatedResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSource`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isSourceOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSubtitling`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSubtitling`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'fragment' in the Ontology for Media Resources with a 'fragment.role' meaning "subtitling".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasSubtitling`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasCaptioning`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTargetAudience`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTargetAudience`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'targetAudience' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTargetAudience`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTargetAudience`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}TargetAudience`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTargetAudience`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isTargetAudienceOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTrack`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTrack`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'fragment' in the Ontology for Media Resources with a 'fragment.role' meaning "track".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTrack`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}Track`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTrack`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}hasFragment`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}hasTrack`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}isTrackOf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isCaptioningOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isChapterOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isCopyrightedBy`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isCopyrightedBy`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'copyright.identifier' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isCopyrightedBy`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isCopyrightedBy`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}Agent`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isCopyrightedBy`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}hasCopyrightOver`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isCreationLocationOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isFictionalLocationDepictedIn`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isFragmentOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isImageRelatedTo`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isImageRelatedTo`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}isRelatedTo`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isLocationRelatedTo`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isMemberOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isMemberOf`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'collection' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isMemberOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isMemberOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}Collection`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isMemberOf`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}hasMember`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isNamedFragmentOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isProvidedBy`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isProvidedBy`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'rating.identifier' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isProvidedBy`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isProvidedBy`),
      namedNode(`${rdfs}range`),
      namedNode(`${ma}Agent`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isProvidedBy`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ma}provides`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isRatingOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isRelatedTo`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isSigningOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isSourceOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isTargetAudienceOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}isTrackOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationAltitude`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationAltitude`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'location.altitude' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationAltitude`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Location`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationAltitude`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationLatitude`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationLatitude`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'location.latitude' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationLatitude`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Location`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationLatitude`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationLongitude`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationLongitude`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'location.longitude' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationLongitude`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Location`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationLongitude`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationName`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'location.name' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locationName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Location`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locator`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locator`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'locator' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locator`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}locator`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}mainOriginalTitle`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}mainOriginalTitle`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'title.title' in the Ontology for Media Resources with a 'title.type' meaning "original".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}mainOriginalTitle`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}title`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}numberOfTracks`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}numberOfTracks`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'numTracks.number' in the Ontology for Media Resources. Subproperties can be used to distinguish different values of 'numTracks.type'.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}numberOfTracks`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}numberOfTracks`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}playsIn`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}provides`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingScaleMax`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingScaleMax`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'rating.max' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingScaleMax`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingScaleMax`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingScaleMin`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingScaleMin`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'rating.min' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingScaleMin`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingScaleMin`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingValue`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingValue`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'rating.value' in the Ontology for Media Resources.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingValue`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Rating`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}ratingValue`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}recordDate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}recordDate`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'date.date' in the Ontology for Media Resources with a 'date.type' meaning "recordDate".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}recordDate`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}date`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}releaseDate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}releaseDate`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'date.date' in the Ontology for Media Resources with a 'date.type' meaning "releaseDate".`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}releaseDate`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}date`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}samplingRate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}samplingRate`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'samplingRate' in the Ontology for Media Resources, in samples per second.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}samplingRate`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}samplingRate`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}decimal`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}title`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}title`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'title.title' in the Ontology for Media Resources. Subproperties can be used to distinguish different values of 'title.type'.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}title`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}trackName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}trackName`),
      namedNode(`${rdfs}comment`),
      literal(`Corresponds to 'fragment.name' in the Ontology for Media Resources, for Track fragments.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}trackName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${ma}Track`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ma}trackName`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${ma}fragmentName`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ns7}ma-ont`),
      namedNode(`${dc11}date`),
      literal(`2013-03-20`, namedNode(`${xsd}date`)),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ns7}ma-ont`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ns7}ma-ont`),
      namedNode(`${rdfs}comment`),
      literal(`Created by Tobias Buerger, Jean Pierre Evain and Pierre-Antoine Champin with the RDFS Taskforce within the W3C Media Annotation Working Group.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ns7}ma-ont`),
      namedNode(`${rdfs}comment`),
      literal(`THE CONTENT OF THIS MA-ONT.RDF AND DERIVED MA-ONT.TTL FILES PREVAIL OVER THE SPECIFICATION.`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ns7}ma-ont`),
      namedNode(`${owl}imports`),
      namedNode(`${ns8}dcelements.rdf`),
      namedNode(ma)
    ),
    quad(
      namedNode(`${ns7}ma-ont`),
      namedNode(`${owl}versionInfo`),
      literal(`R36`),
      namedNode(ma)
    ),
    quad(
      blankNodes[1],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      blankNodes[1],
      namedNode(`${owl}intersectionOf`),
      blankNodes[2],
      namedNode(ma)
    ),
    quad(
      blankNodes[0],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      blankNodes[0],
      namedNode(`${owl}intersectionOf`),
      blankNodes[3],
      namedNode(ma)
    ),
    quad(
      blankNodes[4],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      blankNodes[4],
      namedNode(`${owl}complementOf`),
      namedNode(`${ma}Image`),
      namedNode(ma)
    ),
    quad(
      blankNodes[5],
      namedNode(`${rdf}first`),
      blankNodes[4],
      namedNode(ma)
    ),
    quad(
      blankNodes[5],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(ma)
    ),
    quad(
      blankNodes[3],
      namedNode(`${rdf}first`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      blankNodes[3],
      namedNode(`${rdf}rest`),
      blankNodes[5],
      namedNode(ma)
    ),
    quad(
      blankNodes[6],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(ma)
    ),
    quad(
      blankNodes[6],
      namedNode(`${owl}complementOf`),
      namedNode(`${ma}Image`),
      namedNode(ma)
    ),
    quad(
      blankNodes[7],
      namedNode(`${rdf}first`),
      blankNodes[6],
      namedNode(ma)
    ),
    quad(
      blankNodes[7],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(ma)
    ),
    quad(
      blankNodes[2],
      namedNode(`${rdf}first`),
      namedNode(`${ma}MediaResource`),
      namedNode(ma)
    ),
    quad(
      blankNodes[2],
      namedNode(`${rdf}rest`),
      blankNodes[7],
      namedNode(ma)
    ),

  ]
}
