/* This file was automatically generated. Do not edit by hand. */

const {
  ns1,
  vaem,
  prefix,
  rdf,
  owl,
  ns6,
  dcterms,
  qudt,
  xsd,
  rdfs
} = {
  'ns1': 'http://qudt.org/2.1/vocab/',
  'vaem': 'http://www.linkedmodel.org/schema/vaem#',
  'prefix': 'http://qudt.org/vocab/prefix/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'ns6': 'http://qudt.org/2.1/schema/facade/',
  'dcterms': 'http://purl.org/dc/terms/',
  'qudt': 'http://qudt.org/schema/qudt/',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(`${ns1}prefix`),
      namedNode(`${vaem}hasGraphMetadata`),
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${ns1}prefix`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${ns1}prefix`),
      namedNode(`${owl}imports`),
      namedNode(`${ns6}qudt`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${ns1}prefix`),
      namedNode(`${owl}versionIRI`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${ns1}prefix`),
      namedNode(`${owl}versionInfo`),
      literal(`Created with TopBraid Composer`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${dcterms}description`),
      literal(`"atto" is a decimal prefix for expressing a value with a scaling of \\(10^{-18}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Atto`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Atto?oldid=412748080`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-18`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${qudt}symbol`),
      literal(`a`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${qudt}ucumCode`),
      literal(`a`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Atto`),
      namedNode(`${rdfs}label`),
      literal(`Atto`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${dcterms}description`),
      literal(`'centi' is a decimal prefix for expressing a value with a scaling of \\(10^{-2}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Centi-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Centi-?oldid=480291808`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-2`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${qudt}symbol`),
      literal(`c`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${qudt}ucumCode`),
      literal(`c`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Centi`),
      namedNode(`${rdfs}label`),
      literal(`Centi`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deca`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Deca`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deca`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E1`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deca`),
      namedNode(`${qudt}symbol`),
      literal(`da`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deca`),
      namedNode(`${qudt}ucumCode`),
      literal(`da`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deca`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deca`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deca`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deca`),
      namedNode(`${rdfs}label`),
      literal(`Deca`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${dcterms}description`),
      literal(`"deci" is a decimal prefix for expressing a value with a scaling of \\(10^{-1}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Deci-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Deci-?oldid=469980160`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-1`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${qudt}symbol`),
      literal(`d`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${qudt}ucumCode`),
      literal(`d`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deci`),
      namedNode(`${rdfs}label`),
      literal(`Deci`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${dcterms}description`),
      literal(`<strong>deka</strong> is a decimal prefix for expressing a value with a scaling of \\(10^{1}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Deca`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Deca?oldid=480093935`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`10.0`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${qudt}symbol`),
      literal(`da`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${qudt}ucumCode`),
      literal(`da`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Deka`),
      namedNode(`${rdfs}label`),
      literal(`Deka`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${dcterms}description`),
      literal(`'exa' is a decimal prefix for expressing a value with a scaling of \\(10^{18}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Exa-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Exa-?oldid=494400216`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E18`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${qudt}symbol`),
      literal(`E`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${qudt}ucumCode`),
      literal(`E`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exa`),
      namedNode(`${rdfs}label`),
      literal(`Exa`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exbi`),
      namedNode(`${dcterms}description`),
      literal(`A binary prefix for expressing a value with a scaling of \\(1024^{6}\\), or \\(2^{60}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exbi`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`152921504606846976.0`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exbi`),
      namedNode(`${qudt}symbol`),
      literal(`Ei`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exbi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}BinaryPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exbi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exbi`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Exbi`),
      namedNode(`${rdfs}label`),
      literal(`Exbi`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${dcterms}description`),
      literal(`'femto' is a decimal prefix for expressing a value with a scaling of \\(10^{-15}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Femto-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Femto-?oldid=467211359`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-15`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${qudt}symbol`),
      literal(`f`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${qudt}ucumCode`),
      literal(`f`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Femto`),
      namedNode(`${rdfs}label`),
      literal(`Femto`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Gibi`),
      namedNode(`${dcterms}description`),
      literal(`A binary prefix for expressing a value with a scaling of \\(1024^{3}\\), or \\(2^{30}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Gibi`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1073741824`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Gibi`),
      namedNode(`${qudt}symbol`),
      literal(`Gi`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Gibi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}BinaryPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Gibi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Gibi`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Gibi`),
      namedNode(`${rdfs}label`),
      literal(`Gibi`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${dcterms}description`),
      literal(`'giga' is a decimal prefix for expressing a value with a scaling of \\(10^{9}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Giga-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Giga-?oldid=473222816`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E9`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${qudt}symbol`),
      literal(`G`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${qudt}ucumCode`),
      literal(`G`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Giga`),
      namedNode(`${rdfs}label`),
      literal(`Giga`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${dcterms}description`),
      literal(`'hecta' is a decimal prefix for expressing a value with a scaling of \\(10^{2}"\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Hecto-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Hecto-?oldid=494711166`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E2`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${qudt}symbol`),
      literal(`h`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${qudt}ucumCode`),
      literal(`h`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Hecto`),
      namedNode(`${rdfs}label`),
      literal(`Hecto`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kibi`),
      namedNode(`${dcterms}description`),
      literal(`A binary prefix for expressing a value with a scaling of \\(1024\\), or \\(2^{10}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kibi`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1024`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kibi`),
      namedNode(`${qudt}symbol`),
      literal(`Ki`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kibi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}BinaryPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kibi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kibi`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kibi`),
      namedNode(`${rdfs}label`),
      literal(`Kibi`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${dcterms}description`),
      literal(`"kilo" is a decimal prefix for expressing a value with a scaling of \\(10^{3}"\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Kilo`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Kilo?oldid=461428121`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E3`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${qudt}symbol`),
      literal(`k`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${qudt}ucumCode`),
      literal(`k`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Kilo`),
      namedNode(`${rdfs}label`),
      literal(`Kilo`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mebi`),
      namedNode(`${dcterms}description`),
      literal(`A binary prefix for expressing a value with a scaling of \\(1024^{2}\\), or \\(2^{20}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mebi`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1048576`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mebi`),
      namedNode(`${qudt}symbol`),
      literal(`Mi`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mebi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}BinaryPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mebi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mebi`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mebi`),
      namedNode(`${rdfs}label`),
      literal(`Mebi`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${dcterms}description`),
      literal(`'mega' is a decimal prefix for expressing a value with a scaling of \\(10^{6}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Mega`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Mega?oldid=494040441`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E6`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${qudt}symbol`),
      literal(`M`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${qudt}ucumCode`),
      literal(`M`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Mega`),
      namedNode(`${rdfs}label`),
      literal(`Mega`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${dcterms}description`),
      literal(`"micro" is a decimal prefix for expressing a value with a scaling of \\(10^{-6}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Micro`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Micro?oldid=491618374`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-6`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${qudt}symbol`),
      literal(`μ`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${qudt}ucumCode`),
      literal(`u`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Micro`),
      namedNode(`${rdfs}label`),
      literal(`Micro`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${dcterms}description`),
      literal(`'milli' is a decimal prefix for expressing a value with a scaling of \\(10^{-3}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Milli-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Milli-?oldid=467190544`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-3`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${qudt}symbol`),
      literal(`m`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${qudt}ucumCode`),
      literal(`m`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Milli`),
      namedNode(`${rdfs}label`),
      literal(`Milli`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${dcterms}description`),
      literal(`'nano' is a  decimal prefix for expressing a value with a scaling of \\(10^{-9}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Nano`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Nano?oldid=489001692`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-9`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${qudt}symbol`),
      literal(`n`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${qudt}ucumCode`),
      literal(`n`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Nano`),
      namedNode(`${rdfs}label`),
      literal(`Nano`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pebi`),
      namedNode(`${dcterms}description`),
      literal(`A binary prefix for expressing a value with a scaling of \\(1024^{5}\\), or \\(2^{50}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pebi`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`125899906842624`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pebi`),
      namedNode(`${qudt}symbol`),
      literal(`Pi`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pebi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}BinaryPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pebi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pebi`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pebi`),
      namedNode(`${rdfs}label`),
      literal(`Pebi`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${dcterms}description`),
      literal(`'peta' is a decimal prefix for expressing a value with a scaling of \\(10^{15}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Peta`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Peta?oldid=488263435`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E15`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${qudt}symbol`),
      literal(`P`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${qudt}ucumCode`),
      literal(`P`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Peta`),
      namedNode(`${rdfs}label`),
      literal(`Peta`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${dcterms}description`),
      literal(`'pico' is a decimal prefix for expressing a value with a scaling of \\(10^{-12}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Pico`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Pico?oldid=485697614`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-12`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${qudt}symbol`),
      literal(`p`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${qudt}ucumCode`),
      literal(`p`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Pico`),
      namedNode(`${rdfs}label`),
      literal(`Pico`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tebi`),
      namedNode(`${dcterms}description`),
      literal(`A binary prefix for expressing a value with a scaling of \\(1024^4}\\), or \\(2^{40}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tebi`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1099511627776`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tebi`),
      namedNode(`${qudt}symbol`),
      literal(`Ti`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tebi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}BinaryPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tebi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tebi`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tebi`),
      namedNode(`${rdfs}label`),
      literal(`Tebi`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${dcterms}description`),
      literal(`'tera' is a decimal prefix for expressing a value with a scaling of \\(10^{12}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Tera`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Tera?oldid=494204788`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E12`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${qudt}symbol`),
      literal(`T`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${qudt}ucumCode`),
      literal(`T`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Tera`),
      namedNode(`${rdfs}label`),
      literal(`Tera`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yobi`),
      namedNode(`${dcterms}description`),
      literal(`A binary prefix for expressing a value with a scaling of \\(1024^{8}\\), or \\(2^{80}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yobi`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1208925819614629174706176`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yobi`),
      namedNode(`${qudt}symbol`),
      literal(`Yi`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yobi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}BinaryPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yobi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yobi`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yobi`),
      namedNode(`${rdfs}label`),
      literal(`Yobi`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${dcterms}description`),
      literal(`'yocto' is a decimal prefix for expressing a value with a scaling of \\(10^{-24}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Yocto-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Yocto-?oldid=488155799`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-24`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${qudt}symbol`),
      literal(`y`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${qudt}ucumCode`),
      literal(`y`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yocto`),
      namedNode(`${rdfs}label`),
      literal(`Yocto`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${dcterms}description`),
      literal(`'yotta' is a decimal prefix for expressing a value with a scaling of \\(10^{24}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Yotta-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Yotta-?oldid=494538119`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E24`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${qudt}symbol`),
      literal(`Y`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${qudt}ucumCode`),
      literal(`Y`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Yotta`),
      namedNode(`${rdfs}label`),
      literal(`Yotta`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zebi`),
      namedNode(`${dcterms}description`),
      literal(`A binary prefix for expressing a value with a scaling of \\(1024^{7}\\), or \\(2^{70}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zebi`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1180591620717411303424`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zebi`),
      namedNode(`${qudt}symbol`),
      literal(`Zi`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zebi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}BinaryPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zebi`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zebi`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zebi`),
      namedNode(`${rdfs}label`),
      literal(`Zebi`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${dcterms}description`),
      literal(`'zepto' is a decimal prefix for expressing a value with a scaling of \\(10^{-21}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Zepto-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Zepto-?oldid=476974663`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E-21`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${qudt}symbol`),
      literal(`z`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${qudt}ucumCode`),
      literal(`z`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zepto`),
      namedNode(`${rdfs}label`),
      literal(`Zepto`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${dcterms}description`),
      literal(`'zetta' is a decimal prefix for expressing a value with a scaling of \\(10^{21}\\).`, namedNode(`${qudt}LatexString`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Zetta-`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Zetta-?oldid=495223080`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${qudt}prefixMultiplier`),
      literal(`1.0E21`, namedNode(`${xsd}double`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${qudt}symbol`),
      literal(`Z`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${qudt}ucumCode`),
      literal(`Z`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}DecimalPrefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}Prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${prefix}Zetta`),
      namedNode(`${rdfs}label`),
      literal(`Zetta`, 'en'),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${dcterms}contributor`),
      literal(`Jack Hodges`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${dcterms}contributor`),
      literal(`Ralph Hodgson`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${dcterms}contributor`),
      literal(`Steve Ray`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${dcterms}created`),
      literal(`2020-07-15`, namedNode(`${xsd}date`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${dcterms}creator`),
      literal(`Steve Ray`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${dcterms}modified`),
      literal(`2023-03-02T12:20:27.469-05:00`, namedNode(`${xsd}dateTime`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${dcterms}rights`),
      literal(`The QUDT Ontologies are issued under a Creative Commons Attribution 4.0 International License (CC BY 4.0), available at https://creativecommons.org/licenses/by/4.0/. Attribution should be made to QUDT.org`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${dcterms}subject`),
      literal(`Prefixes`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${dcterms}title`),
      literal(`Prefixes Version 2.1 Vocabulary`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}description`),
      literal(`The Prefixes vocabulary defines the prefixes commonly prepended to units to connote multiplication, either decimal or binary.`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}graphName`),
      literal(`prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}graphTitle`),
      literal(`Prefixes Vocabulary Version 2.1.25`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}hasGraphRole`),
      namedNode(`${vaem}VocabularyGraph`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}hasOwner`),
      namedNode(`${vaem}QUDT.org`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}hasSteward`),
      namedNode(`${vaem}QUDT.org`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}intent`),
      literal(`Provides a vocabulary of prefixes for both human and machine use`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}isMetadataFor`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}latestPublishedVersion`),
      literal(`https://qudt.org/doc/2023/03/DOC_VOCAB-PREFIXES-v2.1.html`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}logo`),
      literal(`https://qudt.org/linkedmodels.org/assets/lib/lm/images/logos/qudt_logo-300x110.png`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}namespace`),
      literal(`http://qudt.org/2.1/vocab/prefix/`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}namespacePrefix`),
      literal(`prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}owner`),
      literal(`QUDT.org`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}previousPublishedVersion`),
      literal(`https://qudt.org/doc/2023/01/DOC_VOCAB-PREFIXES-v2.1.html`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}revision`),
      literal(`2.1`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}specificity`),
      literal(`1`, namedNode(`${xsd}integer`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}turtleFileURL`),
      literal(`http://qudt.org/2.1/vocab/prefix`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}urlForHTML`),
      literal(`http://qudt.org/2.1/vocab/prefix.html`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}abstract`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}created`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}creator`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}modified`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}title`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${vaem}website`),
      literal(`http://qudt.org/2.1/vocab/prefix.ttl`, namedNode(`${xsd}anyURI`)),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphMetaData`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}prefix`),
      namedNode(prefix)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-PREFIXES`),
      namedNode(`${rdfs}label`),
      literal(`Prefixes Vocabulary Version 2.1 Metadata`),
      namedNode(prefix)
    ),

  ]
}
