/* This file was automatically generated. Do not edit by hand. */

const {
  rss,
  rdf,
  rdfs,
  dc11
} = {
  'rss': 'http://purl.org/rss/1.0/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'dc11': 'http://purl.org/dc/elements/1.1/'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(`${rss}channel`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}channel`),
      namedNode(`${rdfs}comment`),
      literal(`An RSS information channel.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}channel`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}channel`),
      namedNode(`${rdfs}label`),
      literal(`Channel`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}description`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}description`),
      namedNode(`${rdfs}comment`),
      literal(`A short text description of the subject.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}description`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}description`),
      namedNode(`${rdfs}label`),
      literal(`Description`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}description`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${dc11}description`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}image`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}image`),
      namedNode(`${rdfs}comment`),
      literal(`An RSS image.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}image`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}image`),
      namedNode(`${rdfs}label`),
      literal(`Image`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}item`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}item`),
      namedNode(`${rdfs}comment`),
      literal(`An RSS item.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}item`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}item`),
      namedNode(`${rdfs}label`),
      literal(`Item`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}items`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}items`),
      namedNode(`${rdfs}comment`),
      literal(`Points to a list of rss:item elements that are members of the subject channel.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}items`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}items`),
      namedNode(`${rdfs}label`),
      literal(`Items`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}link`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}link`),
      namedNode(`${rdfs}comment`),
      literal(`The URL to which an HTML rendering of the subject will link.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}link`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}link`),
      namedNode(`${rdfs}label`),
      literal(`Link`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}link`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${dc11}identifier`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}name`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}name`),
      namedNode(`${rdfs}comment`),
      literal(`The text input field's (variable) name.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}name`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}name`),
      namedNode(`${rdfs}label`),
      literal(`Name`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}textinput`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}textinput`),
      namedNode(`${rdfs}comment`),
      literal(`An RSS text input.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}textinput`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}textinput`),
      namedNode(`${rdfs}label`),
      literal(`Text Input`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}title`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}title`),
      namedNode(`${rdfs}comment`),
      literal(`A descriptive title for the channel.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}title`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}title`),
      namedNode(`${rdfs}label`),
      literal(`Title`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}title`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${dc11}title`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}url`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}url`),
      namedNode(`${rdfs}comment`),
      literal(`The URL of the image to used in the 'src' attribute of the channel's image tag when rendered as HTML.`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}url`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rss),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}url`),
      namedNode(`${rdfs}label`),
      literal(`URL`),
      namedNode(rss)
    ),
    quad(
      namedNode(`${rss}url`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${dc11}identifier`),
      namedNode(rss)
    ),

  ]
}
