/* This file was automatically generated. Do not edit by hand. */

const {
  owl,
  rdf,
  rdfs,
  xsd,
  ns5,
  dc11,
  ns7,
  ns8,
  ns9,
  ns10,
  ns11,
  grddl,
  ns13
} = {
  'owl': 'http://www.w3.org/2002/07/owl#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'ns5': 'http://www.w3.org/2002/07/',
  'dc11': 'http://purl.org/dc/elements/1.1/',
  'ns7': 'http://www.w3.org/TR/owl2-mapping-to-rdf/',
  'ns8': 'http://www.w3.org/TR/owl2-rdf-based-semantics/',
  'ns9': 'http://www.w3.org/TR/owl2-syntax/',
  'ns10': 'http://www.w3.org/TR/owl2-rdf-based-semantics/#',
  'ns11': 'http://www.w3.org/2000/01/',
  'grddl': 'http://www.w3.org/2003/g/data-view#',
  'ns13': 'http://dev.w3.org/cvsweb/2009/owl-grddl/'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(`${owl}AllDifferent`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDifferent`),
      namedNode(`${rdfs}comment`),
      literal(`The class of collections of pairwise different individuals.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDifferent`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDifferent`),
      namedNode(`${rdfs}label`),
      literal(`AllDifferent`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDifferent`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointClasses`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointClasses`),
      namedNode(`${rdfs}comment`),
      literal(`The class of collections of pairwise disjoint classes.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointClasses`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointClasses`),
      namedNode(`${rdfs}label`),
      literal(`AllDisjointClasses`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointClasses`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointProperties`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointProperties`),
      namedNode(`${rdfs}comment`),
      literal(`The class of collections of pairwise disjoint properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointProperties`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointProperties`),
      namedNode(`${rdfs}label`),
      literal(`AllDisjointProperties`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AllDisjointProperties`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Annotation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Annotation`),
      namedNode(`${rdfs}comment`),
      literal(`The class of annotated annotations for which the RDF serialization consists of an annotated subject, predicate and object.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Annotation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Annotation`),
      namedNode(`${rdfs}label`),
      literal(`Annotation`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Annotation`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AnnotationProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AnnotationProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of annotation properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AnnotationProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AnnotationProperty`),
      namedNode(`${rdfs}label`),
      literal(`AnnotationProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AnnotationProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AsymmetricProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AsymmetricProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of asymmetric properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AsymmetricProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AsymmetricProperty`),
      namedNode(`${rdfs}label`),
      literal(`AsymmetricProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}AsymmetricProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Axiom`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Axiom`),
      namedNode(`${rdfs}comment`),
      literal(`The class of annotated axioms for which the RDF serialization consists of an annotated subject, predicate and object.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Axiom`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Axiom`),
      namedNode(`${rdfs}label`),
      literal(`Axiom`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Axiom`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Class`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Class`),
      namedNode(`${rdfs}comment`),
      literal(`The class of OWL classes.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Class`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Class`),
      namedNode(`${rdfs}label`),
      literal(`Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Class`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DataRange`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DataRange`),
      namedNode(`${rdfs}comment`),
      literal(`The class of OWL data ranges, which are special kinds of datatypes. Note: The use of the IRI owl:DataRange has been deprecated as of OWL 2. The IRI rdfs:Datatype SHOULD be used instead.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DataRange`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DataRange`),
      namedNode(`${rdfs}label`),
      literal(`DataRange`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DataRange`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Datatype`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DatatypeProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DatatypeProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of data properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DatatypeProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DatatypeProperty`),
      namedNode(`${rdfs}label`),
      literal(`DatatypeProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DatatypeProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedClass`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedClass`),
      namedNode(`${rdfs}comment`),
      literal(`The class of deprecated classes.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedClass`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedClass`),
      namedNode(`${rdfs}label`),
      literal(`DeprecatedClass`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedClass`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of deprecated properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedProperty`),
      namedNode(`${rdfs}label`),
      literal(`DeprecatedProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}DeprecatedProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}FunctionalProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}FunctionalProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of functional properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}FunctionalProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}FunctionalProperty`),
      namedNode(`${rdfs}label`),
      literal(`FunctionalProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}FunctionalProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of inverse-functional properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(`${rdfs}label`),
      literal(`InverseFunctionalProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}IrreflexiveProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}IrreflexiveProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of irreflexive properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}IrreflexiveProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}IrreflexiveProperty`),
      namedNode(`${rdfs}label`),
      literal(`IrreflexiveProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}IrreflexiveProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NamedIndividual`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NamedIndividual`),
      namedNode(`${rdfs}comment`),
      literal(`The class of named individuals.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NamedIndividual`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NamedIndividual`),
      namedNode(`${rdfs}label`),
      literal(`NamedIndividual`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NamedIndividual`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NegativePropertyAssertion`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NegativePropertyAssertion`),
      namedNode(`${rdfs}comment`),
      literal(`The class of negative property assertions.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NegativePropertyAssertion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NegativePropertyAssertion`),
      namedNode(`${rdfs}label`),
      literal(`NegativePropertyAssertion`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}NegativePropertyAssertion`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Nothing`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Nothing`),
      namedNode(`${rdfs}comment`),
      literal(`This is the empty class.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Nothing`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Nothing`),
      namedNode(`${rdfs}label`),
      literal(`Nothing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Nothing`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ObjectProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ObjectProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of object properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ObjectProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ObjectProperty`),
      namedNode(`${rdfs}label`),
      literal(`ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ObjectProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Ontology`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Ontology`),
      namedNode(`${rdfs}comment`),
      literal(`The class of ontologies.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Ontology`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Ontology`),
      namedNode(`${rdfs}label`),
      literal(`Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Ontology`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}OntologyProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}OntologyProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of ontology properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}OntologyProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}OntologyProperty`),
      namedNode(`${rdfs}label`),
      literal(`OntologyProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}OntologyProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ReflexiveProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ReflexiveProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of reflexive properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ReflexiveProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ReflexiveProperty`),
      namedNode(`${rdfs}label`),
      literal(`ReflexiveProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}ReflexiveProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Restriction`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Restriction`),
      namedNode(`${rdfs}comment`),
      literal(`The class of property restrictions.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Restriction`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Restriction`),
      namedNode(`${rdfs}label`),
      literal(`Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Restriction`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}SymmetricProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}SymmetricProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of symmetric properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}SymmetricProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}SymmetricProperty`),
      namedNode(`${rdfs}label`),
      literal(`SymmetricProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}SymmetricProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Thing`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Thing`),
      namedNode(`${rdfs}comment`),
      literal(`The class of OWL individuals.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Thing`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}Thing`),
      namedNode(`${rdfs}label`),
      literal(`Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}TransitiveProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}TransitiveProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of transitive properties.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}TransitiveProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}TransitiveProperty`),
      namedNode(`${rdfs}label`),
      literal(`TransitiveProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}TransitiveProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the class that a universal property restriction refers to.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${rdfs}label`),
      literal(`allValuesFrom`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the predicate of an annotated axiom or annotated annotation.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedProperty`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedProperty`),
      namedNode(`${rdfs}label`),
      literal(`annotatedProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedProperty`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedSource`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedSource`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the subject of an annotated axiom or annotated annotation.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedSource`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedSource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedSource`),
      namedNode(`${rdfs}label`),
      literal(`annotatedSource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedSource`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedTarget`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedTarget`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the object of an annotated axiom or annotated annotation.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedTarget`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedTarget`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedTarget`),
      namedNode(`${rdfs}label`),
      literal(`annotatedTarget`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}annotatedTarget`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}assertionProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}assertionProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the predicate of a negative property assertion.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}assertionProperty`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}NegativePropertyAssertion`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}assertionProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}assertionProperty`),
      namedNode(`${rdfs}label`),
      literal(`assertionProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}assertionProperty`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}backwardCompatibleWith`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}backwardCompatibleWith`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}OntologyProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}backwardCompatibleWith`),
      namedNode(`${rdfs}comment`),
      literal(`The annotation property that indicates that a given ontology is backward compatible with another ontology.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}backwardCompatibleWith`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}backwardCompatibleWith`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}backwardCompatibleWith`),
      namedNode(`${rdfs}label`),
      literal(`backwardCompatibleWith`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}backwardCompatibleWith`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomDataProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomDataProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The data property that does not relate any individual to any data value.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomDataProperty`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomDataProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomDataProperty`),
      namedNode(`${rdfs}label`),
      literal(`bottomDataProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomDataProperty`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomObjectProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomObjectProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The object property that does not relate any two individuals.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomObjectProperty`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomObjectProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomObjectProperty`),
      namedNode(`${rdfs}label`),
      literal(`bottomObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}bottomObjectProperty`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}cardinality`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}cardinality`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the cardinality of an exact cardinality restriction.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}cardinality`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}cardinality`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}cardinality`),
      namedNode(`${rdfs}label`),
      literal(`cardinality`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}cardinality`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}complementOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}complementOf`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that a given class is the complement of another class.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}complementOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}complementOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}complementOf`),
      namedNode(`${rdfs}label`),
      literal(`complementOf`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}complementOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}datatypeComplementOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}datatypeComplementOf`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that a given data range is the complement of another data range with respect to the data domain.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}datatypeComplementOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Datatype`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}datatypeComplementOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}datatypeComplementOf`),
      namedNode(`${rdfs}label`),
      literal(`datatypeComplementOf`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}datatypeComplementOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Datatype`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}deprecated`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}deprecated`),
      namedNode(`${rdfs}comment`),
      literal(`The annotation property that indicates that a given entity has been deprecated.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}deprecated`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}deprecated`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}deprecated`),
      namedNode(`${rdfs}label`),
      literal(`deprecated`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}deprecated`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}differentFrom`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}differentFrom`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that two given individuals are different.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}differentFrom`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}differentFrom`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}differentFrom`),
      namedNode(`${rdfs}label`),
      literal(`differentFrom`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}differentFrom`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointUnionOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointUnionOf`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that a given class is equivalent to the disjoint union of a collection of other classes.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointUnionOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointUnionOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointUnionOf`),
      namedNode(`${rdfs}label`),
      literal(`disjointUnionOf`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointUnionOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointWith`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointWith`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that two given classes are disjoint.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointWith`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointWith`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointWith`),
      namedNode(`${rdfs}label`),
      literal(`disjointWith`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}disjointWith`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}distinctMembers`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}distinctMembers`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the collection of pairwise different individuals in a owl:AllDifferent axiom.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}distinctMembers`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}AllDifferent`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}distinctMembers`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}distinctMembers`),
      namedNode(`${rdfs}label`),
      literal(`distinctMembers`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}distinctMembers`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentClass`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentClass`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that two given classes are equivalent, and that is used to specify datatype definitions.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentClass`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentClass`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentClass`),
      namedNode(`${rdfs}label`),
      literal(`equivalentClass`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentClass`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that two given properties are equivalent.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${rdfs}label`),
      literal(`equivalentProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasKey`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasKey`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the collection of properties that jointly build a key.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasKey`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasKey`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasKey`),
      namedNode(`${rdfs}label`),
      literal(`hasKey`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasKey`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasSelf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasSelf`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the property that a self restriction refers to.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasSelf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasSelf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasSelf`),
      namedNode(`${rdfs}label`),
      literal(`hasSelf`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasSelf`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasValue`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasValue`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the individual that a has-value restriction refers to.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasValue`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasValue`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasValue`),
      namedNode(`${rdfs}label`),
      literal(`hasValue`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}hasValue`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}imports`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}OntologyProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}imports`),
      namedNode(`${rdfs}comment`),
      literal(`The property that is used for importing other ontologies into a given ontology.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}imports`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}imports`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}imports`),
      namedNode(`${rdfs}label`),
      literal(`imports`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}imports`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}incompatibleWith`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}incompatibleWith`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}OntologyProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}incompatibleWith`),
      namedNode(`${rdfs}comment`),
      literal(`The annotation property that indicates that a given ontology is incompatible with another ontology.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}incompatibleWith`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}incompatibleWith`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}incompatibleWith`),
      namedNode(`${rdfs}label`),
      literal(`incompatibleWith`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}incompatibleWith`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}intersectionOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}intersectionOf`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the collection of classes or data ranges that build an intersection.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}intersectionOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}intersectionOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}intersectionOf`),
      namedNode(`${rdfs}label`),
      literal(`intersectionOf`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}intersectionOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}inverseOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}inverseOf`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that two given properties are inverse.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}inverseOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}inverseOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}inverseOf`),
      namedNode(`${rdfs}label`),
      literal(`inverseOf`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}inverseOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxCardinality`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxCardinality`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the cardinality of a maximum cardinality restriction.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxCardinality`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxCardinality`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxCardinality`),
      namedNode(`${rdfs}label`),
      literal(`maxCardinality`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxCardinality`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxQualifiedCardinality`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxQualifiedCardinality`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the cardinality of a maximum qualified cardinality restriction.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxQualifiedCardinality`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxQualifiedCardinality`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxQualifiedCardinality`),
      namedNode(`${rdfs}label`),
      literal(`maxQualifiedCardinality`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}maxQualifiedCardinality`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}members`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}members`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the collection of members in either a owl:AllDifferent, owl:AllDisjointClasses or owl:AllDisjointProperties axiom.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}members`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}members`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}members`),
      namedNode(`${rdfs}label`),
      literal(`members`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}members`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minCardinality`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minCardinality`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the cardinality of a minimum cardinality restriction.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minCardinality`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minCardinality`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minCardinality`),
      namedNode(`${rdfs}label`),
      literal(`minCardinality`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minCardinality`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minQualifiedCardinality`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minQualifiedCardinality`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the cardinality of a minimum qualified cardinality restriction.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minQualifiedCardinality`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minQualifiedCardinality`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minQualifiedCardinality`),
      namedNode(`${rdfs}label`),
      literal(`minQualifiedCardinality`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}minQualifiedCardinality`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onClass`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onClass`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the class that a qualified object cardinality restriction refers to.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onClass`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onClass`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onClass`),
      namedNode(`${rdfs}label`),
      literal(`onClass`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onClass`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDataRange`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDataRange`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the data range that a qualified data cardinality restriction refers to.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDataRange`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDataRange`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDataRange`),
      namedNode(`${rdfs}label`),
      literal(`onDataRange`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDataRange`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Datatype`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDatatype`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDatatype`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the datatype that a datatype restriction refers to.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDatatype`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Datatype`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDatatype`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDatatype`),
      namedNode(`${rdfs}label`),
      literal(`onDatatype`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onDatatype`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Datatype`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperties`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperties`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the n-tuple of properties that a property restriction on an n-ary data range refers to.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperties`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperties`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperties`),
      namedNode(`${rdfs}label`),
      literal(`onProperties`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperties`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the property that a property restriction refers to.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperty`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperty`),
      namedNode(`${rdfs}label`),
      literal(`onProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}onProperty`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}oneOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}oneOf`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the collection of individuals or data values that build an enumeration.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}oneOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}oneOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}oneOf`),
      namedNode(`${rdfs}label`),
      literal(`oneOf`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}oneOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}priorVersion`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}priorVersion`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}OntologyProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}priorVersion`),
      namedNode(`${rdfs}comment`),
      literal(`The annotation property that indicates the predecessor ontology of a given ontology.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}priorVersion`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}priorVersion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}priorVersion`),
      namedNode(`${rdfs}label`),
      literal(`priorVersion`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}priorVersion`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyChainAxiom`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyChainAxiom`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the n-tuple of properties that build a sub property chain of a given property.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyChainAxiom`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyChainAxiom`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyChainAxiom`),
      namedNode(`${rdfs}label`),
      literal(`propertyChainAxiom`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyChainAxiom`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyDisjointWith`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyDisjointWith`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that two given properties are disjoint.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyDisjointWith`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyDisjointWith`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyDisjointWith`),
      namedNode(`${rdfs}label`),
      literal(`propertyDisjointWith`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}propertyDisjointWith`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}qualifiedCardinality`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}qualifiedCardinality`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the cardinality of an exact qualified cardinality restriction.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}qualifiedCardinality`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}qualifiedCardinality`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}qualifiedCardinality`),
      namedNode(`${rdfs}label`),
      literal(`qualifiedCardinality`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}qualifiedCardinality`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sameAs`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sameAs`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines that two given individuals are equal.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sameAs`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sameAs`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sameAs`),
      namedNode(`${rdfs}label`),
      literal(`sameAs`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sameAs`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}someValuesFrom`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}someValuesFrom`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the class that an existential property restriction refers to.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}someValuesFrom`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Restriction`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}someValuesFrom`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}someValuesFrom`),
      namedNode(`${rdfs}label`),
      literal(`someValuesFrom`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}someValuesFrom`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sourceIndividual`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sourceIndividual`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the subject of a negative property assertion.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sourceIndividual`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}NegativePropertyAssertion`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sourceIndividual`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sourceIndividual`),
      namedNode(`${rdfs}label`),
      literal(`sourceIndividual`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}sourceIndividual`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetIndividual`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetIndividual`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the object of a negative object property assertion.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetIndividual`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}NegativePropertyAssertion`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetIndividual`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetIndividual`),
      namedNode(`${rdfs}label`),
      literal(`targetIndividual`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetIndividual`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetValue`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetValue`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the value of a negative data property assertion.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetValue`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}NegativePropertyAssertion`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetValue`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetValue`),
      namedNode(`${rdfs}label`),
      literal(`targetValue`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}targetValue`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topDataProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topDataProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The data property that relates every individual to every data value.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topDataProperty`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topDataProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topDataProperty`),
      namedNode(`${rdfs}label`),
      literal(`topDataProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topDataProperty`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topObjectProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topObjectProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The object property that relates every two individuals.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topObjectProperty`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topObjectProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topObjectProperty`),
      namedNode(`${rdfs}label`),
      literal(`topObjectProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}topObjectProperty`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Thing`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}unionOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}unionOf`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the collection of classes or data ranges that build a union.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}unionOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Class`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}unionOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}unionOf`),
      namedNode(`${rdfs}label`),
      literal(`unionOf`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}unionOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionIRI`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}OntologyProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionIRI`),
      namedNode(`${rdfs}comment`),
      literal(`The property that identifies the version IRI of an ontology.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionIRI`),
      namedNode(`${rdfs}domain`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionIRI`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionIRI`),
      namedNode(`${rdfs}label`),
      literal(`versionIRI`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionIRI`),
      namedNode(`${rdfs}range`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionInfo`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionInfo`),
      namedNode(`${rdfs}comment`),
      literal(`The annotation property that provides version information for an ontology or another OWL construct.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionInfo`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionInfo`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionInfo`),
      namedNode(`${rdfs}label`),
      literal(`versionInfo`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}versionInfo`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}withRestrictions`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}withRestrictions`),
      namedNode(`${rdfs}comment`),
      literal(`The property that determines the collection of facet-value pairs that define a datatype restriction.`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}withRestrictions`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Datatype`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}withRestrictions`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(owl),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}withRestrictions`),
      namedNode(`${rdfs}label`),
      literal(`withRestrictions`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${owl}withRestrictions`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${dc11}title`),
      literal(`The OWL 2 Schema vocabulary (OWL 2)`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${rdfs}comment`),
      literal(`
  This ontology partially describes the built-in classes and
  properties that together form the basis of the RDF/XML syntax of OWL 2.
  The content of this ontology is based on Tables 6.1 and 6.2
  in Section 6.4 of the OWL 2 RDF-Based Semantics specification,
  available at http://www.w3.org/TR/owl2-rdf-based-semantics/.
  Please note that those tables do not include the different annotations
  (labels, comments and rdfs:isDefinedBy links) used in this file.
  Also note that the descriptions provided in this ontology do not
  provide a complete and correct formal description of either the syntax
  or the semantics of the introduced terms (please see the OWL 2
  recommendations for the complete and normative specifications).
  Furthermore, the information provided by this ontology may be
  misleading if not used with care. This ontology SHOULD NOT be imported
  into OWL ontologies. Importing this file into an OWL 2 DL ontology
  will cause it to become an OWL 2 Full ontology and may have other,
  unexpected, consequences.
   `),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns7),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns8),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns9),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns10}table-axiomatic-classes`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns10}table-axiomatic-properties`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${owl}imports`),
      namedNode(`${ns11}rdf-schema`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${owl}versionIRI`),
      namedNode(`${ns5}owl`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${owl}versionInfo`),
      literal(`$Date: 2009/11/15 10:54:12 $`),
      namedNode(owl)
    ),
    quad(
      namedNode(`${ns5}owl`),
      namedNode(`${grddl}namespaceTransformation`),
      namedNode(`${ns13}owx2rdf.xsl`),
      namedNode(owl)
    ),

  ]
}
