/* This file was automatically generated. Do not edit by hand. */

const {
  ns1,
  rdfs,
  sem,
  ns4,
  dcmitype,
  dc11,
  dcterms,
  rdf,
  owl,
  skos,
  ns11,
  ns12,
  ns13,
  ns14,
  foaf,
  wgs,
  ns17,
  ns18
} = {
  'ns1': 'http://linkedevents.org/ontology/',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'sem': 'http://semanticweb.cs.vu.nl/2009/11/sem/',
  'ns4': 'http://purl.org/NET/c4dm/event.owl#',
  'dcmitype': 'http://purl.org/dc/dcmitype/',
  'dc11': 'http://purl.org/dc/elements/1.1/',
  'dcterms': 'http://purl.org/dc/terms/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'skos': 'http://www.w3.org/2004/02/skos/core#',
  'ns11': 'http://sw.opencyc.org/2009/04/07/concept/en/',
  'ns12': 'http://www.loa-cnr.it/ontologies/DOLCE-Lite.owl#',
  'ns13': 'http://www.ontologyportal.org/translations/SUMO.owl.txt#',
  'ns14': 'http://www8.informatik.uni-erlangen.de/IMMD8/Services/cidoc-crm/erlangen-crm_090330_5_0_1.owl#',
  'foaf': 'http://xmlns.com/foaf/0.1/',
  'wgs': 'http://www.w3.org/2003/01/geo/wgs84_pos#',
  'ns17': 'http://www.w3.org/2006/',
  'ns18': 'http://www.kulttuurisampo.fi/ebkr/'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(`${ns1}Event`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns1),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns1}atTime`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns1),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns1}inSpace`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns1),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns1}involved`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns1),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns4}Event`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns4}Factor`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns4}Product`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns4}sub_event`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(sem)
    ),
    quad(
      namedNode(`${dcmitype}Event`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcmitype),
      namedNode(sem)
    ),
    quad(
      namedNode(`${dcmitype}PhysicalObject`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcmitype),
      namedNode(sem)
    ),
    quad(
      namedNode(`${dc11}type`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dc11),
      namedNode(sem)
    ),
    quad(
      namedNode(`${dcterms}Agent`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(sem)
    ),
    quad(
      namedNode(`${dcterms}AgentClass`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(sem)
    ),
    quad(
      namedNode(`${dcterms}Location`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(sem)
    ),
    quad(
      namedNode(`${dcterms}PhysicalResource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${rdfs}comment`),
      literal(`Actors are entities that take part in an Event, either actively or passively. Actors do not necessarily have to be sentient. They can also be objects. Actors are a thing, animate or inanimate, physical or non-physical.
`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${rdfs}label`),
      literal(`Actor`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Authority`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Core`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${skos}broadMatch`),
      namedNode(`${ns11}SomethingExisting`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${skos}broadMatch`),
      namedNode(`${ns12}endurant`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${dcterms}Agent`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${dcterms}AgentClass`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns11}Agent-Generic`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns13}Agent`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns14}E39.Actor`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Actor`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${foaf}Agent`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}ActorType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}ActorType`),
      namedNode(`${rdfs}comment`),
      literal(`EventType contains all resources that are used to classify Actors, e.g. person`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}ActorType`),
      namedNode(`${rdfs}label`),
      literal(`Actor type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}ActorType`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Authority`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Authority`),
      namedNode(`${rdfs}comment`),
      literal(`Authorities are entities that state SEM properties. Their nature is not specified. They can symbolize people, organizations, sources of information, etc.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Authority`),
      namedNode(`${rdfs}label`),
      literal(`Authority`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Constraint`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Constraint`),
      namedNode(`${rdfs}comment`),
      literal(`The SEM Constraint class contains instances of properties that have a constrained (i.e. not universal) validity. This includes time dependent validity (Temporary), validity in the guise of a specific role (Role), or validity according to a given Authority (View).`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Constraint`),
      namedNode(`${rdfs}label`),
      literal(`Constraint`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Core`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Core`),
      namedNode(`${rdfs}comment`),
      literal(`The SEM Core class contains all entities that make up the context of an event: Events, Actors, Places, Times. This class is meant to be extended for each application domain.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Core`),
      namedNode(`${rdfs}label`),
      literal(`Core`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${rdfs}comment`),
      literal(`Events are things that happen. This comprises everything from historical events to web site sessions and mythical journeys. Event is the central class of SEM.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${rdfs}label`),
      literal(`Event`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Core`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${skos}broadMatch`),
      namedNode(`${ns1}Event`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${skos}broadMatch`),
      namedNode(`${ns4}Event`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${dcmitype}Event`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns11}Situation`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns12}perdurant`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns13}Process`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Event`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns14}E5.Event`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}EventType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}EventType`),
      namedNode(`${rdfs}comment`),
      literal(`EventType contains all resources that are used to classify Events, e.g. meeting.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}EventType`),
      namedNode(`${rdfs}label`),
      literal(`Event type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}EventType`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${rdfs}comment`),
      literal(`Objects are passive, inanimate Actors.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${rdfs}label`),
      literal(`Object`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Actor`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${skos}broadMatch`),
      namedNode(`${ns11}SomethingExisting`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${skos}broadMatch`),
      namedNode(`${ns12}endurant`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns13}Object`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns14}E19.Physical_Object`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns14}E21.Person`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${skos}narrowMatch`),
      namedNode(`${ns4}Factor`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${skos}narrowMatch`),
      namedNode(`${ns4}Product`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${skos}narrowMatch`),
      namedNode(`${dcmitype}PhysicalObject`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Object`),
      namedNode(`${skos}narrowMatch`),
      namedNode(`${dcterms}PhysicalResource`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${rdfs}comment`),
      literal(`Places are locations where an Event happens. They do not need to be physical places and hence do not necessarily need coordinates. Neither do they need to have any significance apart from them being the location of an Event.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${rdfs}label`),
      literal(`Place`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Core`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${dcterms}Location`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns11}EnduringThing-Localized`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns13}GeographicArea`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns14}E53.Place`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${skos}narrowMatch`),
      namedNode(`${ns12}PhysicalRegion`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Place`),
      namedNode(`${skos}narrowMatch`),
      namedNode(`${wgs}SpatialThing`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}PlaceType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}PlaceType`),
      namedNode(`${rdfs}comment`),
      literal(`EventType contains all resources that are used to classify Places, e.g. river.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}PlaceType`),
      namedNode(`${rdfs}label`),
      literal(`Place type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}PlaceType`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Role`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Role`),
      namedNode(`${rdfs}comment`),
      literal(`Roles are properties with a subspecified function or position indicated by a RoleType in the scope of an Event. For example, the sem:hasActor property can be subspecified with the RoleType attacker, to denote that the type of participation of the Actor in the scope of the Event is "attacker". The sem:hasPlace property can be subspecified with the RoleType origin, to denote that within the scope of the Event it is the origin.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Role`),
      namedNode(`${rdfs}label`),
      literal(`Role`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Role`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Constraint`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Role`),
      namedNode(`${skos}relatedMatch`),
      namedNode(`${ns11}Role`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Role`),
      namedNode(`${skos}relatedMatch`),
      namedNode(`${ns12}region`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Role`),
      namedNode(`${skos}relatedMatch`),
      namedNode(`${ns13}IntentionalProcess`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}RoleType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}RoleType`),
      namedNode(`${rdfs}comment`),
      literal(`EventType contains all resources that are used to classify Roles, e.g. receiver.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}RoleType`),
      namedNode(`${rdfs}label`),
      literal(`Role type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}RoleType`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Temporary`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Temporary`),
      namedNode(`${rdfs}comment`),
      literal(`Temporaries are properties that only hold during a certain Time, which is either indicated with the sem:hasTime property to an instance of sem:Time, or with the sem:hasTimeStamp property to some timestamp(s).`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Temporary`),
      namedNode(`${rdfs}label`),
      literal(`Temporary`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Temporary`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Constraint`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Time`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Time`),
      namedNode(`${rdfs}comment`),
      literal(`Time contains symbolic representations of when an Event took place. Time instances do not necessarily need to have a timestamp associated with them. The Time class exists to represent semantics of time, e.g. that one thing happens before another, even though the exact timestamps are unknown.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Time`),
      namedNode(`${rdfs}label`),
      literal(`Time`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Time`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Core`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Time`),
      namedNode(`${skos}broadMatch`),
      namedNode(`${ns17}timeTemporalEntity`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}TimeType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}TimeType`),
      namedNode(`${rdfs}comment`),
      literal(`EventType contains all resources that are used to classify Time, e.g. century.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}TimeType`),
      namedNode(`${rdfs}label`),
      literal(`Time type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}TimeType`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Type`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Type`),
      namedNode(`${rdfs}comment`),
      literal(`The SEM Type class contains all types of Core instances. These can be either individuals of classes themselves. This class is meant to be extended for each application domain.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Type`),
      namedNode(`${rdfs}label`),
      literal(`Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Type`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns12}AbstractRegion`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}Type`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns14}E55.Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}View`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}View`),
      namedNode(`${rdfs}comment`),
      literal(`Views are properties that only hold according to a certain Authority.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}View`),
      namedNode(`${rdfs}label`),
      literal(`View`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}View`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sem}Constraint`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}accordingTo`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}accordingTo`),
      namedNode(`${rdfs}comment`),
      literal(`According to is used to state which Authority sais that a property constrained by the View Constraint is true.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}accordingTo`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sem}View`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}accordingTo`),
      namedNode(`${rdfs}label`),
      literal(`according to`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}accordingTo`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}Authority`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}actorType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}actorType`),
      namedNode(`${rdfs}comment`),
      literal(`Has actor type is used to assign a type to an actor.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}actorType`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sem}Actor`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}actorType`),
      namedNode(`${rdfs}label`),
      literal(`has actor type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}actorType`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}ActorType`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}actorType`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}eventProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}eventProperty`),
      namedNode(`${rdfs}comment`),
      literal(`Event properties connect Events to other SEM Core entities.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}eventProperty`),
      namedNode(`${rdfs}label`),
      literal(`event property`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}eventType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}eventType`),
      namedNode(`${rdfs}comment`),
      literal(`Has event type is used to assign a type to an event.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}eventType`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sem}Event`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}eventType`),
      namedNode(`${rdfs}label`),
      literal(`has event type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}eventType`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}EventType`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}eventType`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasActor`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasActor`),
      namedNode(`${rdfs}comment`),
      literal(`Has actor is used to state which Actors or Objects participate in an Event.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasActor`),
      namedNode(`${rdfs}label`),
      literal(`has Actor`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasActor`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}Actor`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasActor`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}eventProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasActor`),
      namedNode(`${skos}exactMatch`),
      namedNode(`${ns1}involved`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasActor`),
      namedNode(`${skos}narrowMatch`),
      namedNode(`${ns18}agent`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasBeginTimeStamp`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasBeginTimeStamp`),
      namedNode(`${rdfs}comment`),
      literal(`Has begin timestamp is used to indicate the beginning of a time interval. Omitting the hasBeginTimeStamp while stating a hasEndTimeStamp is interpreted as an open ended interval.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasBeginTimeStamp`),
      namedNode(`${rdfs}label`),
      literal(`has begin timestamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasBeginTimeStamp`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}hasTimeStamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEarliestBeginTimeStamp`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEarliestBeginTimeStamp`),
      namedNode(`${rdfs}comment`),
      literal(`Has earliest begin timestamp is used to indicate the earliest possible starting time of an uncertain time interval.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEarliestBeginTimeStamp`),
      namedNode(`${rdfs}label`),
      literal(`has earliest begin timestamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEarliestBeginTimeStamp`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}hasBeginTimeStamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEarliestEndTimeStamp`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEarliestEndTimeStamp`),
      namedNode(`${rdfs}comment`),
      literal(`Has earliest end timestamp is used to indicate the earliest possible ending time of an uncertain time interval.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEarliestEndTimeStamp`),
      namedNode(`${rdfs}label`),
      literal(`has earliest end timestamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEarliestEndTimeStamp`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}hasEndTimeStamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEndTimeStamp`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEndTimeStamp`),
      namedNode(`${rdfs}comment`),
      literal(`Has end timestamp is used to indicate the end of a time interval. Omitting the hasEndTimeStamp while stating a hasBeginTimeStamp is interpreted as an open ended interval.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEndTimeStamp`),
      namedNode(`${rdfs}label`),
      literal(`has end timestamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasEndTimeStamp`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}hasTimeStamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasLatestBeginTimeStamp`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasLatestBeginTimeStamp`),
      namedNode(`${rdfs}comment`),
      literal(`Has latest begin timestamp is used to indicate the latest possible starting time of an uncertain time interval.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasLatestBeginTimeStamp`),
      namedNode(`${rdfs}label`),
      literal(`has latest begin timestamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasLatestBeginTimeStamp`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}hasBeginTimeStamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasLatestEndTimeStamp`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasLatestEndTimeStamp`),
      namedNode(`${rdfs}comment`),
      literal(`Has latest end timestamp is used to indicate the latest possible ending time of an uncertain time interval.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasLatestEndTimeStamp`),
      namedNode(`${rdfs}label`),
      literal(`has latest end timestamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasLatestEndTimeStamp`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}hasEndTimeStamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasPlace`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasPlace`),
      namedNode(`${rdfs}comment`),
      literal(`Has place is used to state in which Place(s) an Event happened. Coordinates can be attached to the Place with the W3C Geospatial Vocabulary (http://www.w3.org/2005/Incubator/geo/XGR-geo-20071023/).`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasPlace`),
      namedNode(`${rdfs}label`),
      literal(`has Place`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasPlace`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}Place`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasPlace`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}eventProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasPlace`),
      namedNode(`${skos}exactMatch`),
      namedNode(`${ns18}place`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasPlace`),
      namedNode(`${skos}narrowMatch`),
      namedNode(`${ns1}inSpace`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubEvent`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubEvent`),
      namedNode(`${rdfs}comment`),
      literal(`Has subevent connects an Event to other Events that belong to it. This is a very generic property that does not mean the subevents fully define the superconcept or that there is any causal relationship.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubEvent`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sem}Event`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubEvent`),
      namedNode(`${rdfs}label`),
      literal(`has subevent`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubEvent`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}Event`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubEvent`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}eventProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubEvent`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sem}subEventOf`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubEvent`),
      namedNode(`${skos}exactMatch`),
      namedNode(`${ns4}sub_event`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubType`),
      namedNode(`${rdfs}comment`),
      literal(`Has sub type is used to state that a type falls under another type. This is a generic aggregation relation that is used to generalize over various hierarchical relations that can exist between types.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubType`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sem}Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubType`),
      namedNode(`${rdfs}label`),
      literal(`has subtype`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubType`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasSubType`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sem}subTypeOf`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTime`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTime`),
      namedNode(`${rdfs}comment`),
      literal(`Has time is used to indicate at which time an Event took place or when a property under the Temporary Constraint is valid. Has time points to a symbolic representation of time, which allows semantic relations between time resources. (see http://www.w3.org/TR/owl-time/)`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTime`),
      namedNode(`${rdfs}label`),
      literal(`has Time`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTime`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}Time`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTime`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}eventProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTime`),
      namedNode(`${skos}broadMatch`),
      namedNode(`${ns1}atTime`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTimeStamp`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTimeStamp`),
      namedNode(`${rdfs}comment`),
      literal(`Has timestamp is used to put time indicators on any individual. It is the most common way to state when an Event took place. There are subproperties of hasTimeStamp to represent time intervals and uncertain time intervals. If the exact moment is not known, but it is necessary to specify a certain time, use hasTime instead. All of these properties are also used to indicate the time at which a property under the Temporary Constraint is valid.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTimeStamp`),
      namedNode(`${rdfs}label`),
      literal(`has timestamp`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}hasTimeStamp`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${ns18}time`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}placeType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}placeType`),
      namedNode(`${rdfs}comment`),
      literal(`Has place type is used to assign a type to a place.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}placeType`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sem}Place`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}placeType`),
      namedNode(`${rdfs}label`),
      literal(`has place type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}placeType`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}PlaceType`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}placeType`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}roleType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}roleType`),
      namedNode(`${rdfs}comment`),
      literal(`Has role type is used to assign a role type to a Role property constraint. This role is a subspecification of the eventProperty which it constrains. For example, if an Event hasActor an Actor and this property is given a Role Constraint, then roleType can be used to assign a role to the participation of the Actor in the Event indicated by hasActor.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}roleType`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sem}Role`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}roleType`),
      namedNode(`${rdfs}label`),
      literal(`has role type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}roleType`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}RoleType`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}roleType`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}subEventOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}subEventOf`),
      namedNode(`${rdfs}comment`),
      literal(`Inverse property of hasSubEvent`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}subEventOf`),
      namedNode(`${rdfs}label`),
      literal(`subevent of`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}subTypeOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}subTypeOf`),
      namedNode(`${rdfs}comment`),
      literal(`The inverse property of hasSubType.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}subTypeOf`),
      namedNode(`${rdfs}label`),
      literal(`subtype of`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}subTypeOf`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}timeType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}timeType`),
      namedNode(`${rdfs}comment`),
      literal(`Has time type is used to assign a type to a time individual.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}timeType`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sem}Time`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}timeType`),
      namedNode(`${rdfs}label`),
      literal(`has time type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}timeType`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}TimeType`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}timeType`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sem}type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}type`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}type`),
      namedNode(`${rdfs}comment`),
      literal(`Type is the super property of the properties that are used to indicate the type of a Core instance, eventType, actorType, placeType, timeType; and of roleType. Types can be both classes and individuals, cf. OWL 2 punning.`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}type`),
      namedNode(`${rdfs}label`),
      literal(`type property`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}type`),
      namedNode(`${rdfs}range`),
      namedNode(`${sem}Type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}type`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdf}type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}type`),
      namedNode(`${skos}closeMatch`),
      namedNode(`${dc11}type`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${sem}type`),
      namedNode(`${skos}relatedMatch`),
      namedNode(`${ns18}quality`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns11}Agent-Generic`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns11),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns11}EnduringThing-Localized`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns11),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns11}Role`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns11),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns11}Situation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns11),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns11}SomethingExisting`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns11),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns18}agent`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns18),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns18}place`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns18),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns18}quality`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns18),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns18}time`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns18),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns12}AbstractRegion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns12),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns12}PhysicalRegion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns12),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns12}endurant`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns12),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns12}perdurant`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns12),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns12}region`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns12),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns13}Agent`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns13),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns13}GeographicArea`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns13),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns13}IntentionalProcess`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns13),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns13}Object`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns13),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns13}Process`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns13),
      namedNode(sem)
    ),
    quad(
      namedNode(`${wgs}SpatialThing`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(wgs),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns17}timeTemporalEntity`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns17}time`),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns14}E19.Physical_Object`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns14),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns14}E21.Person`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns14),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns14}E39.Actor`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns14),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns14}E5.Event`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns14),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns14}E53.Place`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns14),
      namedNode(sem)
    ),
    quad(
      namedNode(`${ns14}E55.Type`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns14),
      namedNode(sem)
    ),
    quad(
      namedNode(`${foaf}Agent`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(sem)
    ),

  ]
}
