/* This file was automatically generated. Do not edit by hand. */

const {
  _void,
  rdf,
  rdfs,
  owl,
  foaf,
  xsd,
  ns7,
  dcterms,
  ns9,
  ns10,
  ns11,
  ns12,
  ns13,
  vann,
  ns15,
  ns16,
  ns17,
  ns18,
  ns19,
  ns20,
  ns21,
  ns22,
  ns23
} = {
  '_void': 'http://rdfs.org/ns/void#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'foaf': 'http://xmlns.com/foaf/0.1/',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'ns7': 'http://vocab.deri.ie/void#',
  'dcterms': 'http://purl.org/dc/terms/',
  'ns9': 'http://vocab.deri.ie/',
  'ns10': 'http://www.w3.org/ns/adms#',
  'ns11': 'http://purl.org/adms/status/',
  'ns12': 'http://',
  'ns13': 'http://purl.org/adms/assettype/',
  'vann': 'http://purl.org/vocab/vann/',
  'ns15': 'https://schema.org/',
  'ns16': 'http://kwijibo.talis.com/',
  'ns17': 'http://www.talis.com/',
  'ns18': 'http://users.ox.ac.uk/~zool0770/',
  'ns19': 'http://www.deri.ie/',
  'ns20': 'http://www.zoo.ox.ac.uk/',
  'ns21': 'http://sw-app.org/',
  'ns22': 'http://linkeddata.deri.ie/',
  'ns23': 'http://richard.cyganiak.de/'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 9; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(`${_void}Dataset`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}Dataset`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}Dataset`),
      namedNode(`${rdfs}comment`),
      literal(`A set of RDF triples that are published, maintained or aggregated by a single provider.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}Dataset`),
      namedNode(`${rdfs}label`),
      literal(`dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}DatasetDescription`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}DatasetDescription`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}DatasetDescription`),
      namedNode(`${rdfs}comment`),
      literal(`A web resource whose foaf:primaryTopic or foaf:topics include void:Datasets.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}DatasetDescription`),
      namedNode(`${rdfs}label`),
      literal(`dataset description`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}DatasetDescription`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${foaf}Document`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}Linkset`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}Linkset`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}Linkset`),
      namedNode(`${rdfs}comment`),
      literal(`A collection of RDF links between two void:Datasets.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}Linkset`),
      namedNode(`${rdfs}label`),
      literal(`linkset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}Linkset`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}TechnicalFeature`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}TechnicalFeature`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}TechnicalFeature`),
      namedNode(`${rdfs}comment`),
      literal(`A technical feature of a void:Dataset, such as a supported RDF serialization format.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}TechnicalFeature`),
      namedNode(`${rdfs}label`),
      literal(`technical feature`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}class`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}FunctionalProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}class`),
      namedNode(`${rdfs}comment`),
      literal(`The rdfs:Class that is the rdf:type of all entities in a class-based partition.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}class`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}class`),
      namedNode(`${rdfs}label`),
      literal(`class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}class`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Class`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classPartition`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classPartition`),
      namedNode(`${rdfs}comment`),
      literal(`A subset of a void:Dataset that contains only the entities of a certain rdfs:Class.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classPartition`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classPartition`),
      namedNode(`${rdfs}label`),
      literal(`class partition`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classPartition`),
      namedNode(`${rdfs}range`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classPartition`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${_void}subset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classes`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classes`),
      namedNode(`${rdfs}comment`),
      literal(`The total number of distinct classes in a void:Dataset. In other words, the number of distinct resources occuring as objects of rdf:type triples in the dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classes`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classes`),
      namedNode(`${rdfs}label`),
      literal(`classes`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}classes`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}dataDump`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}dataDump`),
      namedNode(`${rdfs}comment`),
      literal(`An RDF dump, partial or complete, of a void:Dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}dataDump`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}dataDump`),
      namedNode(`${rdfs}label`),
      literal(`Data Dump`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}dataDump`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctObjects`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctObjects`),
      namedNode(`${rdfs}comment`),
      literal(`The total number of distinct objects in a void:Dataset. In other words, the number of distinct resources that occur in the object position of triples in the dataset. Literals are included in this count.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctObjects`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctObjects`),
      namedNode(`${rdfs}label`),
      literal(`distinct objects`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctObjects`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctSubjects`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctSubjects`),
      namedNode(`${rdfs}comment`),
      literal(`The total number of distinct subjects in a void:Dataset. In other words, the number of distinct resources that occur in the subject position of triples in the dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctSubjects`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctSubjects`),
      namedNode(`${rdfs}label`),
      literal(`distinct subjects`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}distinctSubjects`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}documents`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}documents`),
      namedNode(`${rdfs}comment`),
      literal(`The total number of documents, for datasets that are published as a set of individual documents, such as RDF/XML documents or RDFa-annotated web pages. Non-RDF documents, such as web pages in HTML or images, are usually not included in this count. This property is intended for datasets where the total number of triples or entities is hard to determine. void:triples or void:entities should be preferred where practical.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}documents`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}documents`),
      namedNode(`${rdfs}label`),
      literal(`number of documents`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}documents`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}entities`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}entities`),
      namedNode(`${rdfs}comment`),
      literal(`The total number of entities that are described in a void:Dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}entities`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}entities`),
      namedNode(`${rdfs}label`),
      literal(`number of entities`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}entities`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}exampleResource`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}exampleResource`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}exampleResource`),
      namedNode(`${rdfs}label`),
      literal(`example resource of dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}exampleResource`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}feature`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}feature`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}feature`),
      namedNode(`${rdfs}label`),
      literal(`feature`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}feature`),
      namedNode(`${rdfs}range`),
      namedNode(`${_void}TechnicalFeature`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}inDataset`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}inDataset`),
      namedNode(`${rdfs}comment`),
      literal(`Points to the void:Dataset that a document is a part of.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}inDataset`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Document`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}inDataset`),
      namedNode(`${rdfs}label`),
      literal(`in dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}inDataset`),
      namedNode(`${rdfs}range`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}linkPredicate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}linkPredicate`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Linkset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}linkPredicate`),
      namedNode(`${rdfs}label`),
      literal(`a link predicate`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}linkPredicate`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}objectsTarget`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}FunctionalProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}objectsTarget`),
      namedNode(`${rdfs}comment`),
      literal(`The dataset describing the objects of the triples contained in the Linkset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}objectsTarget`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Linkset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}objectsTarget`),
      namedNode(`${rdfs}label`),
      literal(`Objects Target`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}objectsTarget`),
      namedNode(`${rdfs}range`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}objectsTarget`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${_void}target`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}openSearchDescription`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}openSearchDescription`),
      namedNode(`${rdfs}comment`),
      literal(`An OpenSearch description document for a free-text search service over a void:Dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}openSearchDescription`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}openSearchDescription`),
      namedNode(`${rdfs}label`),
      literal(`open search description`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}openSearchDescription`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}properties`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}properties`),
      namedNode(`${rdfs}comment`),
      literal(`The total number of distinct properties in a void:Dataset. In other words, the number of distinct resources that occur in the predicate position of triples in the dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}properties`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}properties`),
      namedNode(`${rdfs}label`),
      literal(`number of properties`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}properties`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}property`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}FunctionalProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}property`),
      namedNode(`${rdfs}comment`),
      literal(`The rdf:Property that is the predicate of all triples in a property-based partition.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}property`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}property`),
      namedNode(`${rdfs}label`),
      literal(`property`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}property`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}propertyPartition`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}propertyPartition`),
      namedNode(`${rdfs}comment`),
      literal(`A subset of a void:Dataset that contains only the triples of a certain rdf:Property.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}propertyPartition`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}propertyPartition`),
      namedNode(`${rdfs}label`),
      literal(`property partition`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}propertyPartition`),
      namedNode(`${rdfs}range`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}propertyPartition`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${_void}subset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}rootResource`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}rootResource`),
      namedNode(`${rdfs}comment`),
      literal(`A top concept or entry point for a void:Dataset that is structured in a tree-like fashion. All resources in a dataset can be reached by following links from its root resources in a small number of steps.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}rootResource`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}rootResource`),
      namedNode(`${rdfs}label`),
      literal(`root resource`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}sparqlEndpoint`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}sparqlEndpoint`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}sparqlEndpoint`),
      namedNode(`${rdfs}label`),
      literal(`has a SPARQL endpoint at`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subjectsTarget`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}FunctionalProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subjectsTarget`),
      namedNode(`${rdfs}comment`),
      literal(`The dataset describing the subjects of triples contained in the Linkset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subjectsTarget`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Linkset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subjectsTarget`),
      namedNode(`${rdfs}label`),
      literal(`Subjects Target`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subjectsTarget`),
      namedNode(`${rdfs}range`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subjectsTarget`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${_void}target`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subset`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subset`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subset`),
      namedNode(`${rdfs}label`),
      literal(`has subset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}subset`),
      namedNode(`${rdfs}range`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}target`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}target`),
      namedNode(`${rdfs}comment`),
      literal(`One of the two datasets linked by the Linkset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}target`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Linkset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}target`),
      namedNode(`${rdfs}label`),
      literal(`Target`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}target`),
      namedNode(`${rdfs}range`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}triples`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}triples`),
      namedNode(`${rdfs}comment`),
      literal(`The total number of triples contained in a void:Dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}triples`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}triples`),
      namedNode(`${rdfs}label`),
      literal(`number of triples`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}triples`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}integer`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriLookupEndpoint`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriLookupEndpoint`),
      namedNode(`${rdfs}comment`),
      literal(`Defines a simple URI look-up protocol for accessing a dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriLookupEndpoint`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriLookupEndpoint`),
      namedNode(`${rdfs}label`),
      literal(`has an URI look-up endpoint at`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriRegexPattern`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}DatatypeProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriRegexPattern`),
      namedNode(`${rdfs}comment`),
      literal(`Defines a regular expression pattern matching URIs in the dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriRegexPattern`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriRegexPattern`),
      namedNode(`${rdfs}label`),
      literal(`has URI regular expression pattern`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriSpace`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriSpace`),
      namedNode(`${rdfs}comment`),
      literal(`A URI that is a common string prefix of all the entity URIs in a void:Dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriSpace`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriSpace`),
      namedNode(`${rdfs}label`),
      literal(`URI space`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}uriSpace`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}vocabulary`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}vocabulary`),
      namedNode(`${rdfs}comment`),
      literal(`A vocabulary that is used in the dataset.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}vocabulary`),
      namedNode(`${rdfs}domain`),
      namedNode(`${_void}Dataset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${_void}vocabulary`),
      namedNode(`${rdfs}label`),
      literal(`vocabulary`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns7}rdf`),
      namedNode(`${dcterms}FileFormat`),
      namedNode(`${ns9}void.ttl`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns7}rdf`),
      namedNode(`${rdf}type`),
      namedNode(`${ns10}SemanticDistribution`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns7}rdf`),
      namedNode(`${ns10}accessURL`),
      literal(`http://vocab.deri.ie/void.rdf`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns7}rdf`),
      namedNode(`${ns10}status`),
      namedNode(`${ns11}Completed`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns7}ttl`),
      namedNode(`${dcterms}FileFormat`),
      namedNode(`${ns9}void.ttl`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns7}ttl`),
      namedNode(`${rdf}type`),
      namedNode(`${ns10}SemanticDistribution`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns7}ttl`),
      namedNode(`${ns10}accessURL`),
      literal(`http://vocab.deri.ie/void.ttl`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns7}ttl`),
      namedNode(`${ns10}status`),
      namedNode(`${ns11}Completed`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}created`),
      literal(`2010-01-26`, namedNode(`${xsd}date`)),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}creator`),
      blankNodes[0],
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}creator`),
      blankNodes[1],
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}creator`),
      blankNodes[2],
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}creator`),
      blankNodes[3],
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}description`),
      literal(`The Vocabulary of Interlinked Datasets (VoID) is an RDF Schema vocabulary for expressing metadata about RDF datasets. It is intended as a bridge between the publishers and users of RDF data, with applications ranging from data discovery to cataloging and archiving of datasets. This document provides a formal definition of the new RDF classes and properties introduced for VoID. It is a companion to the main specification document for VoID, <em><a href="http://www.w3.org/TR/void/">Describing Linked Datasets with the VoID Vocabulary</a></em>.`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}modified`),
      literal(`2011-03-06`, namedNode(`${xsd}date`)),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}partOf`),
      namedNode(`${ns12}vocab.deri.ie`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}publisher`),
      blankNodes[4],
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}status`),
      namedNode(`${ns11}UnderDevelopment`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}title`),
      literal(`Vocabulary of Interlinked Datasets (VoID)`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${dcterms}type`),
      namedNode(`${ns13}Ontology`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${vann}preferredNamespacePrefix`),
      literal(`void`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${vann}preferredNamespaceUri`),
      literal(`http://rdfs.org/ns/void#`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${rdf}type`),
      namedNode(`${ns10}SemanticAsset`),
      namedNode(_void)
    ),
    quad(
      namedNode(`${ns9}void`),
      namedNode(`${foaf}homepage`),
      namedNode(`${ns9}void.html`),
      namedNode(_void)
    ),
    quad(
      blankNodes[0],
      namedNode(`${rdf}type`),
      namedNode(`${ns15}Person`),
      namedNode(_void)
    ),
    quad(
      blankNodes[0],
      namedNode(`${ns15}affiliation`),
      blankNodes[5],
      namedNode(_void)
    ),
    quad(
      blankNodes[0],
      namedNode(`${ns15}email`),
      namedNode('mailto:Keith.Alexander@talis.com'),
      namedNode(_void)
    ),
    quad(
      blankNodes[0],
      namedNode(`${ns15}name`),
      literal(`Keith Alexander`),
      namedNode(_void)
    ),
    quad(
      blankNodes[0],
      namedNode(`${ns15}url`),
      namedNode(ns16),
      namedNode(_void)
    ),
    quad(
      blankNodes[5],
      namedNode(`${rdf}type`),
      namedNode(`${ns15}Organization`),
      namedNode(_void)
    ),
    quad(
      blankNodes[5],
      namedNode(`${ns15}name`),
      literal(`Talis`),
      namedNode(_void)
    ),
    quad(
      blankNodes[5],
      namedNode(`${ns15}url`),
      namedNode(ns17),
      namedNode(_void)
    ),
    quad(
      blankNodes[1],
      namedNode(`${rdf}type`),
      namedNode(`${ns15}Person`),
      namedNode(_void)
    ),
    quad(
      blankNodes[1],
      namedNode(`${ns15}affiliation`),
      blankNodes[6],
      namedNode(_void)
    ),
    quad(
      blankNodes[1],
      namedNode(`${ns15}email`),
      namedNode('mailto:jun.zhao@zoo.ox.ac.uk'),
      namedNode(_void)
    ),
    quad(
      blankNodes[1],
      namedNode(`${ns15}name`),
      literal(`Jun Zhao`),
      namedNode(_void)
    ),
    quad(
      blankNodes[1],
      namedNode(`${ns15}url`),
      namedNode(ns18),
      namedNode(_void)
    ),
    quad(
      blankNodes[4],
      namedNode(`${rdfs}seeAlso`),
      namedNode(ns19),
      namedNode(_void)
    ),
    quad(
      blankNodes[4],
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns12}www.insight-centre.org`),
      namedNode(_void)
    ),
    quad(
      blankNodes[4],
      namedNode(`${ns15}identifier`),
      namedNode(`${ns7}Digital%20Enterprise%20Research%20Institute%2C%20NUI%20Galway`),
      namedNode(_void)
    ),
    quad(
      blankNodes[4],
      namedNode(`${ns15}name`),
      literal(`Digital Enterprise Research Institute, NUI Galway`),
      namedNode(_void)
    ),
    quad(
      blankNodes[6],
      namedNode(`${rdf}type`),
      namedNode(`${ns15}Organization`),
      namedNode(_void)
    ),
    quad(
      blankNodes[6],
      namedNode(`${ns15}name`),
      literal(`Department of Zoology, University of Oxford`),
      namedNode(_void)
    ),
    quad(
      blankNodes[6],
      namedNode(`${ns15}url`),
      namedNode(ns20),
      namedNode(_void)
    ),
    quad(
      blankNodes[7],
      namedNode(`${rdf}type`),
      namedNode(`${ns15}Organization`),
      namedNode(_void)
    ),
    quad(
      blankNodes[7],
      namedNode(`${foaf}homepage`),
      namedNode(ns19),
      namedNode(_void)
    ),
    quad(
      blankNodes[7],
      namedNode(`${foaf}name`),
      literal(`Digital Enterprise Research Institute, NUI Galway`),
      namedNode(_void)
    ),
    quad(
      blankNodes[2],
      namedNode(`${rdf}type`),
      namedNode(`${ns15}Person`),
      namedNode(_void)
    ),
    quad(
      blankNodes[2],
      namedNode(`${ns15}affiliation`),
      blankNodes[8],
      namedNode(_void)
    ),
    quad(
      blankNodes[2],
      namedNode(`${ns15}email`),
      namedNode('mailto:michael.hausenblas@deri.org'),
      namedNode(_void)
    ),
    quad(
      blankNodes[2],
      namedNode(`${ns15}name`),
      literal(`Michael Hausenblas`),
      namedNode(_void)
    ),
    quad(
      blankNodes[2],
      namedNode(`${ns15}url`),
      namedNode(`${ns21}about.html`),
      namedNode(_void)
    ),
    quad(
      blankNodes[8],
      namedNode(`${rdf}type`),
      namedNode(`${ns15}Organization`),
      namedNode(_void)
    ),
    quad(
      blankNodes[8],
      namedNode(`${ns15}name`),
      literal(`LiDRC`),
      namedNode(_void)
    ),
    quad(
      blankNodes[8],
      namedNode(`${ns15}url`),
      namedNode(ns22),
      namedNode(_void)
    ),
    quad(
      blankNodes[3],
      namedNode(`${rdf}type`),
      namedNode(`${ns15}Person`),
      namedNode(_void)
    ),
    quad(
      blankNodes[3],
      namedNode(`${ns15}affiliation`),
      blankNodes[7],
      namedNode(_void)
    ),
    quad(
      blankNodes[3],
      namedNode(`${ns15}email`),
      namedNode('mailto:richard.cyganiak@deri.org'),
      namedNode(_void)
    ),
    quad(
      blankNodes[3],
      namedNode(`${ns15}name`),
      literal(`Richard Cyganiak`),
      namedNode(_void)
    ),
    quad(
      blankNodes[3],
      namedNode(`${ns15}url`),
      namedNode(ns23),
      namedNode(_void)
    ),

  ]
}
