/* This file was automatically generated. Do not edit by hand. */

const {
  ns1,
  rdfs,
  ns3,
  sou,
  dcterms,
  rdf,
  qudt,
  xsd,
  unit,
  ns10,
  owl,
  vaem,
  ns13,
  prov
} = {
  'ns1': 'http://qudt.org/2.1/vocab/',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'ns3': 'http://qudt.org/vocab/',
  'sou': 'http://qudt.org/vocab/sou/',
  'dcterms': 'http://purl.org/dc/terms/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'qudt': 'http://qudt.org/schema/qudt/',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'unit': 'http://qudt.org/vocab/unit/',
  'ns10': 'http://qudt.org/2.1/vocab/prefix/',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'vaem': 'http://www.linkedmodel.org/schema/vaem#',
  'ns13': 'http://qudt.org/2.1/schema/facade/',
  'prov': 'http://www.w3.org/ns/prov#'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(`${ns1}sou`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}ASU`),
      namedNode(`${dcterms}description`),
      literal(`The astronomical system of units, formally called the IAU (1976) System of Astronomical Constants, is a system of measurement developed for use in astronomy. It was adopted by the International Astronomical Union (IAU) in 1976, and has been slightly updated since then. The system was developed because of the difficulties in measuring and expressing astronomical data in International System of Units (SI units). In particular, there is a huge quantity of very precise data relating to the positions of objects within the solar system which cannot conveniently be expressed or processed in SI units. Through a number of modifications, the astronomical system of units now explicitly recognizes the consequences of general relativity, which is a necessary addition to the International System of Units in order to accurately treat astronomical data. The astronomical system of units is a tridimensional system, in that it defines units of length, mass and time. The associated astronomical constants also fix the different frames of reference that are needed to report observations. The system is a conventional system, in that neither the unit of length nor the unit of mass are true physical constants, and there are at least three different measures of time.`, namedNode(`${rdf}HTML`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}ASU`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.iau.org/public/themes/measuring/`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}ASU`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}ASU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}ASU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}ASU`),
      namedNode(`${rdfs}label`),
      literal(`Astronomic System Of Units`, 'en'),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${dcterms}description`),
      literal(`The units in this system are formed in a manner similar to that of the cgs electrostatic system of units: the unit of electric current was defined using the law that describes the force between current-carrying wires. To do this, the permeability of free space (the magnetic constant, relating the magnetic flux density in a vacuum to the strength of the external magnetic field), was set at 1. To distinguish cgs electromagnetic units from units in the international system, they were often given the prefix “ab-”. However, most are often referred to purely descriptively as the 'e.m. unit of capacitance', etc. `, namedNode(`${rdf}HTML`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${qudt}abbreviation`),
      literal(`CGS-EMU`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}BIOT`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}CentiM`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}GM`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}SEC`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}UNITLESS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.sizes.com/units/sys_cgs_em.htm`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-EMU`),
      namedNode(`${rdfs}label`),
      literal(`CGS System of Units - EMU`, 'en'),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-ESU`),
      namedNode(`${dcterms}description`),
      literal(`The electrostatic system of units is a system of units used to measure electrical quantities of electric charge, current, and voltage, within the centimeter gram second (or "CGS") metric system of units. In electrostatic units, electrical charge is defined via the force it exerts on other charges. The various units of the e.s.u. system have specific names obtained by prefixing more familiar names with $stat$, but are often referred to purely descriptively as the 'e.s. unit of capacitance', etc. `, namedNode(`${rdf}HTML`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-ESU`),
      namedNode(`${qudt}abbreviation`),
      literal(`CGS-ESU`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-ESU`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Electrostatic_units`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-ESU`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.oxfordreference.com/view/10.1093/acref/9780198605225.001.0001/acref-9780198605225-e-399#`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-ESU`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.sizes.com/units/sys_cgs_stat.htm`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-ESU`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-ESU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-ESU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-ESU`),
      namedNode(`${rdfs}label`),
      literal(`CGS System of Units ESU`, 'en'),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${dcterms}description`),
      literal(`Gaussian units constitute a metric system of physical units. This system is the most common of the several electromagnetic unit systems based on cgs (centimetre–gram–second) units. It is also called the Gaussian unit system, Gaussian-cgs units, or often just cgs units. The term "cgs units" is ambiguous and therefore to be avoided if possible: there are several variants of cgs with conflicting definitions of electromagnetic quantities and units. [Wikipedia]`, namedNode(`${rdf}HTML`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${qudt}abbreviation`),
      literal(`CGS-GAUSS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}CentiM`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}GM`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}SEC`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}UNITLESS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${qudt}informativeReference`),
      literal(`https://en.wikipedia.org/wiki/Gaussian_units`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${rdfs}label`),
      literal(`CGS System of Units - Gaussian`, 'en'),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}CGS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${dcterms}description`),
      literal(`<p>The centimetre-gram-second system (abbreviated CGS or cgs) is a variant of the metric system of physical units based on centimetre as the unit of length, gram as a unit of mass, and second as a unit of time. All CGS mechanical units are unambiguously derived from these three base units, but there are several different ways of extending the CGS system to cover electromagnetism. The CGS system has been largely supplanted by the MKS system, based on metre, kilogram, and second. Note that the term cgs is ambiguous, since there are several variants with conflicting definitions of electromagnetic quantities and units. The unqualified term is generally associated with the Gaussian system of units, so this more precise URI is preferred.</p>`, namedNode(`${rdf}HTML`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${qudt}abbreviation`),
      literal(`CGS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Centimetre_gram_second_system_of_units`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}CentiM`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}GM`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}SEC`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}UNITLESS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Centimetre–gram–second_system_of_units`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://scienceworld.wolfram.com/physics/cgs.html`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.tf.uni-kiel.de/matwis/amat/mw1_ge/kap_2/basics/b2_1_14.html`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${rdfs}label`),
      literal(`CGS System of Units`, 'en'),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}CGS-EMU`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}CGS-ESU`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}CGS`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}IMPERIAL`),
      namedNode(`${dcterms}description`),
      literal(`A system of units formerly widely used in the UK and the rest of the English-speaking world. It includes the pound (lb), quarter (qt), hundredweight (cwt), and ton (ton); the foot (ft), yard (yd), and mile (mi); and the gallon (gal), British thermal unit (btu), etc. These units have been largely replaced by metric units, although Imperial units persist in some contexts. In January 2000 an EU regulation outlawing the sale of goods in Imperial measures was adopted into British law; an exception was made for the sale of beer and milk in pints. `, namedNode(`${rdf}HTML`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}IMPERIAL`),
      namedNode(`${qudt}abbreviation`),
      literal(`Imperial`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}IMPERIAL`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Imperial_units`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}IMPERIAL`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.oxfordreference.com/view/10.1093/acref/9780199234899.001.0001/acref-9780199234899-e-3147`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}IMPERIAL`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}IMPERIAL`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}IMPERIAL`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}IMPERIAL`),
      namedNode(`${rdfs}label`),
      literal(`Imperial System of Units`, 'en'),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${dcterms}description`),
      literal(`In physics, Planck units are physical units of measurement defined exclusively in terms of five universal physical constants listed below, in such a manner that these five physical constants take on the numerical value of 1 when expressed in terms of these units. Planck units elegantly simplify particular algebraic expressions appearing in physical law.  
Originally proposed in 1899 by German physicist Max Planck, these units are also known as natural units because the origin of their definition comes only from properties of nature and not from any human construct. Planck units are unique among systems of natural units, because they are not defined in terms of properties of any prototype, physical object, or even elementary particle.
Unlike the meter and second, which exist as fundamental units in the SI system for (human) historical reasons, the Planck length and Planck time are conceptually linked at a fundamental physical level. Natural units help physicists to reframe questions.`, namedNode(`${rdf}HTML`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${qudt}abbreviation`),
      literal(`PLANCK`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/Planck_units`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}PlanckCharge`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}PlanckLength`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}PlanckMass`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}PlanckTemperature`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}PlanckTime`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://en.wikipedia.org/wiki/Planck_units?oldid=495407713`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}PLANCK`),
      namedNode(`${rdfs}label`),
      literal(`Planck System of Units`, 'en'),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${dcterms}description`),
      literal(`The International System of Units (abbreviated \\(SI\\) from French: Système international d'unités) is the modern form of the metric system and is generally a system of units of measurement devised around seven base units and the convenience of the number ten. The older metric system included several groups of units. The SI was established in 1960, based on the metre-kilogram-second system, rather than the centimetre-gram-second system, which, in turn, had a few variants.`, namedNode(`${rdf}HTML`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}abbreviation`),
      literal(`SI`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/International_System_of_Units`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}A`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}CD`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}K`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}KiloGM`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}M`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}MOL`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}SEC`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}hasBaseUnit`),
      namedNode(`${unit}UNITLESS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://aurora.regenstrief.org/~ucum/ucum.html`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://physics.info/system-international/`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://physics.nist.gov/Pubs/SP811`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.nist.gov/pml/pubs/sp811/index.cfm`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.oxfordreference.com/view/10.1093/acref/9780198605225.001.0001/acref-9780198605225-e-1292`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.oxfordreference.com/view/10.1093/acref/9780199233991.001.0001/acref-9780199233991-appendix-0003`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}informativeReference`),
      literal(`http://www.oxfordreference.com/view/10.1093/acref/9780199233991.001.0001/acref-9780199233991-e-2791`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}informativeReference`),
      literal(`https://www.govinfo.gov/content/pkg/GOVPUB-C13-f10c2ff9e7af2091314396a2d53213e4/pdf/GOVPUB-C13-f10c2ff9e7af2091314396a2d53213e4.pdf`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Atto`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Centi`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Deca`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Deci`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Exa`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Femto`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Giga`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Hecto`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Kilo`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Mega`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Micro`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Milli`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Nano`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Peta`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Pico`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Tera`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Yocto`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Yotta`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Zepto`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${qudt}prefix`),
      namedNode(`${ns10}Zetta`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SI`),
      namedNode(`${rdfs}label`),
      literal(`International System of Units`, 'en'),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_ASU`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_ASU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_ASU`),
      namedNode(`${rdfs}label`),
      literal(`Astronomical System of Units (deprecated URI)`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_ASU`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}ASU`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_ASU`),
      namedNode(`${owl}deprecated`),
      literal(`true`, namedNode(`${xsd}boolean`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-EMU`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-EMU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-EMU`),
      namedNode(`${rdfs}label`),
      literal(`CGS-EMU System of Units (deprecated URI)`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-EMU`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}CGS-EMU`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-EMU`),
      namedNode(`${owl}deprecated`),
      literal(`true`, namedNode(`${xsd}boolean`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-ESU`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-ESU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-ESU`),
      namedNode(`${rdfs}label`),
      literal(`CGS-ESU System of Units (deprecated URI)`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-ESU`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}CGS-ESU`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-ESU`),
      namedNode(`${owl}deprecated`),
      literal(`true`, namedNode(`${xsd}boolean`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-GAUSS`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-GAUSS`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-GAUSS`),
      namedNode(`${rdfs}label`),
      literal(`CGS-Gauss System of Units (deprecated URI)`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-GAUSS`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}CGS-GAUSS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS-GAUSS`),
      namedNode(`${owl}deprecated`),
      literal(`true`, namedNode(`${xsd}boolean`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS`),
      namedNode(`${rdfs}label`),
      literal(`CGS System of Units (deprecated URI)`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}CGS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_CGS`),
      namedNode(`${owl}deprecated`),
      literal(`true`, namedNode(`${xsd}boolean`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_IMPERIAL`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_IMPERIAL`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_IMPERIAL`),
      namedNode(`${rdfs}label`),
      literal(`Imperial System of Units (deprecated URI)`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_IMPERIAL`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}IMPERIAL`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_IMPERIAL`),
      namedNode(`${owl}deprecated`),
      literal(`true`, namedNode(`${xsd}boolean`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_PLANCK`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_PLANCK`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_PLANCK`),
      namedNode(`${rdfs}label`),
      literal(`Planck System of Units (deprecated URI)`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_PLANCK`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}PLANCK`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_PLANCK`),
      namedNode(`${owl}deprecated`),
      literal(`true`, namedNode(`${xsd}boolean`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_SI`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_SI`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_SI`),
      namedNode(`${rdfs}label`),
      literal(`SI System of Units (deprecated URI)`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_SI`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}SI`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_SI`),
      namedNode(`${owl}deprecated`),
      literal(`true`, namedNode(`${xsd}boolean`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_USCS`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_USCS`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_USCS`),
      namedNode(`${rdfs}label`),
      literal(`US Customary System of Units (deprecated URI)`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_USCS`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${sou}USCS`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}SOU_USCS`),
      namedNode(`${owl}deprecated`),
      literal(`true`, namedNode(`${xsd}boolean`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}USCS`),
      namedNode(`${dcterms}description`),
      literal(`United States customary units are a system of measurements commonly used in the United States. Many U.S. units are virtually identical to their imperial counterparts, but the U.S. customary system developed from English units used in the British Empire before the system of imperial units was standardized in 1824. Several numerical differences from the imperial system are present. The vast majority of U.S. customary units have been defined in terms of the meter and the kilogram since the Mendenhall Order of 1893 (and, in practice, for many years before that date). These definitions were refined in 1959. The United States is the only industrialized nation that does not mainly use the metric system in its commercial and standards activities, although the International System of Units (SI, often referred to as "metric") is commonly used in the U.S. Armed Forces, in fields relating to science, and increasingly in medicine, aviation, and government as well as various sectors of industry. [Wikipedia]`, namedNode(`${rdf}HTML`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}USCS`),
      namedNode(`${qudt}abbreviation`),
      literal(`US Customary`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}USCS`),
      namedNode(`${qudt}dbpediaMatch`),
      literal(`http://dbpedia.org/resource/United_States_customary_units`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}USCS`),
      namedNode(`${vaem}url`),
      literal(`http://en.wikipedia.org/wiki/US_customary_units`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}USCS`),
      namedNode(`${rdf}type`),
      namedNode(`${qudt}SystemOfUnits`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}USCS`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}USCS`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${sou}USCS`),
      namedNode(`${rdfs}label`),
      literal(`US Customary Unit System`, 'en'),
      namedNode(sou)
    ),
    quad(
      namedNode(`${ns3}sou`),
      namedNode(`${vaem}hasGraphMetadata`),
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${ns3}sou`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${ns3}sou`),
      namedNode(`${rdfs}label`),
      literal(`QUDT Vocabulary - Systems of Units - v2.1.25`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${ns3}sou`),
      namedNode(`${owl}imports`),
      namedNode(`${ns13}qudt`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${ns3}sou`),
      namedNode(`${owl}versionInfo`),
      literal(`Created with TopBraid Composer`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${dcterms}contributor`),
      literal(`Jack Hodges`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${dcterms}contributor`),
      literal(`Steve Ray`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${dcterms}created`),
      literal(`2016-07-04`, namedNode(`${xsd}date`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${dcterms}creator`),
      literal(`Ralph Hodgson`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${dcterms}description`),
      literal(`QUDT Systems of Units Vocabulary Version 2.1.25`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${dcterms}modified`),
      literal(`2023-03-02T12:21:27.982-05:00`, namedNode(`${xsd}dateTime`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${dcterms}rights`),
      literal(`The QUDT Ontologies are issued under a Creative Commons Attribution 4.0 International License (CC BY 4.0), available at https://creativecommons.org/licenses/by/4.0/. Attribution should be made to QUDT.org`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${dcterms}subject`),
      literal(`Systems of Units`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${dcterms}title`),
      literal(`QUDT Systems of Units Ontology Version 2.1.25`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}graphTitle`),
      literal(`Systems of Units Ontology Version 2.1.25`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}hasGraphRole`),
      namedNode(`${vaem}VocabularyGraph`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}hasOwner`),
      namedNode(`${vaem}QUDT`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}hasSteward`),
      namedNode(`${vaem}QUDT`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}intent`),
      literal(`The intent of this graph is the specification of all Systems of Units`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}isMetadataFor`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}latestPublishedVersion`),
      literal(`https://qudt.org/doc/2023/03/DOC_VOCAB-SYSTEMS-OF-UNITS-v2.1.html`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}logo`),
      literal(`https://qudt.org/linkedmodels.org/assets/lib/lm/images/logos/qudt_logo-300x110.png`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}name`),
      literal(`sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}namespace`),
      literal(`http://qudt.org/vocab/sou/`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}namespacePrefix`),
      literal(`sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}owner`),
      literal(`qudt.org`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}previousPublishedVersion`),
      literal(`https://qudt.org/doc/2023/01/DOC_VOCAB-SYSTEMS-OF-UNITS-v2.1.html`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}revision`),
      literal(`2.1`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}turtleFileURL`),
      literal(`http://qudt.org/2.1/vocab/sou`, namedNode(`${xsd}anyURI`)),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${prov}wasInfluencedBy`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${prov}wasInformedBy`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphMetaData`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns3}sou`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${rdfs}label`),
      literal(`QUDT Systems of Units Ontology Version 2.1.25`),
      namedNode(sou)
    ),
    quad(
      namedNode(`${vaem}GMD_QUDT-SOU`),
      namedNode(`${owl}versionIRI`),
      namedNode(`${ns1}sou`),
      namedNode(sou)
    ),

  ]
}
