/* This file was automatically generated. Do not edit by hand. */

const {
  rdfs,
  dc11,
  rdf,
  owl,
  ns5
} = {
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'dc11': 'http://purl.org/dc/elements/1.1/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'ns5': 'http://www.w3.org/2000/01/'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(rdfs),
      namedNode(`${dc11}title`),
      literal(`The RDF Schema vocabulary (RDFS)`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(rdfs),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(rdfs),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns5}rdf-schema-more`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Class`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Class`),
      namedNode(`${rdfs}comment`),
      literal(`The class of classes.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Class`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Class`),
      namedNode(`${rdfs}label`),
      literal(`Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Class`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Container`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Container`),
      namedNode(`${rdfs}comment`),
      literal(`The class of RDF containers.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Container`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Container`),
      namedNode(`${rdfs}label`),
      literal(`Container`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Container`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}ContainerMembershipProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}ContainerMembershipProperty`),
      namedNode(`${rdfs}comment`),
      literal(`The class of container membership properties, rdf:_1, rdf:_2, ...,
                    all of which are sub-properties of 'member'.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}ContainerMembershipProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}ContainerMembershipProperty`),
      namedNode(`${rdfs}label`),
      literal(`ContainerMembershipProperty`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}ContainerMembershipProperty`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Datatype`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Datatype`),
      namedNode(`${rdfs}comment`),
      literal(`The class of RDF datatypes.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Datatype`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Datatype`),
      namedNode(`${rdfs}label`),
      literal(`Datatype`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Datatype`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Literal`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Literal`),
      namedNode(`${rdfs}comment`),
      literal(`The class of literal values, eg. textual strings and integers.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Literal`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Literal`),
      namedNode(`${rdfs}label`),
      literal(`Literal`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Literal`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Resource`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Resource`),
      namedNode(`${rdfs}comment`),
      literal(`The class resource, everything.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Resource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}Resource`),
      namedNode(`${rdfs}label`),
      literal(`Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}comment`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}comment`),
      namedNode(`${rdfs}comment`),
      literal(`A description of the subject resource.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}comment`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}comment`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}comment`),
      namedNode(`${rdfs}label`),
      literal(`comment`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}comment`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}domain`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}comment`),
      literal(`A domain of the subject property.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}label`),
      literal(`domain`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${rdfs}comment`),
      literal(`The defininition of the subject resource.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${rdfs}label`),
      literal(`isDefinedBy`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}label`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}label`),
      namedNode(`${rdfs}comment`),
      literal(`A human-readable name for the subject.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}label`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}label`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}label`),
      namedNode(`${rdfs}label`),
      literal(`label`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}label`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}member`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}member`),
      namedNode(`${rdfs}comment`),
      literal(`A member of the subject resource.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}member`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}member`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}member`),
      namedNode(`${rdfs}label`),
      literal(`member`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}member`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}comment`),
      literal(`A range of the subject property.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}label`),
      literal(`range`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${rdfs}comment`),
      literal(`Further information about the subject resource.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${rdfs}label`),
      literal(`seeAlso`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}comment`),
      literal(`The subject is a subclass of a class.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}label`),
      literal(`subClassOf`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Class`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}comment`),
      literal(`The subject is a subproperty of a property.`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(rdfs),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}label`),
      literal(`subPropertyOf`),
      namedNode(rdfs)
    ),
    quad(
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}Property`),
      namedNode(rdfs)
    ),

  ]
}
