/* This file was automatically generated. Do not edit by hand. */

const {
  foaf,
  dc11,
  rdf,
  owl,
  rdfs,
  ns6,
  ns7,
  ns8,
  ns9,
  ns10,
  ns11,
  vs,
  ns13,
  wgs
} = {
  'foaf': 'http://xmlns.com/foaf/0.1/',
  'dc11': 'http://purl.org/dc/elements/1.1/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'ns6': 'http://www.w3.org/2001/08/rdfweb/',
  'ns7': 'http://www.w3.org/2000/01/',
  'ns8': 'http://www.w3.org/2002/07/',
  'ns9': 'http://xmlns.com/wot/0.1/',
  'ns10': 'http://xmlns.com/foaf/',
  'ns11': 'http://xmlns.com/wordnet/1.6/',
  'vs': 'http://www.w3.org/2003/06/sw-vocab-status/ns#',
  'ns13': 'http://www.w3.org/2000/10/swap/pim/contact#',
  'wgs': 'http://www.w3.org/2003/01/geo/wgs84_pos#'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(foaf),
      namedNode(`${dc11}date`),
      literal(`$Date: 2004-08-18 00:31:33 $`),
      namedNode(foaf)
    ),
    quad(
      namedNode(foaf),
      namedNode(`${dc11}description`),
      literal(`The Friend of a Friend (FOAF) RDF vocabulary, described using W3C RDF Schema and the Web Ontology Language.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(foaf),
      namedNode(`${dc11}title`),
      literal(`Friend of a Friend (FOAF) vocabulary`),
      namedNode(foaf)
    ),
    quad(
      namedNode(foaf),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(foaf)
    ),
    quad(
      namedNode(foaf),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns6}foaf`),
      namedNode(foaf)
    ),
    quad(
      namedNode(foaf),
      namedNode(`${owl}imports`),
      namedNode(`${ns7}rdf-schema`),
      namedNode(foaf)
    ),
    quad(
      namedNode(foaf),
      namedNode(`${owl}imports`),
      namedNode(`${ns8}owl`),
      namedNode(foaf)
    ),
    quad(
      namedNode(foaf),
      namedNode(`${ns9}assurance`),
      namedNode(`${ns10}foafsig`),
      namedNode(foaf)
    ),
    quad(
      namedNode(foaf),
      namedNode(`${ns9}src_assurance`),
      namedNode(`${ns10}htmlfoafsig`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Agent`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Agent`),
      namedNode(`${rdfs}comment`),
      literal(`An agent (eg. person, group, software or physical artifact).`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Agent`),
      namedNode(`${rdfs}label`),
      literal(`Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Agent`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns11}Agent-3`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Agent`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Agent`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Document`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Document`),
      namedNode(`${rdfs}comment`),
      literal(`A document.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Document`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Document`),
      namedNode(`${rdfs}label`),
      literal(`Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Document`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns11}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Document`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Organization`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Document`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Document`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Project`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Document`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Group`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Group`),
      namedNode(`${rdfs}comment`),
      literal(`A class of Agents.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Group`),
      namedNode(`${rdfs}label`),
      literal(`Group`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Group`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Group`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Image`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Image`),
      namedNode(`${rdfs}comment`),
      literal(`An image.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Image`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Image`),
      namedNode(`${rdfs}label`),
      literal(`Image`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Image`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns11}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Image`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineAccount`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineAccount`),
      namedNode(`${rdfs}comment`),
      literal(`An online account.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineAccount`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineAccount`),
      namedNode(`${rdfs}label`),
      literal(`Online Account`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineAccount`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineChatAccount`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineChatAccount`),
      namedNode(`${rdfs}comment`),
      literal(`An online chat account.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineChatAccount`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineChatAccount`),
      namedNode(`${rdfs}label`),
      literal(`Online Chat Account`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineChatAccount`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns11}OnlineAccount`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineChatAccount`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineEcommerceAccount`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineEcommerceAccount`),
      namedNode(`${rdfs}comment`),
      literal(`An online e-commerce account.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineEcommerceAccount`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineEcommerceAccount`),
      namedNode(`${rdfs}label`),
      literal(`Online E-commerce Account`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineEcommerceAccount`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns11}OnlineAccount`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineEcommerceAccount`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineGamingAccount`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineGamingAccount`),
      namedNode(`${rdfs}comment`),
      literal(`An online gaming account.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineGamingAccount`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineGamingAccount`),
      namedNode(`${rdfs}label`),
      literal(`Online Gaming Account`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineGamingAccount`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns11}OnlineAccount`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}OnlineGamingAccount`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Organization`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Organization`),
      namedNode(`${rdfs}comment`),
      literal(`An organization.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Organization`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Organization`),
      namedNode(`${rdfs}label`),
      literal(`Organization`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Organization`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Organization`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns11}Organization`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Organization`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Organization`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Organization`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${rdfs}comment`),
      literal(`A person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${rdfs}label`),
      literal(`Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns13}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${wgs}SpatialThing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns11}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Organization`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Project`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Person`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}PersonalProfileDocument`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}PersonalProfileDocument`),
      namedNode(`${rdfs}comment`),
      literal(`A personal profile RDF document.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}PersonalProfileDocument`),
      namedNode(`${rdfs}label`),
      literal(`PersonalProfileDocument`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}PersonalProfileDocument`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}PersonalProfileDocument`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Project`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Project`),
      namedNode(`${rdfs}comment`),
      literal(`A project (a collective endeavour of some kind).`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Project`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Project`),
      namedNode(`${rdfs}label`),
      literal(`Project`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Project`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns11}Project`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Project`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Project`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}Project`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountName`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountName`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates the name (identifier) associated with this online account.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}OnlineAccount`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountName`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountName`),
      namedNode(`${rdfs}label`),
      literal(`account name`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountName`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountName`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountServiceHomepage`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountServiceHomepage`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates a homepage of the service provide for this online account.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountServiceHomepage`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}OnlineAccount`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountServiceHomepage`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountServiceHomepage`),
      namedNode(`${rdfs}label`),
      literal(`account service homepage`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountServiceHomepage`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}accountServiceHomepage`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}aimChatID`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}aimChatID`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}aimChatID`),
      namedNode(`${rdfs}comment`),
      literal(`An AIM chat ID`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}aimChatID`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}aimChatID`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}aimChatID`),
      namedNode(`${rdfs}label`),
      literal(`AIM chat ID`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}aimChatID`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}aimChatID`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${foaf}nick`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}aimChatID`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}based_near`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}based_near`),
      namedNode(`${rdfs}comment`),
      literal(`A location that something is based near, for some broadly human notion of near.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}based_near`),
      namedNode(`${rdfs}domain`),
      namedNode(`${wgs}SpatialThing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}based_near`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}based_near`),
      namedNode(`${rdfs}label`),
      literal(`based near`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}based_near`),
      namedNode(`${rdfs}range`),
      namedNode(`${wgs}SpatialThing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}based_near`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}currentProject`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}currentProject`),
      namedNode(`${rdfs}comment`),
      literal(`A current project this person works on.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}currentProject`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}currentProject`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}currentProject`),
      namedNode(`${rdfs}label`),
      literal(`current project`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}currentProject`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}currentProject`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depiction`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depiction`),
      namedNode(`${rdfs}comment`),
      literal(`A depiction of some thing.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depiction`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depiction`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depiction`),
      namedNode(`${rdfs}label`),
      literal(`depiction`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depiction`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Image`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depiction`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${foaf}depicts`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depiction`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depicts`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depicts`),
      namedNode(`${rdfs}comment`),
      literal(`A thing depicted in this representation.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depicts`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Image`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depicts`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depicts`),
      namedNode(`${rdfs}label`),
      literal(`depicts`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depicts`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depicts`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${foaf}depiction`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}depicts`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}dnaChecksum`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}dnaChecksum`),
      namedNode(`${rdfs}comment`),
      literal(`A checksum for the DNA of some thing. Joke.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}dnaChecksum`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}dnaChecksum`),
      namedNode(`${rdfs}label`),
      literal(`DNA checksum`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}dnaChecksum`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}dnaChecksum`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}family_name`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}family_name`),
      namedNode(`${rdfs}comment`),
      literal(`The family_name of some person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}family_name`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}family_name`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}family_name`),
      namedNode(`${rdfs}label`),
      literal(`family_name`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}family_name`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}family_name`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}firstName`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}firstName`),
      namedNode(`${rdfs}comment`),
      literal(`The first name of a person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}firstName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}firstName`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}firstName`),
      namedNode(`${rdfs}label`),
      literal(`firstName`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}firstName`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}firstName`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}fundedBy`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}fundedBy`),
      namedNode(`${rdfs}comment`),
      literal(`An organization funding a project or person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}fundedBy`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}fundedBy`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}fundedBy`),
      namedNode(`${rdfs}label`),
      literal(`funded by`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}fundedBy`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}fundedBy`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}geekcode`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}geekcode`),
      namedNode(`${rdfs}comment`),
      literal(`A textual geekcode for this person, see http://www.geekcode.com/geek.html`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}geekcode`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}geekcode`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}geekcode`),
      namedNode(`${rdfs}label`),
      literal(`geekcode`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}geekcode`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}geekcode`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}gender`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}gender`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}FunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}gender`),
      namedNode(`${rdfs}comment`),
      literal(`The gender of this Agent (typically but not necessarily 'male' or 'female').`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}gender`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}gender`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}gender`),
      namedNode(`${rdfs}label`),
      literal(`gender`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}gender`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}gender`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}givenname`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}givenname`),
      namedNode(`${rdfs}comment`),
      literal(`The given name of some person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}givenname`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}givenname`),
      namedNode(`${rdfs}label`),
      literal(`Given name`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}givenname`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}holdsAccount`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}holdsAccount`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates an account held by this agent.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}holdsAccount`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}holdsAccount`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}holdsAccount`),
      namedNode(`${rdfs}label`),
      literal(`holds account`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}holdsAccount`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}OnlineAccount`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}holdsAccount`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}homepage`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}homepage`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}homepage`),
      namedNode(`${rdfs}comment`),
      literal(`A homepage for some thing.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}homepage`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}homepage`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}homepage`),
      namedNode(`${rdfs}label`),
      literal(`homepage`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}homepage`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}homepage`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${foaf}page`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}homepage`),
      namedNode(`${vs}term_status`),
      literal(`stable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}icqChatID`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}icqChatID`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}icqChatID`),
      namedNode(`${rdfs}comment`),
      literal(`An ICQ chat ID`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}icqChatID`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}icqChatID`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}icqChatID`),
      namedNode(`${rdfs}label`),
      literal(`ICQ chat ID`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}icqChatID`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}icqChatID`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${foaf}nick`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}icqChatID`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}img`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}img`),
      namedNode(`${rdfs}comment`),
      literal(`An image that can be used to represent some thing (ie. those depictions which are particularly representative of something, eg. one's photo on a homepage).`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}img`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}img`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}img`),
      namedNode(`${rdfs}label`),
      literal(`image`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}img`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Image`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}img`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${foaf}depiction`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}img`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}interest`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}interest`),
      namedNode(`${rdfs}comment`),
      literal(`A page about a topic of interest to this person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}interest`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}interest`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}interest`),
      namedNode(`${rdfs}label`),
      literal(`interest`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}interest`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}interest`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}jabberID`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}jabberID`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}jabberID`),
      namedNode(`${rdfs}comment`),
      literal(`A jabber ID for something.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}jabberID`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}jabberID`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}jabberID`),
      namedNode(`${rdfs}label`),
      literal(`jabber ID`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}jabberID`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}jabberID`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${foaf}nick`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}jabberID`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}knows`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}knows`),
      namedNode(`${rdfs}comment`),
      literal(`A person known by this person (indicating some level of reciprocated interaction between the parties).`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}knows`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}knows`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}knows`),
      namedNode(`${rdfs}label`),
      literal(`knows`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}knows`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}knows`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}logo`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}logo`),
      namedNode(`${rdfs}comment`),
      literal(`A logo representing some thing.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}logo`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}logo`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}logo`),
      namedNode(`${rdfs}label`),
      literal(`logo`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}logo`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}logo`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}made`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}made`),
      namedNode(`${rdfs}comment`),
      literal(`Something that was made by this agent.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}made`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}made`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}made`),
      namedNode(`${rdfs}label`),
      literal(`made`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}made`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}made`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${foaf}maker`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}made`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}maker`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}maker`),
      namedNode(`${rdfs}comment`),
      literal(`An agent that made this thing.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}maker`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}maker`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}maker`),
      namedNode(`${rdfs}label`),
      literal(`maker`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}maker`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}maker`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${foaf}made`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}maker`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox`),
      namedNode(`${rdfs}comment`),
      literal(`A personal mailbox, ie. an Internet mailbox associated with exactly one owner, the first owner of this mailbox. This is a 'static inverse functional property', in that  there is (across time and change) at most one individual that ever has any particular value for foaf:mbox.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox`),
      namedNode(`${rdfs}label`),
      literal(`personal mailbox`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox_sha1sum`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox_sha1sum`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox_sha1sum`),
      namedNode(`${rdfs}comment`),
      literal(`The sha1sum of the URI of an Internet mailbox associated with exactly one owner, the  first owner of the mailbox.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox_sha1sum`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox_sha1sum`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox_sha1sum`),
      namedNode(`${rdfs}label`),
      literal(`sha1sum of a personal mailbox URI name`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox_sha1sum`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}mbox_sha1sum`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}member`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}member`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates a member of a Group`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}member`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Group`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}member`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}member`),
      namedNode(`${rdfs}label`),
      literal(`member`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}member`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}member`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}membershipClass`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}membershipClass`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates the class of individuals that are a member of a Group`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}membershipClass`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Group`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}membershipClass`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}membershipClass`),
      namedNode(`${rdfs}label`),
      literal(`membershipClass`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}membershipClass`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Class`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}membershipClass`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}msnChatID`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}msnChatID`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}msnChatID`),
      namedNode(`${rdfs}comment`),
      literal(`An MSN chat ID`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}msnChatID`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}msnChatID`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}msnChatID`),
      namedNode(`${rdfs}label`),
      literal(`MSN chat ID`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}msnChatID`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}msnChatID`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${foaf}nick`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}msnChatID`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}myersBriggs`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}myersBriggs`),
      namedNode(`${rdfs}comment`),
      literal(`A Myers Briggs (MBTI) personality classification.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}myersBriggs`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}myersBriggs`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}myersBriggs`),
      namedNode(`${rdfs}label`),
      literal(`myersBriggs`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}myersBriggs`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}myersBriggs`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}name`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}name`),
      namedNode(`${rdfs}comment`),
      literal(`A name for some thing.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}name`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}name`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}name`),
      namedNode(`${rdfs}label`),
      literal(`name`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}name`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}name`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}label`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}name`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}nick`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}nick`),
      namedNode(`${rdfs}comment`),
      literal(`A short informal nickname characterising an agent (includes login identifiers, IRC and other chat nicknames).`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}nick`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}nick`),
      namedNode(`${rdfs}label`),
      literal(`nickname`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}nick`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}page`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}page`),
      namedNode(`${rdfs}comment`),
      literal(`A page or document about this thing.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}page`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}page`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}page`),
      namedNode(`${rdfs}label`),
      literal(`page`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}page`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}page`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${foaf}topic`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}page`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}pastProject`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}pastProject`),
      namedNode(`${rdfs}comment`),
      literal(`A project this person has previously worked on.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}pastProject`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}pastProject`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}pastProject`),
      namedNode(`${rdfs}label`),
      literal(`past project`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}pastProject`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}pastProject`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}phone`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}phone`),
      namedNode(`${rdfs}comment`),
      literal(`A phone,  specified using fully qualified tel: URI scheme (refs: http://www.w3.org/Addressing/schemes.html#tel).`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}phone`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}phone`),
      namedNode(`${rdfs}label`),
      literal(`phone`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}phone`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}plan`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}plan`),
      namedNode(`${rdfs}comment`),
      literal(`A .plan comment, in the tradition of finger and '.plan' files.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}plan`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}plan`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}plan`),
      namedNode(`${rdfs}label`),
      literal(`plan`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}plan`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}plan`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}primaryTopic`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}primaryTopic`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}FunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}primaryTopic`),
      namedNode(`${rdfs}comment`),
      literal(`The primary topic of some page or document.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}primaryTopic`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}primaryTopic`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}primaryTopic`),
      namedNode(`${rdfs}label`),
      literal(`topic`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}primaryTopic`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}primaryTopic`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}publications`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}publications`),
      namedNode(`${rdfs}comment`),
      literal(`A link to the publications of this person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}publications`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}publications`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}publications`),
      namedNode(`${rdfs}label`),
      literal(`publications`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}publications`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}publications`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}schoolHomepage`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}schoolHomepage`),
      namedNode(`${rdfs}comment`),
      literal(`A homepage of a school attended by the person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}schoolHomepage`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}schoolHomepage`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}schoolHomepage`),
      namedNode(`${rdfs}label`),
      literal(`schoolHomepage`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}schoolHomepage`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}schoolHomepage`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}sha1`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}sha1`),
      namedNode(`${rdfs}comment`),
      literal(`A sha1sum hash, in hex.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}sha1`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}sha1`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}sha1`),
      namedNode(`${rdfs}label`),
      literal(`sha1sum (hex)`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}sha1`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}surname`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}surname`),
      namedNode(`${rdfs}comment`),
      literal(`The surname of some person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}surname`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}surname`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}surname`),
      namedNode(`${rdfs}label`),
      literal(`Surname`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}surname`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}surname`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}theme`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}theme`),
      namedNode(`${rdfs}comment`),
      literal(`A theme.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}theme`),
      namedNode(`${rdfs}domain`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}theme`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}theme`),
      namedNode(`${rdfs}label`),
      literal(`theme`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}theme`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}theme`),
      namedNode(`${vs}term_status`),
      literal(`unstable`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}thumbnail`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}thumbnail`),
      namedNode(`${rdfs}comment`),
      literal(`A derived thumbnail image.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}thumbnail`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Image`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}thumbnail`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}thumbnail`),
      namedNode(`${rdfs}label`),
      literal(`thumbnail`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}thumbnail`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Image`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}thumbnail`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}tipjar`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}tipjar`),
      namedNode(`${rdfs}comment`),
      literal(`A tipjar document for this agent, describing means for payment and reward.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}tipjar`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}tipjar`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}tipjar`),
      namedNode(`${rdfs}label`),
      literal(`tipjar`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}tipjar`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}tipjar`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${foaf}page`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}tipjar`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}title`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}title`),
      namedNode(`${rdfs}comment`),
      literal(`Title (Mr, Mrs, Ms, Dr. etc)`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}title`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}title`),
      namedNode(`${rdfs}label`),
      literal(`title`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}title`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic`),
      namedNode(`${rdfs}comment`),
      literal(`A topic of some page or document.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic`),
      namedNode(`${rdfs}label`),
      literal(`topic`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${foaf}page`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic_interest`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic_interest`),
      namedNode(`${rdfs}comment`),
      literal(`A thing of interest to this person.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic_interest`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic_interest`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic_interest`),
      namedNode(`${rdfs}label`),
      literal(`interest_topic`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic_interest`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}topic_interest`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}weblog`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}weblog`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}weblog`),
      namedNode(`${rdfs}comment`),
      literal(`A weblog of some thing (whether person, group, company etc.).`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}weblog`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}weblog`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}weblog`),
      namedNode(`${rdfs}label`),
      literal(`weblog`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}weblog`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}weblog`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${foaf}page`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}weblog`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workInfoHomepage`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workInfoHomepage`),
      namedNode(`${rdfs}comment`),
      literal(`A work info homepage of some person; a page about their work for some organization.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workInfoHomepage`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workInfoHomepage`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workInfoHomepage`),
      namedNode(`${rdfs}label`),
      literal(`work info homepage`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workInfoHomepage`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workInfoHomepage`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workplaceHomepage`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workplaceHomepage`),
      namedNode(`${rdfs}comment`),
      literal(`A workplace homepage of some person; the homepage of an organization they work for.`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workplaceHomepage`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Person`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workplaceHomepage`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workplaceHomepage`),
      namedNode(`${rdfs}label`),
      literal(`workplace homepage`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workplaceHomepage`),
      namedNode(`${rdfs}range`),
      namedNode(`${foaf}Document`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}workplaceHomepage`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}yahooChatID`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}yahooChatID`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}yahooChatID`),
      namedNode(`${rdfs}comment`),
      literal(`A Yahoo chat ID`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}yahooChatID`),
      namedNode(`${rdfs}domain`),
      namedNode(`${foaf}Agent`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}yahooChatID`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(foaf),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}yahooChatID`),
      namedNode(`${rdfs}label`),
      literal(`Yahoo chat ID`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}yahooChatID`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}yahooChatID`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${foaf}nick`),
      namedNode(foaf)
    ),
    quad(
      namedNode(`${foaf}yahooChatID`),
      namedNode(`${vs}term_status`),
      literal(`testing`),
      namedNode(foaf)
    ),

  ]
}
