/* This file was automatically generated. Do not edit by hand. */

const {
  dcterms,
  rdf,
  owl,
  vaem,
  rdfs,
  xsd,
  ns7,
  ns8,
  ns9,
  ns10
} = {
  'dcterms': 'http://purl.org/dc/terms/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'vaem': 'http://www.linkedmodel.org/schema/vaem#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'ns7': 'http://www.linkedmodel.org/2.0/schema/',
  'ns8': 'http://www.linkedmodel.org/schema/',
  'ns9': 'http://voag.linkedmodel.org/voag/',
  'ns10': 'http://voag.linkedmodel.org/vocab/'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 29; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(`${dcterms}abstract`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}abstract`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}abstract`),
      namedNode(`${rdfs}label`),
      literal(`abstract`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}abstract`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}author`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}author`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}author`),
      namedNode(`${rdfs}label`),
      literal(`author`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}author`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}contributor`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}contributor`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}contributor`),
      namedNode(`${rdfs}label`),
      literal(`contributor`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}contributor`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}created`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}created`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}created`),
      namedNode(`${rdfs}label`),
      literal(`created`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}created`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}date`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}creator`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}creator`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}creator`),
      namedNode(`${rdfs}label`),
      literal(`creator`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}creator`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}description`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}description`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}description`),
      namedNode(`${rdfs}label`),
      literal(`description`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}description`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}modified`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}modified`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}modified`),
      namedNode(`${rdfs}label`),
      literal(`modified`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}modified`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}date`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}replaces`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}replaces`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}replaces`),
      namedNode(`${rdfs}label`),
      literal(`replaces`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}replaces`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}rights`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}rights`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}rights`),
      namedNode(`${rdfs}label`),
      literal(`rights`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}rights`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}subject`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}subject`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}subject`),
      namedNode(`${rdfs}label`),
      literal(`subject`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}subject`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}title`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}title`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(dcterms),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}title`),
      namedNode(`${rdfs}label`),
      literal(`title`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${dcterms}title`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${ns7}vaem`),
      namedNode(`${vaem}hasGraphMetadata`),
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${ns7}vaem`),
      namedNode(`${owl}versionIRI`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Aspect`),
      namedNode(`${dcterms}description`),
      literal(`Aspect is used to distinguish among sets of features of a domain or subject area. The term is borrowed from "aspect-oriented" programming, where it is used to separate concerns. An ontology may be characterized by this dimension so as to parition features that are orthogonal. For example,  in a systems ontology there may be aspects for "structure", "function", "behavior" and "interface" or "interoperability". A viewpoint can be distinguished by "aspects". For example the "information viewpoint" of an application can be partitioned into separate graphs for the "security", "operational" and"data retention" aspects.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Aspect`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Aspect`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Aspect`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Aspect`),
      namedNode(`${rdfs}label`),
      literal(`Aspect Dimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Aspect`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${vaem}Dimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CatalogEntry`),
      namedNode(`${dcterms}description`),
      literal(`VAEM Governed Object class is a placeholder for concepts that are fully defined by the voag:GovernedObject concept hierarchy for building a catalog of ontologies and graphs`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CollectionGraph`),
      namedNode(`${dcterms}description`),
      literal(`A "vaem:CollectionGraph" is a graph that aggregates other graphs using "owl:imports" statements`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CollectionGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`COLLECTION`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CollectionGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CollectionGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CollectionGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CollectionGraph`),
      namedNode(`${rdfs}label`),
      literal(`Collection graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ConstraintsGraph`),
      namedNode(`${dcterms}description`),
      literal(`A "vaem:ConstraintsGraph" is a graph that holds SPIN constraints`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ConstraintsGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`CONSTRAINTS`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ConstraintsGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ConstraintsGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ConstraintsGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ConstraintsGraph`),
      namedNode(`${rdfs}label`),
      literal(`Constraints graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ControllersGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`CONTROLLERS`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ControllersGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ControllersGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ControllersGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ControllersGraph`),
      namedNode(`${rdfs}label`),
      literal(`Controllers graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CurationGraph`),
      namedNode(`${dcterms}description`),
      literal(`A "vaem:CurationGraph" is a graph to hold metadata that is needed to describe, govern and provision another graph. A curation graph will likely use VOAG and VAEM for this purpose. The property "vaem:curationGraph" is used to link to the graph (or graphs) being curated`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CurationGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`CURATION`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CurationGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CurationGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CurationGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}CurationGraph`),
      namedNode(`${rdfs}label`),
      literal(`Curation graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DataGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`DATA`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DataGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DataGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DataGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DataGraph`),
      namedNode(`${rdfs}label`),
      literal(`Data graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Dimension`),
      namedNode(`${dcterms}description`),
      literal(`A dimension identifies a separation of concens that serves as a way to categorize an ontology graph. In VAEM,  the notion of "Dimension" is partitioned into "Aspect", "Discipline", "Domain" and "Viewpoint". `),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Dimension`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Dimension`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Dimension`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Dimension`),
      namedNode(`${rdfs}label`),
      literal(`Domain`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Dimension`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}Thing`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Discipline`),
      namedNode(`${dcterms}description`),
      literal(`A discipline is a specific area of work or study. Examples of disciplines in the engineering domain are electrical engineering, mechanical engineering and, in the financial domain, risk assessment, investment analysis.  In VAEM, discipline is used as a dimension for characterizing an ontology graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Discipline`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Discipline`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Discipline`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Discipline`),
      namedNode(`${rdfs}label`),
      literal(`Discipline Dimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Discipline`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${vaem}Dimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DocumentationGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`DOC`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DocumentationGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DocumentationGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DocumentationGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}DocumentationGraph`),
      namedNode(`${rdfs}label`),
      literal(`Documentation graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Domain`),
      namedNode(`${dcterms}description`),
      literal(`A domain is a subject area of interest. Examples of domains are "enterprise", "process", "organization" and "system". In VAEM, "Domain" is used as a dimension for characterizing an ontology graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Domain`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Domain`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Domain`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Domain`),
      namedNode(`${rdfs}label`),
      literal(`Domain Dimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Domain`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${vaem}Dimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}FunctionsGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`FUNCTIONS`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}FunctionsGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}FunctionsGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}FunctionsGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}FunctionsGraph`),
      namedNode(`${rdfs}label`),
      literal(`Functions graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${dcterms}abstract`),
      literal(`VAEM stands for "Vocabulary for Attaching Essential Metadata". What VAEM regards as essential metadata is data about dates and times, confidentiality, and other characterisitic qualifiers of the ontology, but also references to where a ontology is documented and where to find ontology registration for governance, attribution and provenance. VAEM makes use of some properties from the DC terms vocabulary using the namespace prefix "dct". VAEM is OWL-DL compliant.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${dcterms}created`),
      literal(`2011-04-20`, namedNode(`${xsd}date`)),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${dcterms}modified`),
      literal(`2014-07-26`, namedNode(`${xsd}date`)),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${dcterms}title`),
      literal(`VAEM Version 2.0 Metadata`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}description`),
      literal(`VAEM stands for "Vocabulary for Attaching Essential Metadata". What VAEM regards as essential metadata is data about dates and times, confidentiality, and other characterisitic qualifiers of the ontology, but also references to where a ontology is documented and where to find ontology registration for governance, attribution and provenance. VAEM makes use of some properties from the DC terms vocabulary using the namespace prefix "dct". VAEM is OWL-DL compliant.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}hasGraphRole`),
      namedNode(`${vaem}SchemaGraph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}hasOwner`),
      namedNode(`${vaem}TopQuadrant`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}hasSteward`),
      namedNode(`${vaem}TopQuadrant`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}intent`),
      literal(`The purpose of VAEM is to provide, by import, a foundation for commonly needed resources for metadata on an ontology.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}latestPublishedVersion`),
      literal(`http://www.linkedmodel.org/doc/2014/SCHEMA_vaem-v2.0`, namedNode(`${xsd}anyURI`)),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}logo`),
      literal(`http://linkedmodel.org/lib/lm/images/logos/TopBraid-RDM-Graph-Logo.png`, namedNode(`${xsd}anyURI`)),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}name`),
      literal(`VAEM`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}namespace`),
      literal(`http://www.linkedmodel.org/schema/vaem#`, namedNode(`${xsd}anyURI`)),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}namespacePrefix`),
      literal(`vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}owner`),
      literal(`TopQuadrant, Inc.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}previousPublishedVersion`),
      literal(`http://linkedmodel.org/doc/vaem/1.2/`, namedNode(`${xsd}anyURI`)),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}rdfxmlFileURL`),
      literal(`http://www.linkedmodel.org/2.0/schema/SCHEMA_vaem-v2.0.rdf`, namedNode(`${xsd}anyURI`)),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}revision`),
      literal(`2.0`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}title`),
      literal(`Vocabulary for Attaching Essential Metadata (VAEM) - Version 2.0`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}turtleFileURL`),
      literal(`http://www.linkedmodel.org/2.0/schema/SCHEMA_vaem-v2.0.ttl`, namedNode(`${xsd}anyURI`)),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}abstract`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}author`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}created`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}modified`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}title`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${ns9}CC-SHAREALIKE_3PT0-US`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${vaem}withAttributionTo`),
      literal(`VAEM is issued under a Creative Commons Attribution Share Alike 3.0 United States License. Attribution should be made to TopQuadrant, Inc.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphMetaData`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(`${rdfs}label`),
      literal(`VAEM Schema Version 2.0 Metadata`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${dcterms}description`),
      literal(`"vaem:GraphMetaData" defines basic metadata for the registration and publishing of a graph.  For specificaiton of governance the vocabulary "VOAG" may be used.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}label`),
      literal(`Graph Metadata`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns10}voag`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}Thing`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[0],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[1],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[2],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[3],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[4],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[5],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[6],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[7],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[8],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[9],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[10],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[11],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[12],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[13],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[14],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[15],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[16],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[17],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[18],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[19],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[20],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[21],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[22],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphMetaData`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[23],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphRole`),
      namedNode(`${dcterms}description`),
      literal(`GraphRole is used to characterize how a graph of resources participates in an ontology set.  For example, a graph can be a schema, vocabulary, dataset, script, or ruleset`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphRole`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphRole`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphRole`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphRole`),
      namedNode(`${rdfs}label`),
      literal(`Graph role`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphRole`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}Thing`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphRole`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[24],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}GraphRole`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[25],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}LinkSetGraph`),
      namedNode(`${dcterms}description`),
      literal(`A "vaem:LinkSetGraph" is a graph that holds statements that specify links between resources`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}LinkSetGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`LINKSET`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}LinkSetGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}LinkSetGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}LinkSetGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}LinkSetGraph`),
      namedNode(`${rdfs}label`),
      literal(`Link Set graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}MappingGraph`),
      namedNode(`${dcterms}description`),
      literal(`A graph that specifies a transformation of a graph into another graph or graphs. Invariably this is a SPINMap graph using SPARQL Rules (SPIN) to express the transforms.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}MappingGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`MAPPINGS`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}MappingGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}MappingGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}MappingGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}MappingGraph`),
      namedNode(`${rdfs}label`),
      literal(`Mapping graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Party`),
      namedNode(`${dcterms}description`),
      literal(`A "Party" is a generalization for an actor that may be realized as a person, organizaiton or named role.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Party`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Party`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Party`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Party`),
      namedNode(`${rdfs}label`),
      literal(`Party`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Party`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${owl}Thing`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Party`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[26],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Party`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[27],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Party`),
      namedNode(`${rdfs}subClassOf`),
      blankNodes[28],
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ProxyGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`PROXY`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ProxyGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ProxyGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ProxyGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ProxyGraph`),
      namedNode(`${rdfs}label`),
      literal(`Proxy graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}RulesGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`RULES`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}RulesGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}RulesGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}RulesGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}RulesGraph`),
      namedNode(`${rdfs}label`),
      literal(`Rules Graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}SchemaGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`SCHEMA`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}SchemaGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}SchemaGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}SchemaGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}SchemaGraph`),
      namedNode(`${rdfs}label`),
      literal(`Schema graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ScriptGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`SCRIPT`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ScriptGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ScriptGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ScriptGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ScriptGraph`),
      namedNode(`${rdfs}label`),
      literal(`Script graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TopQuadrant`),
      namedNode(`${vaem}name`),
      literal(`TopQuadrant, Inc.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TopQuadrant`),
      namedNode(`${vaem}url`),
      literal(`http:/www.topquadrant.com`, namedNode(`${xsd}anyURI`)),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TopQuadrant`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}Party`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TopQuadrant`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TopQuadrant`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TopQuadrant`),
      namedNode(`${rdfs}label`),
      literal(`TopQuadrant`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TransformsGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`TRANSFORMS`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TransformsGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TransformsGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TransformsGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}TransformsGraph`),
      namedNode(`${rdfs}label`),
      literal(`Transforms graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ViewGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`VIEWS`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ViewGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ViewGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ViewGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ViewGraph`),
      namedNode(`${rdfs}label`),
      literal(`View graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Viewpoint`),
      namedNode(`${dcterms}description`),
      literal(`Viewpoint is used to denote how a set of resources, or an individual resource, is relevant to a context of use. The term "viewpoint" is adopted from the ISO RM-ODP specifications and its more recent use in enterprise architecture descriptions. The RM-ODP introducesd the concept of viewpoint to describe a system from a particular set of concerns. RM-ODP defines five viewpoints. Together they provide a complete description of a system: enterprise viewpoint, information viewpoint, computational viewpoint, engineering viewpoint, and technology viewpoint.  In VAEM, "Viewpoint" is used as a dimension for characterizing an ontology graph.  The viewpoints of an ontology may not always correpsond directly to those of a system but the idea of describing a subject area of interest from distinct viewpoints is still relevant. A viewpoint can be further distinguished by "aspects". For example the "information viewpoint" of an application can be partitioned into separate graphs for the "security", "operational" and"data retention" aspects.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Viewpoint`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Viewpoint`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Viewpoint`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Viewpoint`),
      namedNode(`${rdfs}label`),
      literal(`ViewpointDimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}Viewpoint`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${vaem}Dimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}VocabularyGraph`),
      namedNode(`${dcterms}description`),
      literal(`An RDF/OWL Graph that is a controlled set of instances.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}VocabularyGraph`),
      namedNode(`${vaem}filePrefix`),
      literal(`VOCAB`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}VocabularyGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}VocabularyGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}VocabularyGraph`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}VocabularyGraph`),
      namedNode(`${rdfs}label`),
      literal(`Vocabulary graph`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}abbreviation`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:abbreviation" provides a common way to define a commonly used abbreviation on a resource`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}abbreviation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}abbreviation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}abbreviation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}abbreviation`),
      namedNode(`${rdfs}label`),
      literal(`abbreviation`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}acronym`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:acronym" provides a common way to define a commonly used abbreviation on a resource`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}acronym`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}acronym`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}acronym`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}acronym`),
      namedNode(`${rdfs}label`),
      literal(`acronym`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}comment`),
      namedNode(`${dcterms}description`),
      literal(`An annotation property that can be freely used on any kind of resource. The range of the property is "xsd:string"`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}comment`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}comment`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}comment`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}comment`),
      namedNode(`${rdfs}label`),
      literal(`definition`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}comment`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}date`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:date" is intended for general use as the name implies.  The range of the property is set as "vaem:dateUnion" so as to allow a value to have a number of forms from a  year only to a full timestamp. The property is also the parent of all dates so that queries can be made for any date on an ontology`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}date`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}date`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}date`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}date`),
      namedNode(`${rdfs}label`),
      literal(`date`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}dateCreated`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:dateCreated" is intended for general use as the name implies.  The range of the property is set as "vaem:dateUnion" so as to allow a value to have a number of forms from a  year only to a full timestamp`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}description`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}description`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}description`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}description`),
      namedNode(`${rdfs}label`),
      literal(`description`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}description`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}filePrefix`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:filePrefix" is for specifying a preferred file prefix for a graph. For example a schema graph may be given the file prefix "SCHEMA" followed by an underscore "_".`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}filePrefix`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}filePrefix`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}filePrefix`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}filePrefix`),
      namedNode(`${rdfs}label`),
      literal(`file prefix`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}filePrefix`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasAspect`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:hasAspect" is used to distinguish among sets of features of a domain or subject area. The term is borrowed from "aspect-oriented" programming, where it is used to separate concerns. An ontology may be characterized by this dimension so as to parition features that are orthogonal. For example,  in a systems ontology we can distinguish aspects for "structure", "function", "behavior" and "interface".  The property is an "rdf:Property" to allow both scalar and object values`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasAspect`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasAspect`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasAspect`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasAspect`),
      namedNode(`${rdfs}label`),
      literal(`has aspect `),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasAspect`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${vaem}hasDimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDimension`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:hasDimension" is used categorize an ontology.  In VAEM, the property is used to characterize an ontology graph.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDimension`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDimension`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDimension`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDimension`),
      namedNode(`${rdfs}label`),
      literal(`has dimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDiscipline`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:hasDiscipline" is used to indicate relevance of a set of resources, or a resource itself, to a specific discipline of work or study. Examples of disciplines in the engineering domain are electrical engineering, mechanical engineering and, in the financial domain, risk assessment, investment analysis.  In VAEM, the property is used as a dimension for characterizing an ontology graph.  The property is an "rdf:Property" to allow both scalar and object values`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDiscipline`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDiscipline`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDiscipline`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDiscipline`),
      namedNode(`${rdfs}label`),
      literal(`has discipline`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDiscipline`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${vaem}hasDimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDomain`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:hasDomain" is used to specify how  a set of resources, or an individual resource is grounded in a domain, that is, a subject area of interest. Examples of domains are "enterprise", "process", "organization" and "system". In VAEM, the property is used as a dimension for characterizing an ontology graph. The property is an "rdf:Property" to allow both scalar and object values`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDomain`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDomain`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDomain`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDomain`),
      namedNode(`${rdfs}label`),
      literal(`has domain`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasDomain`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${vaem}hasDimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphMetadata`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphMetadata`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphMetadata`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphMetadata`),
      namedNode(`${rdfs}range`),
      namedNode(`${vaem}GraphMetaData`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphRole`),
      namedNode(`${dcterms}description`),
      literal(`The property "lms:hasGraphRole" is used to characterize how a resource participates in an ontology set.  The property is used to specify the role that a graph plays, for example, an ontology graph can be a schema, vocabulary, dataset, script, or ruleset`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphRole`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphRole`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphRole`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphRole`),
      namedNode(`${rdfs}label`),
      literal(`has graph role`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasGraphRole`),
      namedNode(`${rdfs}range`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasIdentifier`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaemhasIdentifier" is intended for general use as a means to specifiy a unique reference to something. This is an object property that is a sub-property of "vame:id"`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasIdentifier`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasIdentifier`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasIdentifier`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasIdentifier`),
      namedNode(`${rdfs}label`),
      literal(`has identifier`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasLicenseType`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:hasLicenseType" points to an entry in the VOAG ontology for licenses`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasLicenseType`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasLicenseType`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasLicenseType`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasLicenseType`),
      namedNode(`${rdfs}label`),
      literal(`has license type`, 'en-us'),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasMetadata`),
      namedNode(`${dcterms}description`),
      literal(`The property "hasMetadata" is used to reference a metadata information structure.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasMetadata`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasMetadata`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasMetadata`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasMetadata`),
      namedNode(`${rdfs}label`),
      literal(`has metadata`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasOwner`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasOwner`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasOwner`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasOwner`),
      namedNode(`${rdfs}label`),
      literal(`has owner`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasSteward`),
      namedNode(`${dcterms}description`),
      literal(`A property that is used to refer to a "Steward", that is, the party or role that is responsible for maintaining an asset, in the case of VAEM, an ontology graph.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasSteward`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasSteward`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasSteward`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasSteward`),
      namedNode(`${rdfs}label`),
      literal(`has steward`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasViewpoint`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:hasViewpoint" is used to denote how a set of resources, or an individual resource, is relevant to a context of use. The term "viewpoint" is adopted from the ISO RM-ODP specifications and its more recent use in enterprise architecture descriptions.  In VAEM, the property is used as a dimension for characterizing an ontology graph.  The property is an "rdf:Property" to allow both scalar and object values`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasViewpoint`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasViewpoint`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasViewpoint`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasViewpoint`),
      namedNode(`${rdfs}label`),
      literal(`has viewpoint`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}hasViewpoint`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${vaem}hasDimension`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}id`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:id" is intended for general use as a means to specifiy an identifier. The type of this property is intentionally set to "rdf:Property" so that use of the property can allow both object and scaler values.  For this reason, the property is rangeless`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}id`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}id`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}id`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}id`),
      namedNode(`${rdfs}label`),
      literal(`id`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}idString`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:idString" is intended for general use as a means to specifiy a unique reference to something. This is a data property with a string range and is a sub-property of "vame:id"`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}intent`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:intent" is used to outline  a statement of purpose. This typically expresses one or more desired outcomes`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}intent`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}intent`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}intent`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}intent`),
      namedNode(`${rdfs}label`),
      literal(`intent`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}intent`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}isElaboratedIn`),
      namedNode(`${dcterms}description`),
      literal(`An annotation used to reference a graph that elaborates (adds properties and axioms to) a resource`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}isElaboratedIn`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}isElaboratedIn`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}isElaboratedIn`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}isElaboratedIn`),
      namedNode(`${rdfs}label`),
      literal(`isDefinedBy`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}isElaboratedIn`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}isElaboratedIn`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}lastUpdated`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:lastUpdated" is intended for general use as the name implies.  The range of the property is set as "vaem:dateUnion" so as to allow a value to have a number of forms from a  year only to a full timestamp`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}latestPublishedVersion`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:latestPublishedVersion"is a URL to documentation for the latest version of a graph.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}latestPublishedVersion`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}latestPublishedVersion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}latestPublishedVersion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}latestPublishedVersion`),
      namedNode(`${rdfs}label`),
      literal(`latest published version`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}latestPublishedVersion`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}logo`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:logo" is a reference to an image that is used for publishing the ontology"`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}logo`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}logo`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}logo`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}logo`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}name`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:name" is intended for general use. In many cases "rdfs:label" could be used give names to resources. In the case where compliance with a specific naming rule is needed,  "vaem:name" allows  a resource to carry a name that is used in more specific contexts.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}name`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}name`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}name`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}name`),
      namedNode(`${rdfs}label`),
      literal(`name`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}name`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespace`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:namespace" is the onotlogy URI with which a graph is primarily associated. The intent is to allow multiple graphs to define statements for resources in the same Ontology namespace. For example, a foundation level graph with the base URI of "http://www.somesite.com/1.0/schema/OurOntology"  may define general  concepts for "OurOntology". Another graph with the base URI "http://www.somesite.com/1.0/schema/level2/OurOntology"  may add more specific details to the same "OurOntology". Each of these two graphs would carry the same value for "vaem:namespace", that is, "http://www.somesite.com/schema/OurOntology".    In other words, an ontology URI is the URI associated with the resources of a controlled namespace. On the other hand the graph URIs (the base URIs) identify the graphs that hold resources that make up an ontology`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespace`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespace`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespace`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespace`),
      namedNode(`${rdfs}label`),
      literal(`namespace`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespace`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespacePrefix`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:namespacePrefix" specifes a short handle or label for the URI of an Ontology.  Multiple graphs can define statements for resources in the same Ontololgy namespace. For example, a foundation level graph with the base URI of "http://www.somesite.com/1.0/schema/OurOntology"  may define general  concepts for "OurOntology". Another graph with the base URI "http://www.somesite.com/1.0/schema/level2/OurOntology"  may add more specific details to the same "OurOntology". Each of these two graphs would carry the same value for "vaem:namespacePrefix", for this example, perhaps, "ourOntology"`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespacePrefix`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespacePrefix`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespacePrefix`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespacePrefix`),
      namedNode(`${rdfs}label`),
      literal(`namespace prefix`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}namespacePrefix`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}ownedBy`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:ownedBy" is a general property that in some cases could have scalar values or may refer to some concept of "Party".  For this reason, the  type of this property is set as "rdf:Property" and the property is rangeless. There are two sub-properties of "vaem:ownedBy", namely "vaem:owner" for string values and "vaem:owningParty" for referencing a party.  Ownership applies to those ontologies that are proprietary`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}owner`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}owner`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}owner`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}owner`),
      namedNode(`${rdfs}label`),
      literal(`owner`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}owner`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}owningParty`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:owningParty" is used to refer to some concept of "Party" and is a sub-property of "vaem:ownedBy"`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}previousPublishedVersion`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:previousPublishedVersion"is a URL to documentation for the previous version of a graph.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}previousPublishedVersion`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}previousPublishedVersion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}previousPublishedVersion`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}previousPublishedVersion`),
      namedNode(`${rdfs}label`),
      literal(`previous published version`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}previousPublishedVersion`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rationale`),
      namedNode(`${dcterms}description`),
      literal(`A description of a justification for some other assertion or value`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rationale`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rationale`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rationale`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rationale`),
      namedNode(`${rdfs}label`),
      literal(`rationale`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rationale`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rdfxmlFileURL`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:rdfxmlFileURL" is used to provide a link to the location of the ontology's RDF/XML file`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rdfxmlFileURL`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rdfxmlFileURL`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rdfxmlFileURL`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rdfxmlFileURL`),
      namedNode(`${rdfs}label`),
      literal(`RDF/XML file URL`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}rdfxmlFileURL`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}reifiableBy`),
      namedNode(`${dcterms}description`),
      literal(`To express how statements in a model can be reifiable, this property is used to explicitly associate a property with a user-defined sub-class of "rdf:Statement". A recommended way of using this is to declare the properties that share the same reification constructs as sub-properties of a parent property that carries the "vaem:reifiableBy" property. The parent property should be of type "rdf:Property" so that it can have both datatype and object properties as sub-properties. By this means use and transformations of a model can be understood through a fully specified metamodel. "vaem:reifiableBy" is rangeless in order to comply with OWL DL semantics. Its range would have been rdfs:Class in order to refer to "rdf:Statement" sub-classes`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}reifiableBy`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}reifiableBy`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}reifiableBy`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}reifiableBy`),
      namedNode(`${rdfs}label`),
      literal(`reifiable by`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}releaseDate`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:releaseDate" is intended for general use as the name implies.  The range of the property is set as "vaem:dateUnion" so as to allow a value to have a number of forms from a  year only to a full timestamp`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}releaseDate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}releaseDate`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}releaseDate`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}releaseDate`),
      namedNode(`${rdfs}label`),
      literal(`release date`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}releaseDate`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${vaem}date`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}revision`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:revision" is a property intended for general use as the name implies.`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}revision`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}revision`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}revision`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}revision`),
      namedNode(`${rdfs}label`),
      literal(`revision`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}revision`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}specificity`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:specificity" is intended to specify the level of detail of an ontology.  The values that can be set for this property are restriced to an integer from 1 to 5. An ontology at level 1 has concepts of more general applicability than one at level 5. By having graphs at different levels of specificity it is possible to support greater modularity for selective imports`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}specificity`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}specificity`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}specificity`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}specificity`),
      namedNode(`${rdfs}label`),
      literal(`specificity`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}specificity`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}nonNegativeInteger`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}title`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}title`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}title`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}title`),
      namedNode(`${rdfs}label`),
      literal(`title`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}title`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}todo`),
      namedNode(`${dcterms}description`),
      literal(`As it name implies, a way to attach an annotation about a "todo" task`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}todo`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}todo`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}todo`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}todo`),
      namedNode(`${rdfs}label`),
      literal(`todo`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}todo`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}turtleFileURL`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:turtleFileURL" is used to provide a link to the location of the ontology's turtle file`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}turtleFileURL`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}turtleFileURL`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}turtleFileURL`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}turtleFileURL`),
      namedNode(`${rdfs}label`),
      literal(`turtle file URL`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}turtleFileURL`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}url`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:url" is intended for general use as the name implies.  The range of the property is set as an XSD URI`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}url`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}url`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}url`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}url`),
      namedNode(`${rdfs}label`),
      literal(`url`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}url`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:usesNonImportedResource" is used to express dependencies on resources from graphs that are not imported`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${rdfs}label`),
      literal(`uses non-imported resource`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}usesNonImportedResource`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}withAttributionTo`),
      namedNode(`${dcterms}description`),
      literal(`The property "vaem:withAttributionTo" is an annotation property that is either used to hold either a string or a reference to an instance of "voag:Attribution", from the VOAG ontology`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}withAttributionTo`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}withAttributionTo`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns7}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}withAttributionTo`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns8}vaem`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${vaem}withAttributionTo`),
      namedNode(`${rdfs}label`),
      literal(`with attribution to`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${ns8}vaem`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(vaem)
    ),
    quad(
      namedNode(`${owl}Ontology`),
      namedNode(`${vaem}hasGraphMetadata`),
      namedNode(`${vaem}GMD_VAEM`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[0],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[0],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[0],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}turtleFileURL`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[1],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[1],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[1],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasLicenseType`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[24],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[24],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[24],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}filePrefix`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[2],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[2],
      namedNode(`${owl}cardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[2],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}name`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[3],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[3],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[3],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}namespace`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[4],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[4],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[4],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasMetadata`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[5],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[5],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[5],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}namespacePrefix`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[26],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[26],
      namedNode(`${owl}cardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[26],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}name`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[27],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[27],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[27],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}id`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[6],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[6],
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${vaem}Discipline`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[6],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasDiscipline`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[7],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[7],
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${vaem}Party`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[7],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasSteward`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[8],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[8],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[8],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}latestPublishedVersion`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[25],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[25],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[25],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}description`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[9],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[9],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[9],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}specificity`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[10],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[10],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[10],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}intent`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[11],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[11],
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${vaem}GraphMetaData`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[11],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasMetadata`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[12],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[12],
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${vaem}Domain`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[12],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasDomain`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[13],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[13],
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${vaem}Aspect`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[13],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasAspect`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[14],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[14],
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${xsd}string`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[14],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}description`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[15],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[15],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[15],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}revision`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[16],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[16],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[16],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}owner`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[17],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[17],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[17],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasSteward`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[18],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[18],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[18],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasIdentifier`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[19],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[19],
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${vaem}GraphRole`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[19],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasGraphRole`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[20],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[20],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[20],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}previousPublishedVersion`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[21],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[21],
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${vaem}Party`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[21],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasOwner`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[28],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[28],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[28],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}url`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[22],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[22],
      namedNode(`${owl}maxCardinality`),
      literal(`1`, namedNode(`${xsd}nonNegativeInteger`)),
      namedNode(vaem)
    ),
    quad(
      blankNodes[22],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}rdfxmlFileURL`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[23],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[23],
      namedNode(`${owl}allValuesFrom`),
      namedNode(`${vaem}Viewpoint`),
      namedNode(vaem)
    ),
    quad(
      blankNodes[23],
      namedNode(`${owl}onProperty`),
      namedNode(`${vaem}hasViewpoint`),
      namedNode(vaem)
    ),

  ]
}
