/* This file was automatically generated. Do not edit by hand. */

const {
  og,
  rdf,
  rdfs,
  ns4,
  vcard,
  foaf,
  bibo,
  wgs,
  gr,
  dc11,
  xsd,
  owl
} = {
  'og': 'http://ogp.me/ns#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'ns4': 'http://ogp.me/ns/class#',
  'vcard': 'http://www.w3.org/2006/vcard/ns#',
  'foaf': 'http://xmlns.com/foaf/0.1/',
  'bibo': 'http://purl.org/ontology/bibo/',
  'wgs': 'http://www.w3.org/2003/01/geo/wgs84_pos#',
  'gr': 'http://purl.org/goodrelations/v1#',
  'dc11': 'http://purl.org/dc/elements/1.1/',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'owl': 'http://www.w3.org/2002/07/owl#'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 5; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(`${og}audio:album`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:album`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] An album to which some audio belongs.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:album`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:album`),
      namedNode(`${rdfs}label`),
      literal(`audio album`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:artist`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:artist`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] An artist of some audio.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:artist`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:artist`),
      namedNode(`${rdfs}label`),
      literal(`audio artist`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:secure_url`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:secure_url`),
      namedNode(`${rdfs}comment`),
      literal(`A relevant, secure audio URL for your object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:secure_url`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:secure_url`),
      namedNode(`${rdfs}label`),
      literal(`audio secure URL`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:secure_url`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}url`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:title`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:title`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] A title for some audio.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:title`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:title`),
      namedNode(`${rdfs}label`),
      literal(`audio title`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:type`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:type`),
      namedNode(`${rdfs}comment`),
      literal(`The mime type of an audio file e.g., "application/mp3"`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:type`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:type`),
      namedNode(`${rdfs}label`),
      literal(`audio type`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio:type`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}mime_type_str`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio`),
      namedNode(`${rdfs}comment`),
      literal(`A relevant audio URL for your object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio`),
      namedNode(`${rdfs}label`),
      literal(`audio`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}audio`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}url`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}country-name`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}country-name`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] The country name of the resource e.g., "USA"`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}country-name`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}country-name`),
      namedNode(`${rdfs}label`),
      literal(`country name`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}country-name`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${vcard}country-name`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}description`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}description`),
      namedNode(`${rdfs}comment`),
      literal(`A one to two sentence description of your object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}description`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}description`),
      namedNode(`${rdfs}label`),
      literal(`description`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}description`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}description`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}comment`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}determiner`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}determiner`),
      namedNode(`${rdfs}comment`),
      literal(`The word to precede the object's title in a sentence (e.g., "the" in "the statue of liberty").  Valid values are "a", "an", "the", "", and "auto".`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}determiner`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}determiner`),
      namedNode(`${rdfs}label`),
      literal(`determiner`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}determiner`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}determiner_str`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}email`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}email`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] Email of the contact for your object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}email`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}email`),
      namedNode(`${rdfs}label`),
      literal(`email`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}email`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${foaf}mbox`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}fax_number`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}fax_number`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] Fax number of the contact for your object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}fax_number`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}fax_number`),
      namedNode(`${rdfs}label`),
      literal(`fax number`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}fax_number`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${foaf}phone`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:height`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:height`),
      namedNode(`${rdfs}comment`),
      literal(`The height of an image.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:height`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:height`),
      namedNode(`${rdfs}label`),
      literal(`image height`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:height`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}integer_str`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:secure_url`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:secure_url`),
      namedNode(`${rdfs}comment`),
      literal(`A secure image URL which should represent your object within the graph.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:secure_url`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:secure_url`),
      namedNode(`${rdfs}label`),
      literal(`image secure url`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:secure_url`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}url`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:secure_url`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${foaf}depiction`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:type`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:type`),
      namedNode(`${rdfs}comment`),
      literal(`The mime type of an image.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:type`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:type`),
      namedNode(`${rdfs}label`),
      literal(`image type`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:type`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}mime_type_str`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:width`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:width`),
      namedNode(`${rdfs}comment`),
      literal(`The width of an image.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:width`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:width`),
      namedNode(`${rdfs}label`),
      literal(`image width`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image:width`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}integer_str`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image`),
      namedNode(`${rdfs}comment`),
      literal(`An image URL which should represent your object within the graph.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image`),
      namedNode(`${rdfs}label`),
      literal(`image`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}url`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}image`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${foaf}depiction`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}isbn`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}isbn`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] International Standard Book Number for you object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}isbn`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}isbn`),
      namedNode(`${rdfs}label`),
      literal(`International Standard Book Number`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}isbn`),
      namedNode(`${rdfs}label`),
      literal(`isbn`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}isbn`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${bibo}isbn`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}latitude`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}latitude`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] The latitude of the resource e.g., the latitude of a company.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}latitude`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}latitude`),
      namedNode(`${rdfs}label`),
      literal(`latitude`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}latitude`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${wgs}lat`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locale`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locale`),
      namedNode(`${rdfs}comment`),
      literal(`A Unix locale in which this markup is rendered.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locale`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locale`),
      namedNode(`${rdfs}label`),
      literal(`locale`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locale`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locality`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locality`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] The locality of the resource e.g, "Palo Alto"`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locality`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locality`),
      namedNode(`${rdfs}label`),
      literal(`locality`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}locality`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${vcard}locality`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}longitude`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}longitude`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] The longitude of the resource e.g., the longitude of a company.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}longitude`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}longitude`),
      namedNode(`${rdfs}label`),
      literal(`longitude`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}longitude`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${wgs}long`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}phone_number`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}phone_number`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] Phone number of the contact for your object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}phone_number`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}phone_number`),
      namedNode(`${rdfs}label`),
      literal(`phone number`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}phone_number`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${foaf}phone`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}postal-code`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}postal-code`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] The postal code of the resource e.g., "94304"`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}postal-code`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}postal-code`),
      namedNode(`${rdfs}label`),
      literal(`postal code`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}postal-code`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${vcard}postal-code`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}region`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}region`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] The region of the resource e.g., "CA"`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}region`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}region`),
      namedNode(`${rdfs}label`),
      literal(`region`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}region`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${vcard}region`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}site_name`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}site_name`),
      namedNode(`${rdfs}comment`),
      literal(`If your object is part of a larger web site, the name which should be displayed for the overall site. e.g., "IMDb".`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}site_name`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}site_name`),
      namedNode(`${rdfs}label`),
      literal(`site name`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}site_name`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}street-address`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}street-address`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] The street address of the resource e.g., "1601 S California Ave".`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}street-address`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}street-address`),
      namedNode(`${rdfs}label`),
      literal(`street address`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}street-address`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${vcard}street-address`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}title`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}title`),
      namedNode(`${rdfs}comment`),
      literal(`The title of the object as it should appear within the graph, e.g.,  "The Rock".`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}title`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}title`),
      namedNode(`${rdfs}label`),
      literal(`title`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}title`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}title`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}label`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}type`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}type`),
      namedNode(`${rdfs}comment`),
      literal(`The type of your object, e.g., "movie".  Depending on the type you specify, other properties may also be required.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}type`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}type`),
      namedNode(`${rdfs}label`),
      literal(`type`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}type`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}type`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${rdf}type`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}upc`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}upc`),
      namedNode(`${rdfs}comment`),
      literal(`[DEPRECATED] Universal Product Code for your object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}upc`),
      namedNode(`${rdfs}label`),
      literal(`universal product code`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}upc`),
      namedNode(`${rdfs}label`),
      literal(`upc`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}upc`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${gr}hasEAN_UCC-13`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}url`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}url`),
      namedNode(`${rdfs}comment`),
      literal(`The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}url`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}url`),
      namedNode(`${rdfs}label`),
      literal(`url`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}url`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}url`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}url`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${dc11}identifier`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}url`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${foaf}homepage`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:height`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:height`),
      namedNode(`${rdfs}comment`),
      literal(`The height of a video.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:height`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:height`),
      namedNode(`${rdfs}label`),
      literal(`video height`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:height`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}integer_str`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:secure_url`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:secure_url`),
      namedNode(`${rdfs}comment`),
      literal(`A relevant, secure video URL for your object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:secure_url`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:secure_url`),
      namedNode(`${rdfs}label`),
      literal(`video secure URL`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:secure_url`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}url`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:type`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:type`),
      namedNode(`${rdfs}comment`),
      literal(`The mime type of a video e.g., "application/x-shockwave-flash"`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:type`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:type`),
      namedNode(`${rdfs}label`),
      literal(`video type`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:type`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}mime_type_str`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:width`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:width`),
      namedNode(`${rdfs}comment`),
      literal(`The width of a video.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:width`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:width`),
      namedNode(`${rdfs}label`),
      literal(`video width`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video:width`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}integer_str`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video`),
      namedNode(`${rdfs}comment`),
      literal(`A relevant video URL for your object.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video`),
      namedNode(`${rdfs}label`),
      literal(`video`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${og}video`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns4}url`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}boolean_str`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}boolean_str`),
      namedNode(`${rdfs}comment`),
      literal(`A string representation of a true or false value.  The lexical space contains: "true", "false", "1", and "0".`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}boolean_str`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}boolean_str`),
      namedNode(`${rdfs}label`),
      literal(`boolean string`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}boolean_str`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${xsd}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}date_time_str`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}date_time_str`),
      namedNode(`${rdfs}comment`),
      literal(`A string representation of a temporal value composed of a date (year, month, day) and an optional time component (hours, minutes).  The lexical space is defined by ISO 8601.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}date_time_str`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}date_time_str`),
      namedNode(`${rdfs}label`),
      literal(`date/time string`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}date_time_str`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${xsd}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}determiner_str`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}determiner_str`),
      namedNode(`${rdfs}comment`),
      literal(`The lexical space: "", "the", "a", "an", and "auto".`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}determiner_str`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}determiner_str`),
      namedNode(`${rdfs}label`),
      literal(`determiner`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}determiner_str`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${xsd}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}determiner_str`),
      namedNode(`${owl}oneOf`),
      blankNodes[0],
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}float_str`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}float_str`),
      namedNode(`${rdfs}comment`),
      literal(`A string representation of a 64-bit signed floating point number.  Example lexical values include "1.234", "-1.234", "1.2e3", "-1.2e3", and "7E-10".`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}float_str`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}float_str`),
      namedNode(`${rdfs}label`),
      literal(`float string`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}float_str`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${xsd}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}integer_str`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}integer_str`),
      namedNode(`${rdfs}comment`),
      literal(`A string representation of a 32-bit signed integer.  Example lexical values include "1234" and "-123".`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}integer_str`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}integer_str`),
      namedNode(`${rdfs}label`),
      literal(`integer string`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}integer_str`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${xsd}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}mime_type_str`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}mime_type_str`),
      namedNode(`${rdfs}comment`),
      literal(`Valid mime type strings (e.g., "application/mp3").`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}mime_type_str`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(og),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}mime_type_str`),
      namedNode(`${rdfs}label`),
      literal(`mime type string`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}mime_type_str`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${xsd}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}string`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}string`),
      namedNode(`${rdfs}comment`),
      literal(`A string of Unicode characters.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}string`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}string`),
      namedNode(`${rdfs}label`),
      literal(`Unicode string`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}string`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${xsd}string`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}url`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Datatype`),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}url`),
      namedNode(`${rdfs}comment`),
      literal(`A string of Unicode characters forming a valid URL having the http or https scheme.`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}url`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns4),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}url`),
      namedNode(`${rdfs}label`),
      literal(`URL`, 'en-US'),
      namedNode(og)
    ),
    quad(
      namedNode(`${ns4}url`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns4}string`),
      namedNode(og)
    ),
    quad(
      blankNodes[1],
      namedNode(`${rdf}first`),
      literal(`an`),
      namedNode(og)
    ),
    quad(
      blankNodes[1],
      namedNode(`${rdf}rest`),
      blankNodes[2],
      namedNode(og)
    ),
    quad(
      blankNodes[0],
      namedNode(`${rdf}first`),
      literal(``),
      namedNode(og)
    ),
    quad(
      blankNodes[0],
      namedNode(`${rdf}rest`),
      blankNodes[3],
      namedNode(og)
    ),
    quad(
      blankNodes[4],
      namedNode(`${rdf}first`),
      literal(`a`),
      namedNode(og)
    ),
    quad(
      blankNodes[4],
      namedNode(`${rdf}rest`),
      blankNodes[1],
      namedNode(og)
    ),
    quad(
      blankNodes[2],
      namedNode(`${rdf}first`),
      literal(`auto`),
      namedNode(og)
    ),
    quad(
      blankNodes[2],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(og)
    ),
    quad(
      blankNodes[3],
      namedNode(`${rdf}first`),
      literal(`the`),
      namedNode(og)
    ),
    quad(
      blankNodes[3],
      namedNode(`${rdf}rest`),
      blankNodes[4],
      namedNode(og)
    ),

  ]
}
