/* This file was automatically generated. Do not edit by hand. */

const {
  dqv,
  rdf,
  rdfs,
  owl,
  skos,
  ns6,
  oa,
  vann,
  qb,
  ns10,
  duv,
  xsd,
  ns13,
  dcterms,
  ns15,
  ns16,
  ns17,
  foaf,
  ns19
} = {
  'dqv': 'http://www.w3.org/ns/dqv#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'skos': 'http://www.w3.org/2004/02/skos/core#',
  'ns6': 'http://purl.org/eis/vocab/daq#',
  'oa': 'http://www.w3.org/ns/oa#',
  'vann': 'http://purl.org/vocab/vann/',
  'qb': 'http://purl.org/linked-data/cube#',
  'ns10': 'http://www.w3.org/2004/03/trix/rdfg-1/',
  'duv': 'http://www.w3.org/ns/duv#',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'ns13': 'http://www.w3.org/ns/',
  'dcterms': 'http://purl.org/dc/terms/',
  'ns15': 'http://www.w3.org/data#',
  'ns16': 'http://purl.org/adms/assettype/',
  'ns17': 'http://purl.org/vocommons/voaf#',
  'foaf': 'http://xmlns.com/foaf/0.1/',
  'ns19': 'http://www.w3.org/TR/vocab-dqv/'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 11; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(`${dqv}Category`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Category`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Category`),
      namedNode(`${rdfs}comment`),
      literal(`Represents a group of quality dimensions in which a common type of information is used as quality indicator.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Category`),
      namedNode(`${rdfs}label`),
      literal(`Category`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Category`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${skos}Concept`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Category`),
      namedNode(`${owl}equivalentClass`),
      namedNode(`${ns6}Category`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Dimension`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Dimension`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Dimension`),
      namedNode(`${rdfs}comment`),
      literal(`Represents criteria relevant for assessing quality. Each quality dimension must have one or more metric to measure it. A dimension is linked with a category using the dqv:inCategory property.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Dimension`),
      namedNode(`${rdfs}label`),
      literal(`Dimension`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Dimension`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${skos}Concept`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Dimension`),
      namedNode(`${owl}equivalentClass`),
      namedNode(`${ns6}Dimension`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Metric`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Metric`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Metric`),
      namedNode(`${rdfs}comment`),
      literal(`Represents a standard to measure a quality dimension. An observation (instance of dqv:QualityMeasurement) assigns a value in a given unit to a Metric.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Metric`),
      namedNode(`${rdfs}label`),
      literal(`Metric`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}Metric`),
      namedNode(`${owl}equivalentClass`),
      namedNode(`${ns6}Metric`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityAnnotation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityAnnotation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityAnnotation`),
      namedNode(`${rdfs}comment`),
      literal(`Represents quality annotations, including ratings, quality certificates or feedback that can be associated to datasets or distributions. Quality annotations must have one oa:motivatedBy statement with an instance of oa:Motivation (and skos:Concept) that reflects a quality assessment purpose. We define this instance as dqv:qualityAssessment.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityAnnotation`),
      namedNode(`${rdfs}label`),
      literal(`Quality Annotation`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityAnnotation`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${oa}Annotation`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityAnnotation`),
      namedNode(`${owl}equivalentClass`),
      blankNodes[0],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityCertificate`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityCertificate`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityCertificate`),
      namedNode(`${rdfs}comment`),
      literal(`An annotation that associates a resource (especially, a dataset or a distribution) to another resource (for example, a document) that certifies the resource's quality according to a set of quality assessment rules.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityCertificate`),
      namedNode(`${rdfs}label`),
      literal(`Quality Certificate`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityCertificate`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${dqv}QualityAnnotation`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(`${vann}usageNote`),
      literal(`The unit of measure in quality measurement should be specified through the property sdmx-attribute:unitMeasure as recommended by RDF Data Cube. The Ontology of units of Measure (OM) by Rijgersberg Et Al provides a list of HTTP dereferenceable unit of measures, which can be exploited as values for sdmx-attribute:unitMeasure.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(`${rdfs}comment`),
      literal(`Represents the evaluation of a given dataset (or dataset distribution) against a specific quality metric.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(`${rdfs}label`),
      literal(`Quality Measurement`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${qb}Observation`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(`${owl}equivalentClass`),
      namedNode(`${ns6}Observation`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurementDataset`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurementDataset`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurementDataset`),
      namedNode(`${rdfs}comment`),
      literal(`Represents a dataset of quality measurements, evaluations of one or more datasets (or dataset distributions) against specific quality metrics.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurementDataset`),
      namedNode(`${rdfs}label`),
      literal(`Quality Measurement Dataset`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurementDataset`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${qb}DataSet`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMeasurementDataset`),
      namedNode(`${owl}equivalentClass`),
      namedNode(`${ns6}QualityGraph`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMetadata`),
      namedNode(`${vann}usageNote`),
      literal(`QualityMetadata containers do not necessary include all types of quality statements DQV can support. Implementers decide the granularity of containment. In the current version of DQV, we also leave open the choice of the containment technique. Implementers can use (RDF) graph containment. They may also use an appropriate property of their choice — for example (a subproperty of) dcterms:hasPart — to link instances of dqv:QualityMetadata with instances of other DQV classes.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMetadata`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMetadata`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMetadata`),
      namedNode(`${rdfs}comment`),
      literal(`Represents quality metadata, it is defined to group quality certificates, policies, measurements and annotations under a named graph.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMetadata`),
      namedNode(`${rdfs}label`),
      literal(`Quality Metadata`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityMetadata`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${ns10}Graph`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityPolicy`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityPolicy`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityPolicy`),
      namedNode(`${rdfs}comment`),
      literal(`Represents a policy or agreement that is chiefly governed by data quality concerns.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}QualityPolicy`),
      namedNode(`${rdfs}label`),
      literal(`Quality Policy`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}UserQualityFeedback`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}UserQualityFeedback`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}UserQualityFeedback`),
      namedNode(`${rdfs}comment`),
      literal(`Represents feedback that users have on the quality of datasets or distributions. Besides dqv:qualityAssessment, which is the motivation required by all quality annotations, one of the predefined instances of oa:Motivation should be indicated as motivation to distinguish among the different kinds of feedback, e.g., classifications, questions.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}UserQualityFeedback`),
      namedNode(`${rdfs}label`),
      literal(`User Quality feedback`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}UserQualityFeedback`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${dqv}QualityAnnotation`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}UserQualityFeedback`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${duv}UserFeedback`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}computedOn`),
      namedNode(`${rdf}type`),
      namedNode(`${qb}DimensionProperty`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}computedOn`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}computedOn`),
      namedNode(`${rdfs}comment`),
      literal(`Refers to the resource (e.g., a dataset, a linkset, a graph, a set of triples) on which the quality measurement is performed. In the DQV context, this property is generally expected to be used in statements in which objects are instances of dcat:Dataset or dcat:Distribution.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}computedOn`),
      namedNode(`${rdfs}domain`),
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}computedOn`),
      namedNode(`${rdfs}label`),
      literal(`computed on`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}computedOn`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Resource`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}computedOn`),
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${ns6}computedOn`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}computedOn`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${dqv}hasQualityMeasurement`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}expectedDataType`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}expectedDataType`),
      namedNode(`${rdfs}comment`),
      literal(`Represents the expected data type for metric's observed value (e.g. xsd:boolean, xsd:double etc...)`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}expectedDataType`),
      namedNode(`${rdfs}domain`),
      namedNode(`${dqv}Metric`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}expectedDataType`),
      namedNode(`${rdfs}label`),
      literal(`expected data type`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}expectedDataType`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anySimpleType`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}expectedDataType`),
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${ns6}expectedDataType`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityAnnotation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityAnnotation`),
      namedNode(`${rdfs}comment`),
      literal(`Refers to a quality annotation. Quality annotation can be applied to any kind of resource, e.g., a dataset, a linkset, a graph, a set of triples. However, in the DQV context, this property is generally expected to be used in statements in which subjects are instances of dcat:Dataset or dcat:Distribution.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityAnnotation`),
      namedNode(`${rdfs}label`),
      literal(`has quality annotation`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityAnnotation`),
      namedNode(`${rdfs}range`),
      namedNode(`${dqv}QualityAnnotation`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityAnnotation`),
      namedNode(`${rdfs}subPropertyOf`),
      blankNodes[1],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityMeasurement`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityMeasurement`),
      namedNode(`${rdfs}comment`),
      literal(`Refers to the performed quality measurements. Quality measurements can be performed to any kind of resource (e.g., a dataset, a linkset, a graph, a set of triples). However, in the DQV context, this property is generally expected to be used in statements in which subjects are instances of dcat:Dataset or dcat:Distribution.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityMeasurement`),
      namedNode(`${rdfs}label`),
      literal(`has quality measurement`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityMeasurement`),
      namedNode(`${rdfs}range`),
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityMeasurement`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${dqv}computedOn`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityMetadata`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityMetadata`),
      namedNode(`${rdfs}comment`),
      literal(`Refers to a grouping of quality information such as certificates, policies, measurements and annotations as a named graph. Quality information represented in such a grouping can pertain to any kind of resource (e.g., a dataset, a linkset, a graph, a set of triples). However, in the DQV context, this property is generally expected to be used in statements in which subjects are instances of dcat:Dataset or dcat:Distribution.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityMetadata`),
      namedNode(`${rdfs}label`),
      literal(`has quality metadata`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}hasQualityMetadata`),
      namedNode(`${rdfs}range`),
      namedNode(`${dqv}QualityMetadata`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inCategory`),
      namedNode(`${vann}usageNote`),
      literal(`Categories are meant to systematically organize dimensions. The Data Quality Vocabulary defines no specific cardinality constraints for dqv:inCategory, since distinct quality frameworks might have different perspectives over a dimension. A dimension may therefore be associated to more than one category. However, those who define new quality metrics should try to avoid this as much as possible and assign only one category to the dimensions they define.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inCategory`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inCategory`),
      namedNode(`${rdfs}comment`),
      literal(`Represents the category a dimension is grouped in.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inCategory`),
      namedNode(`${rdfs}domain`),
      namedNode(`${dqv}Dimension`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inCategory`),
      namedNode(`${rdfs}label`),
      literal(`in category`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inCategory`),
      namedNode(`${rdfs}range`),
      namedNode(`${dqv}Category`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inCategory`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${ns6}hasDimension`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inDimension`),
      namedNode(`${vann}usageNote`),
      literal(`Dimensions are meant to systematically organize metrics, quality certificates and quality annotations. The Data Quality Vocabulary defines no specific cardinality constraints for dqv:inDimension, since distinct quality frameworks might have different perspectives over a metric. A metric may therefore be associated to more than one dimension. However, those who define new quality metrics should try to avoid this as much as possible and assign only one dimension to the metrics they define. More than one dimension can be indicated for each quality annotation or certificate.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inDimension`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inDimension`),
      namedNode(`${rdfs}comment`),
      literal(`Represents the dimensions a quality metric, certificate and annotation allow a measurement of.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inDimension`),
      namedNode(`${rdfs}label`),
      literal(`in dimension`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}inDimension`),
      namedNode(`${rdfs}range`),
      namedNode(`${dqv}Dimension`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}isMeasurementOf`),
      namedNode(`${rdf}type`),
      namedNode(`${qb}DimensionProperty`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}isMeasurementOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}isMeasurementOf`),
      namedNode(`${rdfs}comment`),
      literal(`Indicates the metric being observed.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}isMeasurementOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${qb}Observation`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}isMeasurementOf`),
      namedNode(`${rdfs}label`),
      literal(`is measurement of`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}isMeasurementOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${dqv}Metric`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}isMeasurementOf`),
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${ns6}metric`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}precision`),
      namedNode(`${rdf}type`),
      namedNode(`${dqv}Dimension`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}precision`),
      namedNode(`${skos}definition`),
      literal(`Precision is a quality dimension, which refers to the recorded level of details. It represents the exactness of a measurement or description. It is equivalent the notion of Precision from ISO 25012.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}precision`),
      namedNode(`${skos}prefLabel`),
      literal(`Precision`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}qualityAssessment`),
      namedNode(`${vann}usageNote`),
      literal(`Whenever DQV implementers need to extend the motivations for quality annotations, they should follow the instructions provided by the Web Annotation Data Model, and the concepts in the extension should be defined as specializations of dqv:qualityAssessment.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}qualityAssessment`),
      namedNode(`${rdf}type`),
      namedNode(`${oa}Motivation`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}qualityAssessment`),
      namedNode(`${skos}broader`),
      namedNode(`${oa}assessing`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}qualityAssessment`),
      namedNode(`${skos}definition`),
      literal(`Motivation that must be specified for quality annotations.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}qualityAssessment`),
      namedNode(`${skos}prefLabel`),
      literal(`Quality assessment`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}value`),
      namedNode(`${rdf}type`),
      namedNode(`${qb}MeasureProperty`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}value`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}value`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}value`),
      namedNode(`${rdfs}comment`),
      literal(`Refers to values computed by metric.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}value`),
      namedNode(`${rdfs}domain`),
      namedNode(`${dqv}QualityMeasurement`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}value`),
      namedNode(`${rdfs}label`),
      literal(`value`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${dqv}value`),
      namedNode(`${owl}equivalentProperty`),
      namedNode(`${ns6}value`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}contributor`),
      blankNodes[2],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}contributor`),
      blankNodes[3],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}contributor`),
      blankNodes[4],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}contributor`),
      blankNodes[5],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}contributor`),
      blankNodes[6],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}contributor`),
      blankNodes[7],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}created`),
      literal(`2015-12-17`, namedNode(`${xsd}date`)),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}creator`),
      blankNodes[8],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}creator`),
      blankNodes[9],
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}description`),
      literal(`The Data Quality Vocabulary (DQV) is seen as an extension to DCAT to cover the quality of the data, how frequently is it updated, whether it accepts user corrections, persistence commitments etc. When used by publishers, this vocabulary will foster trust in the data amongst developers.`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}modified`),
      literal(`2016-08-26`, namedNode(`${xsd}date`)),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}modified`),
      literal(`2016-12-15`, namedNode(`${xsd}date`)),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}publisher`),
      namedNode(`${ns15}W3C`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}title`),
      literal(`Data Quality Vocabulary`, 'en'),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${dcterms}type`),
      namedNode(`${ns16}Ontology`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${vann}preferredNamespacePrefix`),
      literal(`dqv`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${vann}preferredNamespaceUri`),
      literal(`http://www.w3.org/ns/dqv#`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${rdf}type`),
      namedNode(`${ns17}Vocabulary`),
      namedNode(dqv)
    ),
    quad(
      namedNode(`${ns13}dqv`),
      namedNode(`${foaf}homepage`),
      namedNode(ns19),
      namedNode(dqv)
    ),
    quad(
      blankNodes[2],
      namedNode(`${foaf}name`),
      literal(`Jeremy Debattista`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[3],
      namedNode(`${foaf}name`),
      literal(`Christophe Guéret`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[4],
      namedNode(`${foaf}name`),
      literal(`Makx Dekkers`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[5],
      namedNode(`${foaf}name`),
      literal(`Deirdre Lee`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[1],
      namedNode(`${owl}inverseOf`),
      namedNode(`${oa}hasTarget`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[0],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Restriction`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[0],
      namedNode(`${owl}hasValue`),
      namedNode(`${dqv}qualityAssessment`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[0],
      namedNode(`${owl}onProperty`),
      namedNode(`${oa}motivation`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[6],
      namedNode(`${foaf}name`),
      literal(`Amrapali Zaveri`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[8],
      namedNode(`${foaf}name`),
      literal(`Riccardo Albertoni`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[10],
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${dqv}inDimension`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[10],
      namedNode(`${owl}inverseOf`),
      namedNode(`${ns6}hasMetric`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[9],
      namedNode(`${foaf}name`),
      literal(`Antoine Isaac`),
      namedNode(dqv)
    ),
    quad(
      blankNodes[7],
      namedNode(`${foaf}name`),
      literal(`Nandana Mihindukulasooriya`),
      namedNode(dqv)
    ),

  ]
}
