/* This file was automatically generated. Do not edit by hand. */

const {
  sd,
  rdf,
  rdfs,
  owl,
  ns5
} = {
  'sd': 'http://www.w3.org/ns/sparql-service-description#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'ns5': 'http://www.w3.org/ns/formats/'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(`${sd}Aggregate`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Aggregate`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:Aggregate represents an aggregate that may be used in a SPARQL aggregate query (for instance in a HAVING clause or SELECT expression) besides the standard list of supported aggregates COUNT, SUM, MIN, MAX, AVG, GROUP_CONCAT, and SAMPLE.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Aggregate`),
      namedNode(`${rdfs}label`),
      literal(`Aggregate`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Aggregate`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}BasicFederatedQuery`),
      namedNode(`${rdf}type`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}BasicFederatedQuery`),
      namedNode(`${rdfs}comment`),
      literal(`sd:BasicFederatedQuery, when used as the object of the sd:feature property, indicates that the SPARQL service supports basic federated query using the SERVICE keyword as defined by SPARQL 1.1 Federation Extensions.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}BasicFederatedQuery`),
      namedNode(`${rdfs}label`),
      literal(`Basic Federated Query`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Dataset`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Dataset`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:Dataset represents a RDF Dataset comprised of a default graph and zero or more named graphs.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Dataset`),
      namedNode(`${rdfs}label`),
      literal(`Dataset`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Dataset`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sd}GraphCollection`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}DereferencesURIs`),
      namedNode(`${rdf}type`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}DereferencesURIs`),
      namedNode(`${rdfs}comment`),
      literal(`sd:DereferencesURIs, when used as the object of the sd:feature property, indicates that a SPARQL service will dereference URIs used in FROM/FROM NAMED and USING/USING NAMED clauses and use the resulting RDF in the dataset during query evaluation.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}DereferencesURIs`),
      namedNode(`${rdfs}label`),
      literal(`Dereferences URIs`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EmptyGraphs`),
      namedNode(`${rdf}type`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EmptyGraphs`),
      namedNode(`${rdfs}comment`),
      literal(`sd:EmptyGraphs, when used as the object of the sd:feature property, indicates that the underlying graph store supports empty graphs. A graph store that supports empty graphs MUST NOT remove graphs that are left empty after triples are removed from them.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EmptyGraphs`),
      namedNode(`${rdfs}label`),
      literal(`Empty Graphs`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EntailmentProfile`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EntailmentProfile`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:EntailmentProfile represents a profile of an entailment regime. An entailment profile MAY impose restrictions on what constitutes valid RDF with respect to entailment.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EntailmentProfile`),
      namedNode(`${rdfs}label`),
      literal(`Entailment Profile`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EntailmentProfile`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EntailmentRegime`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EntailmentRegime`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:EntailmentRegime represents an entailment regime used in basic graph pattern matching (as described by SPARQL 1.1 Query Language).`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EntailmentRegime`),
      namedNode(`${rdfs}label`),
      literal(`Entailment Regime`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}EntailmentRegime`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Feature`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Feature`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:Feature represents a feature of a SPARQL service. Specific types of features include functions, aggregates, languages, and entailment regimes and profiles. This document defines five instances of sd:Feature: sd:DereferencesURIs, sd:UnionDefaultGraph, sd:RequiresDataset, sd:EmptyGraphs, and sd:BasicFederatedQuery.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Feature`),
      namedNode(`${rdfs}label`),
      literal(`Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Function`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Function`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:Function represents a function that may be used in a SPARQL SELECT expression or a FILTER, HAVING, GROUP BY, ORDER BY, or BIND clause.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Function`),
      namedNode(`${rdfs}label`),
      literal(`Function`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Function`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Graph`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Graph`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:Graph represents the description of an RDF graph.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Graph`),
      namedNode(`${rdfs}label`),
      literal(`Graph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}GraphCollection`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}GraphCollection`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:GraphCollection represents a collection of zero or more named graph descriptions. Each named graph description belonging to an sd:GraphCollection MUST be linked with the sd:namedGraph predicate.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}GraphCollection`),
      namedNode(`${rdfs}label`),
      literal(`Graph Collection`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Language`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Language`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:Language represents one of the SPARQL languages, including specific configurations providing particular features or extensions. This document defines three instances of sd:Language: sd:SPARQL10Query, sd:SPARQL11Query, and sd:SPARQL11Update.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Language`),
      namedNode(`${rdfs}label`),
      literal(`Language`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Language`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}NamedGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}NamedGraph`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:NamedGraph represents a named graph having a name (via sd:name) and an optional graph description (via sd:graph).`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}NamedGraph`),
      namedNode(`${rdfs}label`),
      literal(`Named Graph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}RequiresDataset`),
      namedNode(`${rdf}type`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}RequiresDataset`),
      namedNode(`${rdfs}comment`),
      literal(`sd:RequiresDataset, when used as the object of the sd:feature property, indicates that the SPARQL service requires an explicit dataset declaration (based on either FROM/FROM NAMED clauses in a query, USING/USING NAMED clauses in an update, or the appropriate SPARQL Protocol parameters).`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}RequiresDataset`),
      namedNode(`${rdfs}label`),
      literal(`Requires Dataset`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}SPARQL10Query`),
      namedNode(`${rdf}type`),
      namedNode(`${sd}Language`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}SPARQL10Query`),
      namedNode(`${rdfs}comment`),
      literal(`sd:SPARQL10Query is an sd:Language representing the SPARQL 1.0 Query language.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}SPARQL10Query`),
      namedNode(`${rdfs}label`),
      literal(`SPARQL 1.0 Query`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}SPARQL11Query`),
      namedNode(`${rdf}type`),
      namedNode(`${sd}Language`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}SPARQL11Query`),
      namedNode(`${rdfs}comment`),
      literal(`sd:SPARQL11Query is an sd:Language representing the SPARQL 1.1 Query language.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}SPARQL11Query`),
      namedNode(`${rdfs}label`),
      literal(`SPARQL 1.1 Query`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}SPARQL11Update`),
      namedNode(`${rdf}type`),
      namedNode(`${sd}Language`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}SPARQL11Update`),
      namedNode(`${rdfs}comment`),
      literal(`sd:SPARQLUpdate is an sd:Language representing the SPARQL 1.1 Update language.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}SPARQL11Update`),
      namedNode(`${rdfs}label`),
      literal(`SPARQL 1.1 Update`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Service`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Service`),
      namedNode(`${rdfs}comment`),
      literal(`An instance of sd:Service represents a SPARQL service made available via the SPARQL Protocol.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}Service`),
      namedNode(`${rdfs}label`),
      literal(`Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}UnionDefaultGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}UnionDefaultGraph`),
      namedNode(`${rdfs}comment`),
      literal(`sd:UnionDefaultGraph, when used as the object of the sd:feature property, indicates that the default graph of the dataset used during query and update evaluation (when an explicit dataset is not specified) is comprised of the union of all the named graphs in that dataset.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}UnionDefaultGraph`),
      namedNode(`${rdfs}label`),
      literal(`Union Default Graph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}availableGraphs`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}availableGraphs`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service to a description of the graphs which are allowed in the construction of a dataset either via the SPARQL Protocol, with FROM/FROM NAMED clauses in a query, or with USING/USING NAMED in an update request, if the service limits the scope of dataset construction.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}availableGraphs`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}availableGraphs`),
      namedNode(`${rdfs}label`),
      literal(`available graph descriptions`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}availableGraphs`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}GraphCollection`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultDataset`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultDataset`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultDataset`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service to a description of the default dataset available when no explicit dataset is specified in the query, update request or via protocol parameters.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultDataset`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultDataset`),
      namedNode(`${rdfs}label`),
      literal(`default dataset description`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultDataset`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}Dataset`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultEntailmentRegime`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultEntailmentRegime`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service with a resource representing an entailment regime used for basic graph pattern matching. This property is intended for use when a single entailment regime by default applies to all graphs in the default dataset of the service. In situations where a different entailment regime applies to a specific graph in the dataset, the sd:entailmentRegime property should be used to indicate this fact in the description of that graph.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultEntailmentRegime`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultEntailmentRegime`),
      namedNode(`${rdfs}label`),
      literal(`default entailment regime`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultEntailmentRegime`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}EntailmentRegime`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultEntailmentRegime`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sd}feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultGraph`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Dataset to the description of its default graph.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultGraph`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Dataset`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultGraph`),
      namedNode(`${rdfs}label`),
      literal(`default graph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultGraph`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}Graph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultSupportedEntailmentProfile`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultSupportedEntailmentProfile`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service with a resource representing a supported profile of the default entailment regime (as declared by sd:defaultEntailmentRegime).`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultSupportedEntailmentProfile`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultSupportedEntailmentProfile`),
      namedNode(`${rdfs}label`),
      literal(`default supported entailment profile`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultSupportedEntailmentProfile`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}EntailmentProfile`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}defaultSupportedEntailmentProfile`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sd}feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}endpoint`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}endpoint`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}InverseFunctionalProperty`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}endpoint`),
      namedNode(`${rdfs}comment`),
      literal(`The SPARQL endpoint of an sd:Service that implements the SPARQL Protocol service. The object of the sd:endpoint property is an IRI.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}endpoint`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}endpoint`),
      namedNode(`${rdfs}label`),
      literal(`endpoint`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}entailmentRegime`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}entailmentRegime`),
      namedNode(`${rdfs}comment`),
      literal(`Relates a named graph description with a resource representing an entailment regime used for basic graph pattern matching over that graph.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}entailmentRegime`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}NamedGraph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}entailmentRegime`),
      namedNode(`${rdfs}label`),
      literal(`entailment regime`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}entailmentRegime`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}EntailmentRegime`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionAggregate`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionAggregate`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service to an aggregate that may be used in a SPARQL aggregate query (for instance in a HAVING clause or SELECT expression) besides the standard list of supported aggregates COUNT, SUM, MIN, MAX, AVG, GROUP_CONCAT, and SAMPLE`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionAggregate`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionAggregate`),
      namedNode(`${rdfs}label`),
      literal(`extension aggregate`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionAggregate`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}Aggregate`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionAggregate`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sd}feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionFunction`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionFunction`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service to a function that may be used in a SPARQL SELECT expression or a FILTER, HAVING, GROUP BY, ORDER BY, or BIND clause.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionFunction`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionFunction`),
      namedNode(`${rdfs}label`),
      literal(`extension function`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionFunction`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}Function`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}extensionFunction`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sd}feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}feature`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}feature`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service with a resource representing a supported feature.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}feature`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}feature`),
      namedNode(`${rdfs}label`),
      literal(`feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}feature`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}graph`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}graph`),
      namedNode(`${rdfs}comment`),
      literal(`Relates a named graph to its graph description.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}graph`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}NamedGraph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}graph`),
      namedNode(`${rdfs}label`),
      literal(`graph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}graph`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}Graph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}inputFormat`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}inputFormat`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service to a format that is supported for parsing RDF input; for example, via a SPARQL 1.1 Update LOAD statement, or when URIs are dereferenced in FROM/FROM NAMED/USING/USING NAMED clauses.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}inputFormat`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}inputFormat`),
      namedNode(`${rdfs}label`),
      literal(`input format`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}inputFormat`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns5}Format`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}languageExtension`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}languageExtension`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service to a resource representing an implemented extension to the SPARQL Query or Update language.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}languageExtension`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}languageExtension`),
      namedNode(`${rdfs}label`),
      literal(`language extension`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}languageExtension`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}languageExtension`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sd}feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}name`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}name`),
      namedNode(`${rdfs}comment`),
      literal(`Relates a named graph to the name by which it may be referenced in a FROM/FROM NAMED clause. The object of the sd:name property is an IRI.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}name`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}NamedGraph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}name`),
      namedNode(`${rdfs}label`),
      literal(`name`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}namedGraph`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}namedGraph`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:GraphCollection (or its subclass sd:Dataset) to the description of one of its named graphs. The description of such a named graph MUST include the sd:name property and MAY include the sd:graph property.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}namedGraph`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}GraphCollection`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}namedGraph`),
      namedNode(`${rdfs}label`),
      literal(`named graph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}namedGraph`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}NamedGraph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}propertyFeature`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}propertyFeature`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service to a resource representing an implemented feature that extends the SPARQL Query or Update language and that is accessed by using the named property.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}propertyFeature`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}propertyFeature`),
      namedNode(`${rdfs}label`),
      literal(`property feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}propertyFeature`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}Feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}propertyFeature`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sd}feature`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}resultFormat`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}resultFormat`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service to a format that is supported for serializing query results.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}resultFormat`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}resultFormat`),
      namedNode(`${rdfs}label`),
      literal(`result format`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}resultFormat`),
      namedNode(`${rdfs}range`),
      namedNode(`${ns5}Format`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedEntailmentProfile`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedEntailmentProfile`),
      namedNode(`${rdfs}comment`),
      literal(`Relates a named graph description with a resource representing a supported profile of the entailment regime (as declared by sd:entailmentRegime) used for basic graph pattern matching over that graph.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedEntailmentProfile`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}NamedGraph`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedEntailmentProfile`),
      namedNode(`${rdfs}label`),
      literal(`supported entailment profile`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedEntailmentProfile`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}EntailmentProfile`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedLanguage`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedLanguage`),
      namedNode(`${rdfs}comment`),
      literal(`Relates an instance of sd:Service to a SPARQL language (e.g. Query and Update) that it implements.`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedLanguage`),
      namedNode(`${rdfs}domain`),
      namedNode(`${sd}Service`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedLanguage`),
      namedNode(`${rdfs}label`),
      literal(`supported language`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedLanguage`),
      namedNode(`${rdfs}range`),
      namedNode(`${sd}Language`),
      namedNode(sd)
    ),
    quad(
      namedNode(`${sd}supportedLanguage`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${sd}feature`),
      namedNode(sd)
    ),

  ]
}
