export { default as prefixes } from './prefixes'
export { vocabularies, loadFile } from './vocabularies'
export { expand } from './expand'
export { shrink } from './shrink'
export { expandWithCheck } from './expandWithCheck'
