/* This file was automatically generated. Do not edit by hand. */

const {
  dcterms,
  rdf,
  owl,
  sosa,
  vann,
  ns6,
  schema,
  skos,
  time,
  xsd,
  ns11,
  ns12,
  rdfs,
  foaf
} = {
  'dcterms': 'http://purl.org/dc/terms/',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'sosa': 'http://www.w3.org/ns/sosa/',
  'vann': 'http://purl.org/vocab/vann/',
  'ns6': 'http://purl.org/vocommons/voaf#',
  'schema': 'http://schema.org/',
  'skos': 'http://www.w3.org/2004/02/skos/core#',
  'time': 'http://www.w3.org/2006/time#',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'ns11': 'http://www.opengeospatial.org/ogc/',
  'ns12': 'http://www.w3.org/Consortium/Legal/2015/',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'foaf': 'http://xmlns.com/foaf/0.1/'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 1; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(`${dcterms}created`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${dcterms}creator`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${dcterms}description`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${dcterms}license`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${dcterms}rights`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${dcterms}title`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${vann}preferredNamespacePrefix`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${vann}preferredNamespaceUri`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${ns6}Vocabulary`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${schema}domainIncludes`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${skos}definition`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${skos}example`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${skos}note`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${time}TemporalEntity`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${dcterms}created`),
      literal(`2017-04-17`, namedNode(`${xsd}date`)),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${dcterms}creator`),
      blankNodes[0],
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${dcterms}description`),
      literal(`This ontology is based on the SSN Ontology by the W3C Semantic Sensor Networks Incubator Group (SSN-XG), together with considerations from the W3C/OGC Spatial Data on the Web Working Group.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${dcterms}license`),
      namedNode(`${ns11}Software`),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${dcterms}license`),
      namedNode(`${ns12}copyright-software-and-document`),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${dcterms}rights`),
      literal(`Copyright 2017 W3C/OGC.`),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${dcterms}title`),
      literal(`Sensor, Observation, Sample, and Actuator (SOSA) Ontology`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${vann}preferredNamespacePrefix`),
      literal(`sosa`),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${vann}preferredNamespaceUri`),
      literal(`http://www.w3.org/ns/sosa/`),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${rdf}type`),
      namedNode(`${ns6}Vocabulary`),
      namedNode(sosa)
    ),
    quad(
      namedNode(sosa),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ActuatableProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ActuatableProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ActuatableProperty`),
      namedNode(`${rdfs}comment`),
      literal(`An actuatable quality (property, characteristic) of a FeatureOfInterest.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ActuatableProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ActuatableProperty`),
      namedNode(`${rdfs}label`),
      literal(`Actuatable Property`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ActuatableProperty`),
      namedNode(`${skos}definition`),
      literal(`An actuatable quality (property, characteristic) of a FeatureOfInterest.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ActuatableProperty`),
      namedNode(`${skos}example`),
      literal(`A window actuator acts by changing the state between a frame and a window. The ability of the window to be opened and closed is its ActuatableProperty.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuation`),
      namedNode(`${rdfs}comment`),
      literal(`An Actuation carries out an (Actuation) Procedure to change the state of the world using an Actuator.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuation`),
      namedNode(`${rdfs}label`),
      literal(`Actuation`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuation`),
      namedNode(`${skos}definition`),
      literal(`An Actuation carries out an (Actuation) Procedure to change the state of the world using an Actuator.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuation`),
      namedNode(`${skos}example`),
      literal(`The activity of automatically closing a window if the temperature in a room drops below 20 degree Celsius. The activity is the Actuation and the device that closes the window is the Actuator. The Procedure is the rule, plan, or specification that defines the conditions that triggers the Actuation, here a drop in temperature. `, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuator`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuator`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuator`),
      namedNode(`${rdfs}comment`),
      literal(`A device that is used by, or implements, an (Actuation) Procedure that changes the state of the world.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuator`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuator`),
      namedNode(`${rdfs}label`),
      literal(`Actuator`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuator`),
      namedNode(`${skos}definition`),
      literal(`A device that is used by, or implements, an (Actuation) Procedure that changes the state of the world.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Actuator`),
      namedNode(`${skos}example`),
      literal(`A window actuator for automatic window control, i.e., opening or closing the window.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(`${rdfs}comment`),
      literal(`The thing whose property is being estimated or calculated in the course of an Observation to arrive at a Result or whose property is being manipulated by an Actuator, or which is being sampled or transformed in an act of Sampling.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(`${rdfs}label`),
      literal(`Feature Of Interest`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(`${skos}definition`),
      literal(`The thing whose property is being estimated or calculated in the course of an Observation to arrive at a Result or whose property is being manipulated by an Actuator, or which is being sampled or transformed in an act of Sampling.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(`${skos}example`),
      literal(`When measuring the height of a tree, the height is the observed ObservableProperty, 20m may be the Result of the Observation, and the tree is the FeatureOfInterest. A window is a FeatureOfInterest for an automatic window control Actuator.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ObservableProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ObservableProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ObservableProperty`),
      namedNode(`${rdfs}comment`),
      literal(`An observable quality (property, characteristic) of a FeatureOfInterest.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ObservableProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ObservableProperty`),
      namedNode(`${rdfs}label`),
      literal(`Observable Property`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ObservableProperty`),
      namedNode(`${skos}definition`),
      literal(`An observable quality (property, characteristic) of a FeatureOfInterest.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}ObservableProperty`),
      namedNode(`${skos}example`),
      literal(`The height of a tree, the depth of a water body, or the temperature of a surface are examples of observable properties, while the value of a classic car is not (directly) observable but asserted.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Observation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Observation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Observation`),
      namedNode(`${rdfs}comment`),
      literal(`Act of carrying out an (Observation) Procedure to estimate or calculate a value of a property of a FeatureOfInterest. Links to a Sensor to describe what made the Observation and how; links to an ObservableProperty to describe what the result is an estimate of, and to a FeatureOfInterest to detail what that property was associated with.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Observation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Observation`),
      namedNode(`${rdfs}label`),
      literal(`Observation`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Observation`),
      namedNode(`${skos}definition`),
      literal(`Act of carrying out an (Observation) Procedure to estimate or calculate a value of a property of a FeatureOfInterest. Links to a Sensor to describe what made the Observation and how; links to an ObservableProperty to describe what the result is an estimate of, and to a FeatureOfInterest to detail what that property was associated with.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Observation`),
      namedNode(`${skos}example`),
      literal(`The activity of estimating the intensity of an Earthquake using the Mercalli intensity scale is an Observation as is measuring the moment magnitude, i.e., the energy released by said earthquake.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Platform`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Platform`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Platform`),
      namedNode(`${rdfs}comment`),
      literal(`A Platform is an entity that hosts other entities, particularly Sensors, Actuators, Samplers, and other Platforms.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Platform`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Platform`),
      namedNode(`${rdfs}label`),
      literal(`Platform`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Platform`),
      namedNode(`${skos}definition`),
      literal(`A Platform is an entity that hosts other entities, particularly Sensors, Actuators, Samplers, and other Platforms.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Platform`),
      namedNode(`${skos}example`),
      literal(`A post, buoy, vehicle, ship, aircraft, satellite, cell-phone, human or animal may act as platforms for (technical or biological) sensors or actuators.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Procedure`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Procedure`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Procedure`),
      namedNode(`${rdfs}comment`),
      literal(`A workflow, protocol, plan, algorithm, or computational method specifying how to make an Observation, create a Sample, or make a change to the state of the world (via an Actuator). A Procedure is re-usable, and might be involved in many Observations, Samplings, or Actuations. It explains the steps to be carried out to arrive at reproducible results.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Procedure`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Procedure`),
      namedNode(`${rdfs}label`),
      literal(`Procedure`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Procedure`),
      namedNode(`${skos}definition`),
      literal(`A workflow, protocol, plan, algorithm, or computational method specifying how to make an Observation, create a Sample, or make a change to the state of the world (via an Actuator). A Procedure is re-usable, and might be involved in many Observations, Samplings, or Actuations. It explains the steps to be carried out to arrive at reproducible results.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Procedure`),
      namedNode(`${skos}example`),
      literal(`The measured wind speed differs depending on the height of the sensor above the surface, e.g., due to friction. Consequently, procedures for measuring wind speed define a standard height for anemometers above ground, typically 10m for meteorological measures and 2m in Agrometeorology. This definition of height, sensor placement, and so forth are defined by the Procedure.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Procedure`),
      namedNode(`${skos}note`),
      literal(`Many observations may be created via the same Procedure, the same way as many tables are assembled using the same instructions (as information objects, not their concrete realization).`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Result`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Result`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Result`),
      namedNode(`${rdfs}comment`),
      literal(`The Result of an Observation, Actuation, or act of Sampling. To store an observation's simple result value one can use the hasSimpleResult property.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Result`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Result`),
      namedNode(`${rdfs}label`),
      literal(`Result`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Result`),
      namedNode(`${skos}definition`),
      literal(`The Result of an Observation, Actuation, or act of Sampling. To store an observation's simple result value one can use the hasSimpleResult property.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Result`),
      namedNode(`${skos}example`),
      literal(`The value 20 as the height of a certain tree together with the unit, e.g., Meter.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${rdfs}comment`),
      literal(`A Sample is the result from an act of Sampling.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${rdfs}comment`),
      literal(`Feature which is intended to be representative of a FeatureOfInterest on which Observations may be made.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${rdfs}comment`),
      literal(`Physical samples are sometimes known as 'specimens'.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${rdfs}comment`),
      literal(`Samples are artifacts of an observational strategy, and have no significant function outside of their role in the observation process. The characteristics of the samples themselves are of little interest, except perhaps to the manager of a sampling campaign.

A Sample is intended to sample some FatureOfInterest, so there is an expectation of at least one isSampleOf property. However, in some cases the identity, and even the exact type, of the sampled feature may not be known when observations are made using the sampling features.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${rdfs}label`),
      literal(`Sample`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${skos}definition`),
      literal(`Feature which is intended to be representative of a FeatureOfInterest on which Observations may be made.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${skos}example`),
      literal(`A 'station' is essentially an identifiable locality where a sensor system or Procedure may be deployed and an observation made. In the context of the observation model, it connotes the 'world in the vicinity of the station', so the observed properties relate to the physical medium at the station, and not to any physical artifact such as a mooring, buoy, benchmark, monument, well, etc.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${skos}example`),
      literal(`A statistical sample is often designed to be characteristic of an entire population, so that observations can be made regarding the sample that provide a good estimate of the properties of the population.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sample`),
      namedNode(`${skos}note`),
      literal(`A transient sample, such as a ships-track or flight-line, might be identified and described, but is unlikely to be revisited exactly.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampler`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampler`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampler`),
      namedNode(`${rdfs}comment`),
      literal(`A device that is used by, or implements, a Sampling Procedure to create or transform one or more samples.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampler`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampler`),
      namedNode(`${rdfs}label`),
      literal(`Sampler`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampler`),
      namedNode(`${skos}definition`),
      literal(`A device that is used by, or implements, a Sampling Procedure to create or transform one or more samples.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampler`),
      namedNode(`${skos}example`),
      literal(`A ball mill, diamond drill, hammer, hypodermic syringe and needle, image Sensor or a soil auger can all act as sampling devices (i.e., be Samplers). However, sometimes the distinction between the Sampler and the Sensor is not evident, as they are packaged as a unit. A Sampler need not be a physical device.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${rdfs}comment`),
      literal(`An act of Sampling carries out a sampling Procedure to create or transform one or more samples.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${rdfs}label`),
      literal(`Sampling`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}definition`),
      literal(`An act of Sampling carries out a sampling Procedure to create or transform one or more samples.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Crushing a rock sample in a ball mill.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Digging a pit through a soil sequence.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Dividing a field site into quadrants.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Drawing blood from a patient.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Drilling an observation well.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Establishing a station for environmental monitoring.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Registering an image of the landscape.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Selecting a subset of a population.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Sieving a powder to separate the subset finer than 100-mesh.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Splitting a piece of drill-core to create two new samples.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sampling`),
      namedNode(`${skos}example`),
      literal(`Taking a diamond-drill core from a rock outcrop.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sensor`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sensor`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sensor`),
      namedNode(`${rdfs}comment`),
      literal(`Device, agent (including humans), or software (simulation) involved in, or implementing, a Procedure. Sensors respond to a stimulus, e.g., a change in the environment, or input data composed from the results of prior Observations, and generate a Result. Sensors can be hosted by Platforms.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sensor`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sensor`),
      namedNode(`${rdfs}label`),
      literal(`Sensor`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sensor`),
      namedNode(`${skos}definition`),
      literal(`Device, agent (including humans), or software (simulation) involved in, or implementing, a Procedure. Sensors respond to a stimulus, e.g., a change in the environment, or input data composed from the results of prior Observations, and generate a Result. Sensors can be hosted by Platforms.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}Sensor`),
      namedNode(`${skos}example`),
      literal(`Accelerometers, gyroscopes, barometers, magnetometers, and so forth are Sensors that are typically mounted on a modern smart phone (which acts as Platform). Other examples of sensors include the human eyes.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}actsOnProperty`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}actsOnProperty`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}ActuatableProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}actsOnProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}actsOnProperty`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between an Actuation and the property of a FeatureOfInterest it is acting upon.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}actsOnProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}actsOnProperty`),
      namedNode(`${rdfs}label`),
      literal(`acts on property`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}actsOnProperty`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}isActedOnBy`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}actsOnProperty`),
      namedNode(`${skos}definition`),
      literal(`Relation between an Actuation and the property of a FeatureOfInterest it is acting upon.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}actsOnProperty`),
      namedNode(`${skos}example`),
      literal(`In the activity (Actuation) of automatically closing a window if the temperature in a room drops below 20 degrees Celsius, the property on which the Actuator acts upon is the state of the window as it changes from being open to being closed. `, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sample`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${rdfs}comment`),
      literal(`A relation between an Observation and the entity whose quality was observed, or between an Actuation and the entity whose property was modified, or between an act of Sampling and the entity that was sampled.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${rdfs}label`),
      literal(`has feature of interest`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${skos}definition`),
      literal(`A relation between an Observation and the entity whose quality was observed, or between an Actuation and the entity whose property was modified, or between an act of Sampling and the entity that was sampled.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(`${skos}example`),
      literal(`For example, in an Observation of the weight of a person, the FeatureOfInterest is the person and the property is its weight.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Result`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sample`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${rdfs}comment`),
      literal(`Relation linking an Observation or Actuation or act of Sampling and a Result or Sample.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${rdfs}label`),
      literal(`has result`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}isResultOf`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasResult`),
      namedNode(`${skos}definition`),
      literal(`Relation linking an Observation or Actuation or act of Sampling and a Result or Sample.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSample`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSample`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sample`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSample`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSample`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between a FeatureOfInterest and the Sample used to represent it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSample`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSample`),
      namedNode(`${rdfs}label`),
      literal(`has sample`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSample`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}isSampleOf`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSample`),
      namedNode(`${skos}definition`),
      literal(`Relation between a FeatureOfInterest and the Sample used to represent it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSimpleResult`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSimpleResult`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSimpleResult`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSimpleResult`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSimpleResult`),
      namedNode(`${rdfs}comment`),
      literal(`The simple value of an Observation or Actuation or act of Sampling.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSimpleResult`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSimpleResult`),
      namedNode(`${rdfs}label`),
      literal(`has simple result`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSimpleResult`),
      namedNode(`${skos}definition`),
      literal(`The simple value of an Observation or Actuation or act of Sampling.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hasSimpleResult`),
      namedNode(`${skos}example`),
      literal(`For instance, the values 23 or true.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Platform`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Actuator`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Platform`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sampler`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sensor`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between a Platform and a Sensor, Actuator, Sampler, or Platform, hosted or mounted on it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${rdfs}label`),
      literal(`hosts`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}isHostedBy`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}hosts`),
      namedNode(`${skos}definition`),
      literal(`Relation between a Platform and a Sensor, Actuator, Sampler, or Platform, hosted or mounted on it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isActedOnBy`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}ActuatableProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isActedOnBy`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isActedOnBy`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isActedOnBy`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between an ActuatableProperty of a FeatureOfInterest and an Actuation changing its state.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isActedOnBy`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isActedOnBy`),
      namedNode(`${rdfs}label`),
      literal(`is acted on by`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isActedOnBy`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}actsOnProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isActedOnBy`),
      namedNode(`${skos}definition`),
      literal(`Relation between an ActuatableProperty of a FeatureOfInterest and an Actuation changing its state.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isActedOnBy`),
      namedNode(`${skos}example`),
      literal(`In the activity (Actuation) of automatically closing a window if the temperature in a room drops below 20 degrees Celsius, the property on which the Actuator acts upon is the state of the window as it changes from being open to being closed. `, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sample`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${rdfs}comment`),
      literal(`A relation between a FeatureOfInterest and an Observation about it, an Actuation acting on it, or an act of Sampling that sampled it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${rdfs}label`),
      literal(`is feature of interest of`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}hasFeatureOfInterest`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isFeatureOfInterestOf`),
      namedNode(`${skos}definition`),
      literal(`A relation between a FeatureOfInterest and an Observation about it, an Actuation acting on it, or an act of Sampling that sampled it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuator`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Platform`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sampler`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sensor`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Platform`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between a Sensor, Actuator, Sampler, or Platform, and the Platform that it is mounted on or hosted by.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${rdfs}label`),
      literal(`is hosted by`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}hosts`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isHostedBy`),
      namedNode(`${skos}definition`),
      literal(`Relation between a Sensor, Actuator, Sampler, or Platform, and the Platform that it is mounted on or hosted by.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isObservedBy`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}ObservableProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isObservedBy`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sensor`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isObservedBy`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isObservedBy`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between an ObservableProperty and the Sensor able to observe it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isObservedBy`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isObservedBy`),
      namedNode(`${rdfs}label`),
      literal(`is observed by`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isObservedBy`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}observes`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isObservedBy`),
      namedNode(`${skos}definition`),
      literal(`Relation between an ObservableProperty and the Sensor able to observe it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Result`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sample`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${rdfs}comment`),
      literal(`Relation linking a Result to the Observation or Actuation or act of Sampling that created or caused it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${rdfs}label`),
      literal(`is result of`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}hasResult`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isResultOf`),
      namedNode(`${skos}definition`),
      literal(`Relation linking a Result to the Observation or Actuation or act of Sampling that created or caused it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isSampleOf`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sample`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isSampleOf`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}FeatureOfInterest`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isSampleOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isSampleOf`),
      namedNode(`${rdfs}comment`),
      literal(`Relation from a Sample to the FeatureOfInterest that it is intended to be representative of.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isSampleOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isSampleOf`),
      namedNode(`${rdfs}label`),
      literal(`is sample of`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isSampleOf`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}hasSample`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}isSampleOf`),
      namedNode(`${skos}definition`),
      literal(`Relation from a Sample to the FeatureOfInterest that it is intended to be representative of.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeActuation`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuator`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeActuation`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeActuation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeActuation`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between an Actuator and the Actuation it has made.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeActuation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeActuation`),
      namedNode(`${rdfs}label`),
      literal(`made actuation`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeActuation`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}madeByActuator`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeActuation`),
      namedNode(`${skos}definition`),
      literal(`Relation between an Actuator and the Actuation it has made.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeByActuator`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeByActuator`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Actuator`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeByActuator`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeByActuator`),
      namedNode(`${rdfs}comment`),
      literal(`Relation linking an Actuation to the Actuator that made that Actuation.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeByActuator`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeByActuator`),
      namedNode(`${rdfs}label`),
      literal(`made by actuator`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeByActuator`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}madeActuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeByActuator`),
      namedNode(`${skos}definition`),
      literal(`Relation linking an Actuation to the Actuator that made that Actuation.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySampler`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySampler`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sampler`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySampler`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySampler`),
      namedNode(`${rdfs}comment`),
      literal(`Relation linking an act of Sampling to the Sampler (sampling device or entity) that made it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySampler`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySampler`),
      namedNode(`${rdfs}label`),
      literal(`made by sampler`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySampler`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}madeSampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySampler`),
      namedNode(`${skos}definition`),
      literal(`Relation linking an act of Sampling to the Sampler (sampling device or entity) that made it.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySensor`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySensor`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sensor`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySensor`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySensor`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between an Observation and the Sensor which made the Observation.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySensor`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySensor`),
      namedNode(`${rdfs}label`),
      literal(`made by sensor`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySensor`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}madeObservation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeBySensor`),
      namedNode(`${skos}definition`),
      literal(`Relation between an Observation and the Sensor which made the Observation.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeObservation`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sensor`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeObservation`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeObservation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeObservation`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between a Sensor and an Observation made by the Sensor.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeObservation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeObservation`),
      namedNode(`${rdfs}label`),
      literal(`made observation`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeObservation`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}madeBySensor`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeObservation`),
      namedNode(`${skos}definition`),
      literal(`Relation between a Sensor and an Observation made by the Sensor.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeSampling`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sampler`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeSampling`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeSampling`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeSampling`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between a Sampler (sampling device or entity) and the Sampling act it performed.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeSampling`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeSampling`),
      namedNode(`${rdfs}label`),
      literal(`made sampling`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeSampling`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}madeBySampler`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}madeSampling`),
      namedNode(`${skos}definition`),
      literal(`Relation between a Sampler (sampling device or entity) and the Sampling act it performed.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observedProperty`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observedProperty`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}ObservableProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observedProperty`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observedProperty`),
      namedNode(`${rdfs}comment`),
      literal(`Relation linking an Observation to the property that was observed. The ObservableProperty should be a property of the FeatureOfInterest (linked by hasFeatureOfInterest) of this Observation.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observedProperty`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observedProperty`),
      namedNode(`${rdfs}label`),
      literal(`observed property`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observedProperty`),
      namedNode(`${skos}definition`),
      literal(`Relation linking an Observation to the property that was observed. The ObservableProperty should be a property of the FeatureOfInterest (linked by hasFeatureOfInterest) of this Observation.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observes`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sensor`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observes`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}ObservableProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observes`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observes`),
      namedNode(`${rdfs}comment`),
      literal(`Relation between a Sensor and an ObservableProperty that it is capable of sensing.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observes`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observes`),
      namedNode(`${rdfs}label`),
      literal(`observes`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observes`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${sosa}isObservedBy`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}observes`),
      namedNode(`${skos}definition`),
      literal(`Relation between a Sensor and an ObservableProperty that it is capable of sensing.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}phenomenonTime`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}phenomenonTime`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}phenomenonTime`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}phenomenonTime`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${time}TemporalEntity`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}phenomenonTime`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}phenomenonTime`),
      namedNode(`${rdfs}comment`),
      literal(`The time that the Result of an Observation, Actuation or Sampling applies to the FeatureOfInterest. Not necessarily the same as the resultTime. May be an Interval or an Instant, or some other compound TemporalEntity.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}phenomenonTime`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}phenomenonTime`),
      namedNode(`${rdfs}label`),
      literal(`phenomenon time`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}phenomenonTime`),
      namedNode(`${skos}definition`),
      literal(`The time that the Result of an Observation, Actuation or Sampling applies to the FeatureOfInterest. Not necessarily the same as the resultTime. May be an Interval or an Instant, or some other compound TemporalEntity.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}resultTime`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}resultTime`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}resultTime`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}resultTime`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}resultTime`),
      namedNode(`${rdfs}comment`),
      literal(`The result time is the instant of time when the Observation, Actuation or Sampling activity was completed.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}resultTime`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}resultTime`),
      namedNode(`${rdfs}label`),
      literal(`result time`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}resultTime`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}dateTime`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}resultTime`),
      namedNode(`${skos}definition`),
      literal(`The result time is the instant of time when the Observation, Actuation or Sampling activity was completed.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}usedProcedure`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Actuation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}usedProcedure`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Observation`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}usedProcedure`),
      namedNode(`${schema}domainIncludes`),
      namedNode(`${sosa}Sampling`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}usedProcedure`),
      namedNode(`${schema}rangeIncludes`),
      namedNode(`${sosa}Procedure`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}usedProcedure`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}usedProcedure`),
      namedNode(`${rdfs}comment`),
      literal(`A relation to link to a re-usable Procedure used in making an Observation, an Actuation, or a Sample, typically through a Sensor, Actuator or Sampler.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}usedProcedure`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(sosa),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}usedProcedure`),
      namedNode(`${rdfs}label`),
      literal(`used procedure`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${sosa}usedProcedure`),
      namedNode(`${skos}definition`),
      literal(`A relation to link to a re-usable Procedure used in making an Observation, an Actuation, or a Sample, typically through a Sensor, Actuator or Sampler.`, 'en'),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${foaf}Agent`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(sosa)
    ),
    quad(
      namedNode(`${foaf}name`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(sosa)
    ),
    quad(
      blankNodes[0],
      namedNode(`${rdf}type`),
      namedNode(`${foaf}Agent`),
      namedNode(sosa)
    ),
    quad(
      blankNodes[0],
      namedNode(`${foaf}name`),
      literal(`W3C/OGC Spatial Data on the Web Working Group`, 'en'),
      namedNode(sosa)
    ),

  ]
}
