/* This file was automatically generated. Do not edit by hand. */

const {
  skos,
  rdf,
  owl,
  rdfs,
  ns5,
  dcterms,
  ns7
} = {
  'skos': 'http://www.w3.org/2004/02/skos/core#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'ns5': 'http://www.w3.org/2004/02/skos/',
  'dcterms': 'http://purl.org/dc/terms/',
  'ns7': 'http://www.w3.org/TR/skos-reference/'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 3; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(`${skos}Collection`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Collection`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Collection`),
      namedNode(`${rdfs}label`),
      literal(`Collection`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Collection`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${skos}Concept`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Collection`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${skos}ConceptScheme`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Collection`),
      namedNode(`${skos}definition`),
      literal(`A meaningful collection of concepts.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Collection`),
      namedNode(`${skos}scopeNote`),
      literal(`Labelled collections can be used where you would like a set of concepts to be displayed under a 'node label' in the hierarchy.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Concept`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Concept`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Concept`),
      namedNode(`${rdfs}label`),
      literal(`Concept`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}Concept`),
      namedNode(`${skos}definition`),
      literal(`An idea or notion; a unit of thought.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}ConceptScheme`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}ConceptScheme`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}ConceptScheme`),
      namedNode(`${rdfs}label`),
      literal(`Concept Scheme`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}ConceptScheme`),
      namedNode(`${owl}disjointWith`),
      namedNode(`${skos}Concept`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}ConceptScheme`),
      namedNode(`${skos}definition`),
      literal(`A set of concepts, optionally including statements about semantic relationships between those concepts.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}ConceptScheme`),
      namedNode(`${skos}example`),
      literal(`Thesauri, classification schemes, subject heading lists, taxonomies, 'folksonomies', and other types of controlled vocabulary are all examples of concept schemes. Concept schemes are also embedded in glossaries and terminologies.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}ConceptScheme`),
      namedNode(`${skos}scopeNote`),
      literal(`A concept scheme may be defined to include concepts from different sources.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}OrderedCollection`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}OrderedCollection`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}OrderedCollection`),
      namedNode(`${rdfs}label`),
      literal(`Ordered Collection`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}OrderedCollection`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${skos}Collection`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}OrderedCollection`),
      namedNode(`${skos}definition`),
      literal(`An ordered collection of concepts, where both the grouping and the ordering are meaningful.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}OrderedCollection`),
      namedNode(`${skos}scopeNote`),
      literal(`Ordered collections can be used where you would like a set of concepts to be displayed in a specific order, and optionally under a 'node label'.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}altLabel`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}altLabel`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}altLabel`),
      namedNode(`${rdfs}comment`),
      literal(`The range of skos:altLabel is the class of RDF plain literals.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}altLabel`),
      namedNode(`${rdfs}comment`),
      literal(`skos:prefLabel, skos:altLabel and skos:hiddenLabel are pairwise disjoint properties.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}altLabel`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}altLabel`),
      namedNode(`${rdfs}label`),
      literal(`alternative label`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}altLabel`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}label`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}altLabel`),
      namedNode(`${skos}definition`),
      literal(`An alternative lexical label for a resource.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}altLabel`),
      namedNode(`${skos}example`),
      literal(`Acronyms, abbreviations, spelling variants, and irregular plural/singular forms may be included among the alternative labels for a concept. Mis-spelled terms are normally included as hidden labels (see skos:hiddenLabel).`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broadMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broadMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broadMatch`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broadMatch`),
      namedNode(`${rdfs}label`),
      literal(`has broader match`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broadMatch`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}broader`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broadMatch`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}mappingRelation`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broadMatch`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${skos}narrowMatch`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broadMatch`),
      namedNode(`${skos}definition`),
      literal(`skos:broadMatch is used to state a hierarchical mapping link between two conceptual resources in different concept schemes.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broader`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broader`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broader`),
      namedNode(`${rdfs}comment`),
      literal(`Broader concepts are typically rendered as parents in a concept hierarchy (tree).`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broader`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broader`),
      namedNode(`${rdfs}label`),
      literal(`has broader`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broader`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}broaderTransitive`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broader`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${skos}narrower`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broader`),
      namedNode(`${skos}definition`),
      literal(`Relates a concept to a concept that is more general in meaning.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broader`),
      namedNode(`${skos}scopeNote`),
      literal(`By convention, skos:broader is only used to assert an immediate (i.e. direct) hierarchical link between two conceptual resources.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broaderTransitive`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broaderTransitive`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broaderTransitive`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}TransitiveProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broaderTransitive`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broaderTransitive`),
      namedNode(`${rdfs}label`),
      literal(`has broader transitive`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broaderTransitive`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}semanticRelation`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broaderTransitive`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${skos}narrowerTransitive`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broaderTransitive`),
      namedNode(`${skos}definition`),
      literal(`skos:broaderTransitive is a transitive superproperty of skos:broader.`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}broaderTransitive`),
      namedNode(`${skos}scopeNote`),
      literal(`By convention, skos:broaderTransitive is not used to make assertions. Rather, the properties can be used to draw inferences about the transitive closure of the hierarchical relation, which is useful e.g. when implementing a simple query expansion algorithm in a search application.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}changeNote`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}changeNote`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}changeNote`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}changeNote`),
      namedNode(`${rdfs}label`),
      literal(`change note`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}changeNote`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}note`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}changeNote`),
      namedNode(`${skos}definition`),
      literal(`A note about a modification to a concept.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}closeMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}closeMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}closeMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}SymmetricProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}closeMatch`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}closeMatch`),
      namedNode(`${rdfs}label`),
      literal(`has close match`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}closeMatch`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}mappingRelation`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}closeMatch`),
      namedNode(`${skos}definition`),
      literal(`skos:closeMatch is used to link two concepts that are sufficiently similar that they can be used interchangeably in some information retrieval applications. In order to avoid the possibility of "compound errors" when combining mappings across more than two concept schemes, skos:closeMatch is not declared to be a transitive property.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}definition`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}definition`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}definition`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}definition`),
      namedNode(`${rdfs}label`),
      literal(`definition`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}definition`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}note`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}definition`),
      namedNode(`${skos}definition`),
      literal(`A statement or formal explanation of the meaning of a concept.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}editorialNote`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}editorialNote`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}editorialNote`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}editorialNote`),
      namedNode(`${rdfs}label`),
      literal(`editorial note`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}editorialNote`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}note`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}editorialNote`),
      namedNode(`${skos}definition`),
      literal(`A note for an editor, translator or maintainer of the vocabulary.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}exactMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}exactMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}exactMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}SymmetricProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}exactMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}TransitiveProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}exactMatch`),
      namedNode(`${rdfs}comment`),
      literal(`skos:exactMatch is disjoint with each of the properties skos:broadMatch and skos:relatedMatch.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}exactMatch`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}exactMatch`),
      namedNode(`${rdfs}label`),
      literal(`has exact match`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}exactMatch`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}closeMatch`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}exactMatch`),
      namedNode(`${skos}definition`),
      literal(`skos:exactMatch is used to link two concepts, indicating a high degree of confidence that the concepts can be used interchangeably across a wide range of information retrieval applications. skos:exactMatch is a transitive property, and is a sub-property of skos:closeMatch.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}example`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}example`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}example`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}example`),
      namedNode(`${rdfs}label`),
      literal(`example`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}example`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}note`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}example`),
      namedNode(`${skos}definition`),
      literal(`An example of the use of a concept.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hasTopConcept`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hasTopConcept`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hasTopConcept`),
      namedNode(`${rdfs}domain`),
      namedNode(`${skos}ConceptScheme`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hasTopConcept`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hasTopConcept`),
      namedNode(`${rdfs}label`),
      literal(`has top concept`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hasTopConcept`),
      namedNode(`${rdfs}range`),
      namedNode(`${skos}Concept`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hasTopConcept`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${skos}topConceptOf`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hasTopConcept`),
      namedNode(`${skos}definition`),
      literal(`Relates, by convention, a concept scheme to a concept which is topmost in the broader/narrower concept hierarchies for that scheme, providing an entry point to these hierarchies.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hiddenLabel`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hiddenLabel`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hiddenLabel`),
      namedNode(`${rdfs}comment`),
      literal(`The range of skos:hiddenLabel is the class of RDF plain literals.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hiddenLabel`),
      namedNode(`${rdfs}comment`),
      literal(`skos:prefLabel, skos:altLabel and skos:hiddenLabel are pairwise disjoint properties.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hiddenLabel`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hiddenLabel`),
      namedNode(`${rdfs}label`),
      literal(`hidden label`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hiddenLabel`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}label`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}hiddenLabel`),
      namedNode(`${skos}definition`),
      literal(`A lexical label for a resource that should be hidden when generating visual displays of the resource, but should still be accessible to free text search operations.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}historyNote`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}historyNote`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}historyNote`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}historyNote`),
      namedNode(`${rdfs}label`),
      literal(`history note`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}historyNote`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}note`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}historyNote`),
      namedNode(`${skos}definition`),
      literal(`A note about the past state/use/meaning of a concept.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}inScheme`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}inScheme`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}inScheme`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}inScheme`),
      namedNode(`${rdfs}label`),
      literal(`is in scheme`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}inScheme`),
      namedNode(`${rdfs}range`),
      namedNode(`${skos}ConceptScheme`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}inScheme`),
      namedNode(`${skos}definition`),
      literal(`Relates a resource (for example a concept) to a concept scheme in which it is included.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}inScheme`),
      namedNode(`${skos}scopeNote`),
      literal(`A concept may be a member of more than one concept scheme.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}mappingRelation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}mappingRelation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}mappingRelation`),
      namedNode(`${rdfs}comment`),
      literal(`These concept mapping relations mirror semantic relations, and the data model defined below is similar (with the exception of skos:exactMatch) to the data model defined for semantic relations. A distinct vocabulary is provided for concept mapping relations, to provide a convenient way to differentiate links within a concept scheme from links between concept schemes. However, this pattern of usage is not a formal requirement of the SKOS data model, and relies on informal definitions of best practice.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}mappingRelation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}mappingRelation`),
      namedNode(`${rdfs}label`),
      literal(`is in mapping relation with`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}mappingRelation`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}semanticRelation`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}mappingRelation`),
      namedNode(`${skos}definition`),
      literal(`Relates two concepts coming, by convention, from different schemes, and that have comparable meanings`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}member`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}member`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}member`),
      namedNode(`${rdfs}domain`),
      namedNode(`${skos}Collection`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}member`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}member`),
      namedNode(`${rdfs}label`),
      literal(`has member`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}member`),
      namedNode(`${rdfs}range`),
      blankNodes[0],
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}member`),
      namedNode(`${skos}definition`),
      literal(`Relates a collection to one of its members.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}memberList`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}memberList`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}FunctionalProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}memberList`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}memberList`),
      namedNode(`${rdfs}comment`),
      literal(`For any resource, every item in the list given as the value of the
      skos:memberList property is also a value of the skos:member property.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}memberList`),
      namedNode(`${rdfs}domain`),
      namedNode(`${skos}OrderedCollection`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}memberList`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}memberList`),
      namedNode(`${rdfs}label`),
      literal(`has member list`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}memberList`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdf}List`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}memberList`),
      namedNode(`${skos}definition`),
      literal(`Relates an ordered collection to the RDF list containing its members.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowMatch`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowMatch`),
      namedNode(`${rdfs}label`),
      literal(`has narrower match`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowMatch`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}mappingRelation`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowMatch`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}narrower`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowMatch`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${skos}broadMatch`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowMatch`),
      namedNode(`${skos}definition`),
      literal(`skos:narrowMatch is used to state a hierarchical mapping link between two conceptual resources in different concept schemes.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrower`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrower`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrower`),
      namedNode(`${rdfs}comment`),
      literal(`Narrower concepts are typically rendered as children in a concept hierarchy (tree).`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrower`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrower`),
      namedNode(`${rdfs}label`),
      literal(`has narrower`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrower`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}narrowerTransitive`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrower`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${skos}broader`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrower`),
      namedNode(`${skos}definition`),
      literal(`Relates a concept to a concept that is more specific in meaning.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrower`),
      namedNode(`${skos}scopeNote`),
      literal(`By convention, skos:broader is only used to assert an immediate (i.e. direct) hierarchical link between two conceptual resources.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowerTransitive`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowerTransitive`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowerTransitive`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}TransitiveProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowerTransitive`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowerTransitive`),
      namedNode(`${rdfs}label`),
      literal(`has narrower transitive`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowerTransitive`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}semanticRelation`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowerTransitive`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${skos}broaderTransitive`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowerTransitive`),
      namedNode(`${skos}definition`),
      literal(`skos:narrowerTransitive is a transitive superproperty of skos:narrower.`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}narrowerTransitive`),
      namedNode(`${skos}scopeNote`),
      literal(`By convention, skos:narrowerTransitive is not used to make assertions. Rather, the properties can be used to draw inferences about the transitive closure of the hierarchical relation, which is useful e.g. when implementing a simple query expansion algorithm in a search application.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}notation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}notation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}DatatypeProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}notation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}notation`),
      namedNode(`${rdfs}label`),
      literal(`notation`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}notation`),
      namedNode(`${skos}definition`),
      literal(`A notation, also known as classification code, is a string of characters such as "T58.5" or "303.4833" used to uniquely identify a concept within the scope of a given concept scheme.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}notation`),
      namedNode(`${skos}scopeNote`),
      literal(`By convention, skos:notation is used with a typed literal in the object position of the triple.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}note`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}note`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}note`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}note`),
      namedNode(`${rdfs}label`),
      literal(`note`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}note`),
      namedNode(`${skos}definition`),
      literal(`A general note, for any purpose.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}note`),
      namedNode(`${skos}scopeNote`),
      literal(`This property may be used directly, or as a super-property for more specific note types.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}prefLabel`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}prefLabel`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}prefLabel`),
      namedNode(`${rdfs}comment`),
      literal(`A resource has no more than one value of skos:prefLabel per language tag, and no more than one value of skos:prefLabel without language tag.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}prefLabel`),
      namedNode(`${rdfs}comment`),
      literal(`The range of skos:prefLabel is the class of RDF plain literals.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}prefLabel`),
      namedNode(`${rdfs}comment`),
      literal(`skos:prefLabel, skos:altLabel and skos:hiddenLabel are pairwise
      disjoint properties.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}prefLabel`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}prefLabel`),
      namedNode(`${rdfs}label`),
      literal(`preferred label`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}prefLabel`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${rdfs}label`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}prefLabel`),
      namedNode(`${skos}definition`),
      literal(`The preferred lexical label for a resource, in a given language.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}related`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}related`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}related`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}SymmetricProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}related`),
      namedNode(`${rdfs}comment`),
      literal(`skos:related is disjoint with skos:broaderTransitive`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}related`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}related`),
      namedNode(`${rdfs}label`),
      literal(`has related`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}related`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}semanticRelation`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}related`),
      namedNode(`${skos}definition`),
      literal(`Relates a concept to a concept with which there is an associative semantic relationship.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}relatedMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}relatedMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}relatedMatch`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}SymmetricProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}relatedMatch`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}relatedMatch`),
      namedNode(`${rdfs}label`),
      literal(`has related match`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}relatedMatch`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}mappingRelation`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}relatedMatch`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}related`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}relatedMatch`),
      namedNode(`${skos}definition`),
      literal(`skos:relatedMatch is used to state an associative mapping link between two conceptual resources in different concept schemes.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}scopeNote`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}scopeNote`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}AnnotationProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}scopeNote`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}scopeNote`),
      namedNode(`${rdfs}label`),
      literal(`scope note`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}scopeNote`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}note`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}scopeNote`),
      namedNode(`${skos}definition`),
      literal(`A note that helps to clarify the meaning and/or the use of a concept.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}semanticRelation`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}semanticRelation`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}semanticRelation`),
      namedNode(`${rdfs}domain`),
      namedNode(`${skos}Concept`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}semanticRelation`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}semanticRelation`),
      namedNode(`${rdfs}label`),
      literal(`is in semantic relation with`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}semanticRelation`),
      namedNode(`${rdfs}range`),
      namedNode(`${skos}Concept`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}semanticRelation`),
      namedNode(`${skos}definition`),
      literal(`Links a concept to a concept related by meaning.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}semanticRelation`),
      namedNode(`${skos}scopeNote`),
      literal(`This property should not be used directly, but as a super-property for all properties denoting a relationship of meaning between concepts.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}topConceptOf`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}topConceptOf`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}topConceptOf`),
      namedNode(`${rdfs}domain`),
      namedNode(`${skos}Concept`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}topConceptOf`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(`${ns5}core`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}topConceptOf`),
      namedNode(`${rdfs}label`),
      literal(`is top concept in scheme`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}topConceptOf`),
      namedNode(`${rdfs}range`),
      namedNode(`${skos}ConceptScheme`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}topConceptOf`),
      namedNode(`${rdfs}subPropertyOf`),
      namedNode(`${skos}inScheme`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}topConceptOf`),
      namedNode(`${owl}inverseOf`),
      namedNode(`${skos}hasTopConcept`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${skos}topConceptOf`),
      namedNode(`${skos}definition`),
      literal(`Relates a concept to the concept scheme that it is a top level concept of.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${ns5}core`),
      namedNode(`${dcterms}contributor`),
      literal(`Dave Beckett`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${ns5}core`),
      namedNode(`${dcterms}contributor`),
      literal(`Nikki Rogers`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${ns5}core`),
      namedNode(`${dcterms}contributor`),
      literal(`Participants in W3C's Semantic Web Deployment Working Group.`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${ns5}core`),
      namedNode(`${dcterms}creator`),
      literal(`Alistair Miles`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${ns5}core`),
      namedNode(`${dcterms}creator`),
      literal(`Sean Bechhofer`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${ns5}core`),
      namedNode(`${dcterms}description`),
      literal(`An RDF vocabulary for describing the basic structure and content of concept schemes such as thesauri, classification schemes, subject heading lists, taxonomies, 'folksonomies', other types of controlled vocabulary, and also concept schemes embedded in glossaries and terminologies.`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${ns5}core`),
      namedNode(`${dcterms}title`),
      literal(`SKOS Vocabulary`, 'en'),
      namedNode(skos)
    ),
    quad(
      namedNode(`${ns5}core`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(skos)
    ),
    quad(
      namedNode(`${ns5}core`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(ns7),
      namedNode(skos)
    ),
    quad(
      blankNodes[1],
      namedNode(`${rdf}first`),
      namedNode(`${skos}Concept`),
      namedNode(skos)
    ),
    quad(
      blankNodes[1],
      namedNode(`${rdf}rest`),
      blankNodes[2],
      namedNode(skos)
    ),
    quad(
      blankNodes[2],
      namedNode(`${rdf}first`),
      namedNode(`${skos}Collection`),
      namedNode(skos)
    ),
    quad(
      blankNodes[2],
      namedNode(`${rdf}rest`),
      namedNode(`${rdf}nil`),
      namedNode(skos)
    ),
    quad(
      blankNodes[0],
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(skos)
    ),
    quad(
      blankNodes[0],
      namedNode(`${owl}unionOf`),
      blankNodes[1],
      namedNode(skos)
    ),

  ]
}
