name: Prefix reminder

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v7

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'

    - name: Verify prefixes coverage in packages/prefixes/prefixes.ts
      run: node .github/scripts/check-prefixes.js
