name: Prefix reminder

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: remind-about-prefixes
      uses: exercism/pr-commenter-action@v1.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        config-file: ".github/pr-commenter.yml"
