/* This file was automatically generated. Do not edit by hand. */

const {
  cnt,
  rdf,
  rdfs,
  owl,
  xsd,
  ns6,
  ns7,
  ns8,
  dcterms
} = {
  'cnt': 'http://www.w3.org/2011/content#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'owl': 'http://www.w3.org/2002/07/owl#',
  'xsd': 'http://www.w3.org/2001/XMLSchema#',
  'ns6': 'http://www.w3.org/2011/',
  'ns7': 'http://www.w3.org/TR/Content-in-RDF/',
  'ns8': 'http://www.w3.org/WAI/intro/',
  'dcterms': 'http://purl.org/dc/terms/'
}

export default ({ literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  return [
    quad(
      namedNode(`${cnt}Content`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}Content`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}Content`),
      namedNode(`${rdfs}comment`),
      literal(`The content.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}Content`),
      namedNode(`${rdfs}label`),
      literal(`Content`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsBase64`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsBase64`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsBase64`),
      namedNode(`${rdfs}comment`),
      literal(`The base64 encoded content (can be used for binary content).`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsBase64`),
      namedNode(`${rdfs}label`),
      literal(`Base64 content`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsBase64`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${cnt}Content`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsText`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsText`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsText`),
      namedNode(`${rdfs}comment`),
      literal(`The text content (can be used for text content).`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsText`),
      namedNode(`${rdfs}label`),
      literal(`Text content`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsText`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${cnt}Content`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsXML`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsXML`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsXML`),
      namedNode(`${rdfs}comment`),
      literal(`The XML content (can only be used for XML-wellformed content).`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsXML`),
      namedNode(`${rdfs}label`),
      literal(`XML content`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}ContentAsXML`),
      namedNode(`${rdfs}subClassOf`),
      namedNode(`${cnt}Content`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}DoctypeDecl`),
      namedNode(`${rdf}type`),
      namedNode(`${rdfs}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}DoctypeDecl`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Class`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}DoctypeDecl`),
      namedNode(`${rdfs}comment`),
      literal(`The document type declaration.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}DoctypeDecl`),
      namedNode(`${rdfs}label`),
      literal(`Document type declaration`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}bytes`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}bytes`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}bytes`),
      namedNode(`${rdfs}comment`),
      literal(`The Base64 encoded byte sequence of the content.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}bytes`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}ContentAsBase64`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}bytes`),
      namedNode(`${rdfs}label`),
      literal(`Base64 encoded byte sequence`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}bytes`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}base64Binary`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}characterEncoding`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}characterEncoding`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}characterEncoding`),
      namedNode(`${rdfs}comment`),
      literal(`The character encoding used to create a character sequence from a byte sequence or vice versa.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}characterEncoding`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}Content`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}characterEncoding`),
      namedNode(`${rdfs}label`),
      literal(`Character encoding`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}characterEncoding`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}chars`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}chars`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}chars`),
      namedNode(`${rdfs}comment`),
      literal(`The character sequence of the text content.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}chars`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}ContentAsText`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}chars`),
      namedNode(`${rdfs}label`),
      literal(`Character sequence`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}chars`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}declaredEncoding`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}declaredEncoding`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}declaredEncoding`),
      namedNode(`${rdfs}comment`),
      literal(`The character encoding declared in the XML declaration.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}declaredEncoding`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}ContentAsXML`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}declaredEncoding`),
      namedNode(`${rdfs}label`),
      literal(`XML character encoding`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}declaredEncoding`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}doctypeName`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}doctypeName`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}doctypeName`),
      namedNode(`${rdfs}comment`),
      literal(`The document type name.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}doctypeName`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}DoctypeDecl`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}doctypeName`),
      namedNode(`${rdfs}label`),
      literal(`Document type name`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}doctypeName`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}dtDecl`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}dtDecl`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}dtDecl`),
      namedNode(`${rdfs}comment`),
      literal(`The document type declaration.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}dtDecl`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}ContentAsXML`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}dtDecl`),
      namedNode(`${rdfs}label`),
      literal(`Document type declaration`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}dtDecl`),
      namedNode(`${rdfs}range`),
      namedNode(`${cnt}DoctypeDecl`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}internalSubset`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}internalSubset`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}internalSubset`),
      namedNode(`${rdfs}comment`),
      literal(`The internal document type definition subset within the document type declarations.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}internalSubset`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}DoctypeDecl`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}internalSubset`),
      namedNode(`${rdfs}label`),
      literal(`Internal DTD subset`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}internalSubset`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}leadingMisc`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}leadingMisc`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}leadingMisc`),
      namedNode(`${rdfs}comment`),
      literal(`The XML content preceding the document type declaration.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}leadingMisc`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}ContentAsXML`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}leadingMisc`),
      namedNode(`${rdfs}label`),
      literal(`XML leading misc`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}leadingMisc`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}XMLLiteral`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}publicId`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}publicId`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}publicId`),
      namedNode(`${rdfs}comment`),
      literal(`The document type declarations's public identifier.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}publicId`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}DoctypeDecl`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}publicId`),
      namedNode(`${rdfs}label`),
      literal(`Public ID`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}publicId`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}rest`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}rest`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}rest`),
      namedNode(`${rdfs}comment`),
      literal(`The XML content following the document type declaration.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}rest`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}ContentAsXML`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}rest`),
      namedNode(`${rdfs}label`),
      literal(`XML rest`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}rest`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}XMLLiteral`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}standalone`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}standalone`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}standalone`),
      namedNode(`${rdfs}comment`),
      literal(`The standalone declaration in the XML declaration.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}standalone`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}ContentAsXML`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}standalone`),
      namedNode(`${rdfs}label`),
      literal(`XML standalone document declaration`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}standalone`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}systemId`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}systemId`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}systemId`),
      namedNode(`${rdfs}comment`),
      literal(`The document type declarations's system identifier (typed: xsd:anyURI)`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}systemId`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}DoctypeDecl`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}systemId`),
      namedNode(`${rdfs}label`),
      literal(`System ID`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}systemId`),
      namedNode(`${rdfs}range`),
      namedNode(`${xsd}anyURI`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}version`),
      namedNode(`${rdf}type`),
      namedNode(`${rdf}Property`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}version`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}ObjectProperty`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}version`),
      namedNode(`${rdfs}comment`),
      literal(`The XML version declared in the XML declaration.`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}version`),
      namedNode(`${rdfs}domain`),
      namedNode(`${cnt}ContentAsXML`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}version`),
      namedNode(`${rdfs}label`),
      literal(`XML version`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${cnt}version`),
      namedNode(`${rdfs}range`),
      namedNode(`${rdfs}Literal`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${ns6}content`),
      namedNode(`${rdf}type`),
      namedNode(`${owl}Ontology`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${ns6}content`),
      namedNode(`${rdfs}comment`),
      literal(`Representing Content in RDF as defined by http://www.w3.org/TR/Content-in-RDF/`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${ns6}content`),
      namedNode(`${rdfs}isDefinedBy`),
      namedNode(ns7),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${ns6}content`),
      namedNode(`${rdfs}label`),
      literal(`Representing Content in RDF`, 'en'),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${ns6}content`),
      namedNode(`${rdfs}seeAlso`),
      namedNode(`${ns8}earl`),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${ns6}content`),
      namedNode(`${owl}imports`),
      namedNode(dcterms),
      namedNode(cnt)
    ),
    quad(
      namedNode(`${ns6}content`),
      namedNode(`${owl}versionInfo`),
      literal(`Working Draft 29 April 2011`, 'en'),
      namedNode(cnt)
    ),

  ]
}
